import { createHash, randomUUID } from 'crypto';
import { supabase } from '../db/supabaseClient';

// eslint-disable-next-line @typescript-eslint/no-var-requires
const sharp = require('sharp') as typeof import('sharp');

type RenderedMediaBundle = {
  url?: string;
  files?: string[];
  metadata?: Record<string, unknown>;
};

type RenderOptions = {
  campaignId?: string | null;
  userId?: string | null;
};

const IMAGE_BUCKET = 'media-images';
const FALLBACK_BASE = 'https://dummyimage.com';
let bucketReady: Promise<void> | null = null;

function safeObject(value: unknown): Record<string, unknown> {
  return value && typeof value === 'object' && !Array.isArray(value) ? value as Record<string, unknown> : {};
}

function escapeXml(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

function wrapText(value: string, maxChars: number, maxLines: number): string[] {
  const words = value.trim().split(/\s+/).filter(Boolean);
  if (words.length === 0) return [];

  const lines: string[] = [];
  let current = '';
  for (const word of words) {
    const next = current ? `${current} ${word}` : word;
    if (next.length <= maxChars) {
      current = next;
      continue;
    }
    if (current) lines.push(current);
    current = word;
    if (lines.length >= maxLines - 1) break;
  }
  if (current && lines.length < maxLines) lines.push(current);
  return lines.slice(0, maxLines);
}

function createFallbackUrl(label: string, width: number, height: number): string {
  const text = encodeURIComponent(label.trim() || 'Creator Asset');
  return `${FALLBACK_BASE}/${width}x${height}/111827/ffffff.png?text=${text}`;
}

function buildSvg(input: {
  width: number;
  height: number;
  eyebrow?: string;
  title: string;
  body: string;
}): string {
  const titleLines = wrapText(input.title, 22, 3);
  const bodyLines = wrapText(input.body, 34, 5);
  const titleY = 220;
  const bodyY = titleY + titleLines.length * 78 + 30;

  return `
    <svg width="${input.width}" height="${input.height}" viewBox="0 0 ${input.width} ${input.height}" xmlns="http://www.w3.org/2000/svg">
      <defs>
        <linearGradient id="creator-bg" x1="0%" y1="0%" x2="100%" y2="100%">
          <stop offset="0%" stop-color="#0f172a" />
          <stop offset="50%" stop-color="#1d4ed8" />
          <stop offset="100%" stop-color="#0891b2" />
        </linearGradient>
      </defs>
      <rect width="${input.width}" height="${input.height}" rx="36" fill="url(#creator-bg)" />
      <circle cx="${input.width - 140}" cy="120" r="82" fill="rgba(255,255,255,0.12)" />
      <circle cx="120" cy="${input.height - 110}" r="56" fill="rgba(255,255,255,0.08)" />
      <rect x="72" y="72" width="${input.width - 144}" height="${input.height - 144}" rx="28" fill="rgba(15,23,42,0.18)" stroke="rgba(255,255,255,0.14)" />
      ${input.eyebrow ? `<text x="110" y="148" fill="#bfdbfe" font-size="28" font-family="Arial, Helvetica, sans-serif" font-weight="700" letter-spacing="3">${escapeXml(input.eyebrow.toUpperCase())}</text>` : ''}
      ${titleLines.map((line, index) => `<text x="110" y="${titleY + (index * 78)}" fill="#ffffff" font-size="64" font-family="Arial, Helvetica, sans-serif" font-weight="800">${escapeXml(line)}</text>`).join('')}
      ${bodyLines.map((line, index) => `<text x="110" y="${bodyY + (index * 48)}" fill="#e2e8f0" font-size="34" font-family="Arial, Helvetica, sans-serif" font-weight="500">${escapeXml(line)}</text>`).join('')}
      <rect x="110" y="${input.height - 140}" width="180" height="10" rx="5" fill="#f8fafc" opacity="0.85" />
    </svg>
  `.trim();
}

async function renderPng(input: {
  title: string;
  body: string;
  eyebrow?: string;
  width?: number;
  height?: number;
}): Promise<Buffer> {
  const width = input.width ?? 1200;
  const height = input.height ?? 1200;
  const svg = buildSvg({
    width,
    height,
    eyebrow: input.eyebrow,
    title: input.title || 'Creator Asset',
    body: input.body || 'Generated by Omnivyra Creator',
  });

  return sharp(Buffer.from(svg))
    .png()
    .toBuffer();
}

async function uploadRenderedPng(input: {
  fileBuffer: Buffer;
  campaignId?: string | null;
  userId?: string | null;
  fileNamePrefix: string;
  metadata?: Record<string, unknown>;
}): Promise<string> {
  await ensureImageBucket();
  const userPrefix = String(input.userId || 'system');
  const campaignPrefix = String(input.campaignId || 'standalone');
  const digest = createHash('sha1').update(input.fileBuffer).digest('hex').slice(0, 12);
  const objectPath = `creator/${campaignPrefix}/${userPrefix}/${Date.now()}-${input.fileNamePrefix}-${digest}-${randomUUID().slice(0, 8)}.png`;

  const { error: uploadError } = await supabase.storage
    .from(IMAGE_BUCKET)
    .upload(objectPath, input.fileBuffer, {
      contentType: 'image/png',
      upsert: true,
      cacheControl: '3600',
    });

  if (uploadError) {
    throw new Error(`Failed to upload rendered asset: ${uploadError.message}`);
  }

  const { data } = supabase.storage.from(IMAGE_BUCKET).getPublicUrl(objectPath);
  return data.publicUrl;
}

async function ensureImageBucket(): Promise<void> {
  if (!bucketReady) {
    bucketReady = (async () => {
      const { data: buckets, error: listError } = await supabase.storage.listBuckets();
      if (listError) {
        throw new Error(`Failed to inspect storage buckets: ${listError.message}`);
      }
      const exists = Array.isArray(buckets) && buckets.some((bucket) => bucket.name === IMAGE_BUCKET);
      if (exists) return;

      const { error: createError } = await supabase.storage.createBucket(IMAGE_BUCKET, {
        public: true,
        fileSizeLimit: 10 * 1024 * 1024,
        allowedMimeTypes: ['image/png', 'image/jpeg'],
      });
      if (createError && !/already exists/i.test(createError.message)) {
        throw new Error(`Failed to create storage bucket: ${createError.message}`);
      }
    })().catch((error) => {
      bucketReady = null;
      throw error;
    });
  }

  return bucketReady;
}

async function renderImageLikeAsset(
  assetPayload: Record<string, unknown>,
  options: RenderOptions,
  fileNamePrefix: string
): Promise<RenderedMediaBundle> {
  const descriptor = safeObject(assetPayload.visual_descriptor);
  const captionBlueprint = safeObject(assetPayload.caption_blueprint);
  const title = String(descriptor.headline ?? captionBlueprint.hook ?? 'Creator Asset');
  const body = String(descriptor.visual_description ?? captionBlueprint.body ?? 'Generated creative asset');
  const fileBuffer = await renderPng({ title, body });
  const url = await uploadRenderedPng({
    fileBuffer,
    campaignId: options.campaignId,
    userId: options.userId,
    fileNamePrefix,
    metadata: { width: 1200, height: 1200 },
  });
  return {
    url,
    metadata: {
      width: 1200,
      height: 1200,
      generated_by: 'creatorAssetRenderer',
    },
  };
}

async function renderCarouselLikeAsset(
  assetPayload: Record<string, unknown>,
  options: RenderOptions,
  items: Array<Record<string, unknown>>,
  fallbackLabel: string,
  fileNamePrefix: string
): Promise<RenderedMediaBundle> {
  const files: string[] = [];
  for (let index = 0; index < items.length; index += 1) {
    const item = safeObject(items[index]);
    const title = String(item.headline ?? `Slide ${index + 1}`);
    const body = String(item.body_text ?? item.text ?? fallbackLabel);
    const eyebrow = String(item.role ?? `Slide ${index + 1}`);
    const fileBuffer = await renderPng({ title, body, eyebrow });
    const url = await uploadRenderedPng({
      fileBuffer,
      campaignId: options.campaignId,
      userId: options.userId,
      fileNamePrefix: `${fileNamePrefix}-${index + 1}`,
      metadata: { width: 1200, height: 1200, slide_number: index + 1 },
    });
    files.push(url);
  }
  return {
    files,
    metadata: {
      width: 1200,
      height: 1200,
      generated_by: 'creatorAssetRenderer',
      item_count: files.length,
    },
  };
}

export async function renderAsset(
  assetPayload: Record<string, unknown>,
  options: RenderOptions = {}
): Promise<RenderedMediaBundle> {
  const assetKind = String(assetPayload.asset_kind || '').trim();

  try {
    if (assetKind === 'image') {
      return await renderImageLikeAsset(assetPayload, options, 'image');
    }

    if (assetKind === 'carousel') {
      const slides = Array.isArray(assetPayload.slides)
        ? assetPayload.slides.filter((slide) => slide && typeof slide === 'object' && !Array.isArray(slide)).map((slide) => slide as Record<string, unknown>)
        : [];
      const threadSequence = Array.isArray(assetPayload.thread_sequence)
        ? assetPayload.thread_sequence.filter((item) => item && typeof item === 'object' && !Array.isArray(item)).map((item) => item as Record<string, unknown>)
        : [];
      const items = slides.length > 0 ? slides : threadSequence;
      if (items.length > 0) {
        return await renderCarouselLikeAsset(assetPayload, options, items, 'Creator carousel asset', 'carousel');
      }
    }

    if (assetKind === 'video') {
      return {
        url: createFallbackUrl('Creator Video', 1280, 720),
        metadata: {
          width: 1280,
          height: 720,
          generated_by: 'creatorAssetRenderer',
          placeholder: true,
        },
      };
    }
  } catch {
    return {
      url: createFallbackUrl('Creator Asset', 1200, 1200),
      metadata: {
        width: 1200,
        height: 1200,
        generated_by: 'creatorAssetRenderer',
        placeholder: true,
      },
    };
  }

  return {
    url: createFallbackUrl('Creator Asset', 1200, 1200),
    metadata: {
      width: 1200,
      height: 1200,
      generated_by: 'creatorAssetRenderer',
      placeholder: true,
    },
  };
}
