-- Campaign Activity Engagement Signals
-- Stores engagement signals (comments, replies, mentions, etc.) linked to campaign activities.
-- Run in Supabase SQL Editor.

CREATE TABLE IF NOT EXISTS campaign_activity_engagement_signals (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  campaign_id UUID NOT NULL,
  activity_id TEXT NOT NULL,
  platform TEXT NOT NULL,
  source_type TEXT NOT NULL,
  source_id TEXT,
  conversation_url TEXT,
  author TEXT,
  content TEXT,
  signal_type TEXT NOT NULL CHECK (signal_type IN (
    'comment', 'reply', 'mention', 'quote', 'discussion', 'buyer_intent_signal'
  )),
  engagement_score NUMERIC NOT NULL DEFAULT 0,
  detected_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  organization_id UUID,
  raw_payload JSONB
);

CREATE INDEX IF NOT EXISTS idx_campaign_activity_signals_campaign
  ON campaign_activity_engagement_signals(campaign_id);
CREATE INDEX IF NOT EXISTS idx_campaign_activity_signals_activity
  ON campaign_activity_engagement_signals(activity_id);
CREATE INDEX IF NOT EXISTS idx_campaign_activity_signals_platform
  ON campaign_activity_engagement_signals(platform);
CREATE INDEX IF NOT EXISTS idx_campaign_activity_signals_detected
  ON campaign_activity_engagement_signals(detected_at DESC);
CREATE INDEX IF NOT EXISTS idx_campaign_activity_signals_score
  ON campaign_activity_engagement_signals(engagement_score DESC);

COMMENT ON TABLE campaign_activity_engagement_signals IS 'Engagement signals generated by campaign activities; used by Campaign Planner integration';
