/**
 * GET /api/super-admin/savings-report
 *
 * Returns the Redis-ops savings generated by the user-intent driven scheduler.
 *
 * Response:
 *   {
 *     date:               "2026-03-25",
 *     skippedJobsCount:   142,
 *     skippedRedisOpsEst: 2840,
 *     byReason: {
 *       feature_disabled:       80,
 *       no_active_companies:    40,
 *       company_inactive:       12,
 *       frequency_not_elapsed:  10,
 *     },
 *     summary: "Saved ~2.8k Redis ops today by skipping 142 unused job runs",
 *     history: [
 *       { date: "2026-03-19", skippedJobs: 98,  skippedOps: 1960 },
 *       ...
 *     ]
 *   }
 *
 * Auth: super_admin_session cookie OR Supabase SUPER_ADMIN role
 */

import type { NextApiRequest, NextApiResponse } from 'next';
import { getSupabaseUserFromRequest } from '../../../backend/services/supabaseAuthService';
import { isPlatformSuperAdmin } from '../../../backend/services/rbacService';
import { getSavingsReport } from '../../../backend/services/intentExecutionService';

async function requireSuperAdmin(req: NextApiRequest, res: NextApiResponse): Promise<boolean> {
  if (req.cookies?.super_admin_session === '1') return true;
  const { user, error } = await getSupabaseUserFromRequest(req);
  if (!error && user?.id && await isPlatformSuperAdmin(user.id)) return true;
  res.status(403).json({ error: 'NOT_AUTHORIZED' });
  return false;
}

export default async function handler(req: NextApiRequest, res: NextApiResponse) {
  if (req.method !== 'GET') return res.status(405).json({ error: 'Method not allowed' });
  if (!(await requireSuperAdmin(req, res))) return;

  const report = await getSavingsReport();
  return res.status(200).json(report);
}
