
/**
 * GET /api/super-admin/savings-report
 *
 * Returns the Redis-ops savings generated by the user-intent driven scheduler.
 *
 * Response:
 *   {
 *     date:               "2026-03-25",
 *     skippedJobsCount:   142,
 *     skippedRedisOpsEst: 2840,
 *     byReason: {
 *       feature_disabled:       80,
 *       no_active_companies:    40,
 *       company_inactive:       12,
 *       frequency_not_elapsed:  10,
 *     },
 *     summary: "Saved ~2.8k Redis ops today by skipping 142 unused job runs",
 *     history: [
 *       { date: "2026-03-19", skippedJobs: 98,  skippedOps: 1960 },
 *       ...
 *     ]
 *   }
 *
 * Auth: super_admin_session cookie OR Supabase SUPER_ADMIN role
 */

import type { NextApiRequest, NextApiResponse } from 'next';
import { requireAdminScope } from '../../../backend/services/requestAccessService';
import { getSavingsReport } from '../../../backend/services/intentExecutionService';

export default async function handler(req: NextApiRequest, res: NextApiResponse) {
  if (req.method !== 'GET') return res.status(405).json({ error: 'Method not allowed' });
  const ctx = await requireAdminScope(req, res, 'analytics:savings-report');
  if (!ctx) return;
  if (process.env.NODE_ENV !== 'production') {
    console.warn('[ADMIN_SCOPE]', '/api/super-admin/savings-report', 'analytics:savings-report');
  }

  const report = await getSavingsReport();
  return res.status(200).json(report);
}
