/**
 * WS-1c-4 (PMO Zone A1) — LONG-FORM RUNTIME DELEGATION SEAM.
 *
 * The canonical long-form entry funnel (`runUnifiedLongFormGeneration`) produces
 * every long-form family (blog / article / guide / newsletter / whitepaper /
 * story / case-study) through the "compatibility-core" full generator
 * `runBlogGeneration`. That call is the ONE chokepoint all long-form
 * compatibility-core generation passes through.
 *
 * This module lets that chokepoint flow through the runtime's long-form seam —
 * `backend/services/content/runtime/longFormRuntimeAdapter` — WITHOUT changing a
 * single generated byte. The adapter is a fail-safe observability envelope: it
 * delegates to `runBlogGeneration` UNCHANGED and returns its EXACT native result
 * (see the adapter's own contract). So:
 *
 *   flag OFF (default) ⇒ the legacy fn is called DIRECTLY — byte-identical to
 *                        pre-WS-1c-4, zero new imports on the hot path.
 *   flag ON            ⇒ the SAME request runs through the adapter, which returns
 *                        the SAME result plus best-effort metrics/timing that can
 *                        never alter or break generation.
 *
 * CYCLE SAFETY — the adapter statically imports the article/story runners, which
 * chain back through `runManagedContentGeneration → runUnifiedLongFormGeneration`.
 * A STATIC import of the adapter from the long-form graph would therefore form an
 * import cycle. We break it with a LAZY dynamic `import()` performed only when the
 * flag is ON, and we inject the legacy fn rather than importing it here — so this
 * module carries no runtime dependency on either engine.
 */

import type { BlogGenerationRequest, BlogGenerationResult } from '../blog/runBlogGeneration';

/**
 * Reads `LONGFORM_RUNTIME_DELEGATION_ENABLED`. Matches the exact convention of the
 * existing sacred delegation flags (WRITER_/TEXTGEN_/BOLT_/CONTENTGEN_DAY_):
 * truthy only for 1/true/on/yes (case-insensitive); default (unset/empty) is OFF.
 */
export function isLongFormRuntimeDelegationEnabled(): boolean {
  return /^(1|true|on|yes)$/.test(
    String(process.env.LONGFORM_RUNTIME_DELEGATION_ENABLED ?? '').trim().toLowerCase(),
  );
}

/**
 * Dispatch the compatibility-core blog generation either directly (legacy) or
 * through the runtime's long-form adapter envelope (flag ON). BYTE-IDENTICAL in
 * both branches: the adapter returns the engine's exact native result.
 *
 * @param req    the fully-built BlogGenerationRequest the funnel already assembled
 * @param legacy the legacy engine fn (`runBlogGeneration`), injected to avoid a
 *               static import cycle and to keep this seam trivially testable.
 */
export async function dispatchLongFormCompatibilityCore(
  req: BlogGenerationRequest,
  legacy: (r: BlogGenerationRequest) => Promise<BlogGenerationResult>,
): Promise<BlogGenerationResult> {
  if (!isLongFormRuntimeDelegationEnabled()) {
    return legacy(req);
  }
  // Lazy — loaded only when the operator has opted in. Breaks the static cycle.
  const { longFormRuntimeAdapter } = await import(
    '../../backend/services/content/runtime/longFormRuntimeAdapter'
  );
  return longFormRuntimeAdapter.runBlog(req);
}
