/**
 * @jest-environment jsdom
 *
 * A2 — ICP review / edit / ratification workspace DOM tests.
 *
 * Follows the repository's `.dom.test.tsx` convention: RTL scoped to one
 * surface, jsdom via the pragma above.
 *
 * The load-bearing assertions are the ones a careless review screen would fail:
 * a title shortlist saved as several criteria (which would score a match at
 * 0.2), proposal confidence relabelled as ICP fit, an inferred target rendered
 * as observed, an edit that mutates instead of versioning, and — worst —
 * ratification happening without an explicit human confirmation.
 */

import React from 'react';
import { render, screen, waitFor, fireEvent } from '@testing-library/react';
import '@testing-library/jest-dom';
import { SWRConfig } from 'swr';

const mockApiFetch = jest.fn();
let mockCompanyId: string | null = 'company-1';

jest.mock('@/lib/apiFetch', () => ({
  apiFetch: (u: string, init?: RequestInit) => mockApiFetch(u, init),
}));
jest.mock('@/components/CompanyContext', () => ({
  useCompanyContext: () => ({ selectedCompanyId: mockCompanyId }),
}));

// eslint-disable-next-line @typescript-eslint/no-var-requires
const IcpWorkspace = require('@/components/prospects/icp/IcpWorkspace').default;

const TITLE_UNION = {
  id: 'person-title-union',
  kind: 'required',
  subject: 'person',
  attribute: 'job_title',
  predicate: { op: 'one_of', values: ['Head of Marketing', 'Marketing Manager'] },
  description: 'Union of the 2 ranked target title(s).',
};

const proposalVersion = (over: Record<string, unknown> = {}) => ({
  id: 'v-1', version: 2, status: 'proposed', proposedByModel: 'gpt-4o-mini',
  ratifiedAt: null, createdAt: '2026-09-05T00:00:00.000Z',
  criteria: [
    {
      id: 'account-industry', kind: 'optional', subject: 'account', attribute: 'industry',
      predicate: { op: 'one_of', values: ['Marketing Technology'] },
      description: 'Sells marketing technology. [evidence: industry]',
    },
    TITLE_UNION,
    {
      id: 'person-department', kind: 'optional', subject: 'person', attribute: 'department',
      predicate: { op: 'one_of', values: ['Marketing'] }, description: 'Function check.',
    },
  ],
  proposal: {
    status: 'ai_suggested',
    ai_value: 'Generated by direct-openai/gpt-4o-mini · prompt pi.a1.icp_generator@1 · trace trace-abc',
    guidance: 'Not expressible as criteria: problem_relevance — buyers feel fragmentation acutely.',
    targets: [
      {
        rank: 1, title: 'Marketing Manager', roleTypes: ['user', 'evaluator'],
        derivation: 'directly_evidenced', confidence: 'high',
        evidenceFields: ['target_audience_list'], evidenceQuotes: ['Marketing managers'],
        orgAssumption: 'A marketing function exists at SMB scale.',
      },
      {
        rank: 2, title: 'Head of Marketing', roleTypes: ['economic_buyer'],
        derivation: 'inferred', confidence: 'medium',
        evidenceFields: ['target_customer_segment'], evidenceQuotes: [],
        orgAssumption: 'Senior-most marketer holds the budget at SMB scale.',
      },
    ],
    rejected: [{ title: 'CMO', reason: 'Above the authority ceiling implied by the price point.' }],
    stageAssumption: { stage: 'smb', evidenceFields: ['target_customer_segment'], rationale: 'Segment spans startups through SMB.' },
  },
  ...over,
});

const workspace = (over: Record<string, unknown> = {}) => ({
  state: 'available',
  reason: 'ok',
  data: {
    icpKey: 'first-cut', icpId: 'icp-1', ratified: null,
    proposals: [proposalVersion()],
    history: [{ version: 2, status: 'proposed', createdAt: '2026-09-05T00:00:00.000Z', ratifiedAt: null, proposedByModel: 'gpt-4o-mini', criteriaCount: 3, targetCount: 2 }],
    proposalChoiceRequired: false,
    ...over,
  },
});

/** Queues the workspace GET; POSTs are queued per test. */
function mockGet(payload: unknown) {
  mockApiFetch.mockImplementation((url: string) => {
    if (url.startsWith('/api/prospect-icp/versions')) {
      return Promise.resolve({ ok: true, json: async () => payload });
    }
    throw new Error(`unexpected request: ${url}`);
  });
}

const renderWorkspace = () => render(
  <SWRConfig value={{ dedupingInterval: 0, provider: () => new Map() }}>
    <IcpWorkspace />
  </SWRConfig>,
);

beforeEach(() => { mockApiFetch.mockReset(); mockCompanyId = 'company-1'; });

describe('A2 — proposal rendering', () => {
  it('renders the AI proposal with its criteria, targets and provenance', async () => {
    mockGet(workspace());
    renderWorkspace();

    expect(await screen.findByTestId('proposal-version-2')).toBeInTheDocument();
    expect(screen.getByTestId('criterion-account-industry')).toHaveTextContent('industry');
    expect(screen.getByTestId('criterion-person-department')).toHaveTextContent('department');
    expect(screen.getByTestId('proposal-metadata')).toHaveTextContent('gpt-4o-mini');
    expect(screen.getByTestId('proposal-metadata')).toHaveTextContent('trace-abc');
    expect(screen.getByTestId('ranked-targets')).toHaveTextContent('Marketing Manager');
  });

  it('renders the empty state as empty, never as an error', async () => {
    mockGet({ state: 'empty', reason: "no ICP named 'first-cut' exists in this tenant yet", data: null });
    renderWorkspace();
    expect(await screen.findByTestId('icp-empty')).toHaveTextContent('no ICP named');
    expect(screen.queryByTestId('icp-failed')).not.toBeInTheDocument();
  });

  it('renders a failed read as failed, distinct from empty', async () => {
    mockGet({ state: 'failed', reason: 'version list read failed', data: null });
    renderWorkspace();
    expect(await screen.findByTestId('icp-failed')).toHaveTextContent('version list read failed');
    expect(screen.queryByTestId('icp-empty')).not.toBeInTheDocument();
  });

  it('renders a transport error without claiming the ICP changed', async () => {
    mockApiFetch.mockImplementation(() => Promise.reject(new Error('network down')));
    renderWorkspace();
    expect(await screen.findByTestId('icp-transport-error')).toHaveTextContent('only unread');
  });

  it('asks for a company before reading anything', () => {
    mockCompanyId = null;
    renderWorkspace();
    expect(screen.getByText(/Select a company/i)).toBeInTheDocument();
    expect(mockApiFetch).not.toHaveBeenCalled();
  });
});

describe('A2 — the title union stays ONE criterion', () => {
  it('renders the shortlist as a single editable union, not as separate criteria', async () => {
    mockGet(workspace());
    renderWorkspace();

    expect(await screen.findByTestId('title-union-editor')).toBeInTheDocument();
    expect(screen.getByTestId('title-value-Marketing Manager')).toBeInTheDocument();
    expect(screen.getByTestId('title-value-Head of Marketing')).toBeInTheDocument();
    // The titles must NOT each appear as their own criterion row.
    expect(screen.queryByTestId('criterion-Marketing Manager')).not.toBeInTheDocument();
    expect(screen.queryByTestId('criterion-Head of Marketing')).not.toBeInTheDocument();
  });

  it('saves an edited shortlist as ONE job_title criterion — the 0.2 defect cannot be reintroduced', async () => {
    mockGet(workspace());
    let posted: Record<string, unknown> | null = null;
    mockApiFetch.mockImplementation((url: string, init?: RequestInit) => {
      if (url.startsWith('/api/prospect-icp/versions')) {
        return Promise.resolve({ ok: true, json: async () => workspace() });
      }
      posted = JSON.parse(String(init?.body));
      return Promise.resolve({ ok: true, json: async () => ({ version: 3 }) });
    });

    renderWorkspace();
    await screen.findByTestId('title-union-editor');

    fireEvent.change(screen.getByLabelText('Add a job title'), { target: { value: 'Growth Lead' } });
    fireEvent.click(screen.getByText('Add title'));
    fireEvent.click(screen.getByTestId('save-edits'));

    await waitFor(() => expect(posted).not.toBeNull());
    const criteria = (posted as { criteria: Array<Record<string, unknown>> }).criteria;
    const titleCriteria = criteria.filter((c) => c.attribute === 'job_title');

    expect(titleCriteria).toHaveLength(1);                       // the whole point
    expect(titleCriteria[0].id).toBe('person-title-union');
    expect((titleCriteria[0].predicate as { op: string }).op).toBe('one_of');
    expect((titleCriteria[0].predicate as { values: string[] }).values)
      .toEqual(['Head of Marketing', 'Marketing Manager', 'Growth Lead']);
  });

  it('removing a title edits the union rather than deleting a criterion', async () => {
    mockGet(workspace());
    let posted: Record<string, unknown> | null = null;
    mockApiFetch.mockImplementation((url: string, init?: RequestInit) => {
      if (url.startsWith('/api/prospect-icp/versions')) {
        return Promise.resolve({ ok: true, json: async () => workspace() });
      }
      posted = JSON.parse(String(init?.body));
      return Promise.resolve({ ok: true, json: async () => ({ version: 3 }) });
    });

    renderWorkspace();
    await screen.findByTestId('title-union-editor');
    fireEvent.click(screen.getByLabelText('Remove Marketing Manager'));
    fireEvent.click(screen.getByTestId('save-edits'));

    await waitFor(() => expect(posted).not.toBeNull());
    const criteria = (posted as { criteria: Array<Record<string, unknown>> }).criteria;
    expect(criteria.filter((c) => c.attribute === 'job_title')).toHaveLength(1);
    expect(criteria).toHaveLength(3);                            // nothing removed
  });
});

describe('A2 — confidence is not a fit score', () => {
  it('labels target confidence as proposal confidence and never as ICP fit', async () => {
    mockGet(workspace());
    renderWorkspace();
    expect(await screen.findByTestId('target-confidence-1')).toHaveTextContent('AI proposal confidence: high');
    expect(screen.queryByText(/ICP fit/i)).not.toBeInTheDocument();
  });
});

describe('A2 — observed versus inferred', () => {
  it('marks a directly-evidenced target and an inferred target differently', async () => {
    mockGet(workspace());
    renderWorkspace();
    await screen.findByTestId('ranked-targets');
    expect(screen.getByTestId('derivation-directly_evidenced')).toHaveTextContent('Directly evidenced');
    expect(screen.getByTestId('derivation-inferred')).toHaveTextContent('Inferred by AI');
  });

  it('renders an inferred target with no quotes without failing or fabricating one', async () => {
    mockGet(workspace());
    renderWorkspace();
    await screen.findByTestId('ranked-targets');
    expect(screen.getByTestId('target-noquote-2')).toHaveTextContent('No verbatim quote');
    expect(screen.getByTestId('target-2')).toHaveTextContent('target_customer_segment');
  });

  it('renders evidence quotes when they exist', async () => {
    mockGet(workspace());
    renderWorkspace();
    await screen.findByTestId('ranked-targets');
    expect(screen.getByTestId('target-1')).toHaveTextContent('Marketing managers');
  });
});

describe('A2 — guidance, assumptions and rejections', () => {
  it('shows GAP-1/GAP-2 guidance as reasoning that is NOT a formal criterion', async () => {
    mockGet(workspace());
    renderWorkspace();
    const guidance = await screen.findByTestId('proposal-guidance');
    expect(guidance).toHaveTextContent('problem_relevance');
    expect(guidance).toHaveTextContent('does not score');
    // It must not appear among the criteria.
    expect(screen.getByTestId('person-icp')).not.toHaveTextContent('problem_relevance');
  });

  it('labels the stage assumption as an assumption', async () => {
    mockGet(workspace());
    renderWorkspace();
    const stage = await screen.findByTestId('stage-assumption');
    expect(stage).toHaveTextContent('not an observed fact');
    expect(stage).toHaveTextContent('smb');
  });

  it('shows rejected candidates with their reasons', async () => {
    mockGet(workspace());
    renderWorkspace();
    expect(await screen.findByTestId('rejected-targets')).toHaveTextContent('CMO');
    expect(screen.getByTestId('rejected-targets')).toHaveTextContent('authority ceiling');
  });
});

describe('A2 — unsupported attributes (GAP-3)', () => {
  it.each(['seniority', 'authority', 'influence', 'buying_role'])(
    'offers no editing control for %s', async (attribute) => {
      mockGet(workspace());
      renderWorkspace();
      await screen.findByTestId('person-icp');
      expect(screen.queryByLabelText(new RegExp(attribute, 'i'))).not.toBeInTheDocument();
      // Stated as a limitation rather than silently omitted.
      expect(screen.getByTestId('unsupported-attributes')).toHaveTextContent(attribute);
    });
});

describe('A2 — editing creates a new version', () => {
  it('reports the new version and says the reviewed one is unchanged', async () => {
    mockGet(workspace());
    mockApiFetch.mockImplementation((url: string) => (
      url.startsWith('/api/prospect-icp/versions')
        ? Promise.resolve({ ok: true, json: async () => workspace() })
        : Promise.resolve({ ok: true, json: async () => ({ version: 3 }) })));

    renderWorkspace();
    await screen.findByTestId('title-union-editor');
    fireEvent.click(screen.getByLabelText('Remove Marketing Manager'));
    fireEvent.click(screen.getByTestId('save-edits'));

    await waitFor(() => expect(screen.getByTestId('icp-notice')).toHaveTextContent('Saved as version 3'));
    expect(screen.getByTestId('icp-notice')).toHaveTextContent('Version 2 is unchanged');
    expect(screen.getByTestId('icp-notice')).toHaveTextContent('Nothing is ratified yet');
  });

  it('surfaces a rejected edit and does not claim success', async () => {
    mockGet(workspace());
    mockApiFetch.mockImplementation((url: string) => (
      url.startsWith('/api/prospect-icp/versions')
        ? Promise.resolve({ ok: true, json: async () => workspace() })
        : Promise.resolve({ ok: false, status: 400, json: async () => ({ code: 'value_outside_vocabulary', error: 'bad criterion' }) })));

    renderWorkspace();
    await screen.findByTestId('title-union-editor');
    fireEvent.click(screen.getByLabelText('Remove Marketing Manager'));
    fireEvent.click(screen.getByTestId('save-edits'));

    await waitFor(() => expect(screen.getByTestId('icp-notice')).toHaveTextContent('Edit rejected'));
    expect(screen.getByTestId('icp-notice')).toHaveTextContent('value_outside_vocabulary');
  });

  it('never ratifies as a side effect of saving', async () => {
    mockGet(workspace());
    const urls: string[] = [];
    mockApiFetch.mockImplementation((url: string) => {
      urls.push(url);
      return url.startsWith('/api/prospect-icp/versions')
        ? Promise.resolve({ ok: true, json: async () => workspace() })
        : Promise.resolve({ ok: true, json: async () => ({ version: 3 }) });
    });

    renderWorkspace();
    await screen.findByTestId('title-union-editor');
    fireEvent.click(screen.getByLabelText('Remove Marketing Manager'));
    fireEvent.click(screen.getByTestId('save-edits'));

    await waitFor(() => expect(screen.getByTestId('icp-notice')).toBeInTheDocument());
    expect(urls.some((u) => u.includes('/ratify'))).toBe(false);
  });
});

describe('A2 — ratification is an explicit human act', () => {
  it('requires a confirmation step before calling the ratify route', async () => {
    mockGet(workspace());
    const urls: string[] = [];
    mockApiFetch.mockImplementation((url: string) => {
      urls.push(url);
      return url.startsWith('/api/prospect-icp/versions')
        ? Promise.resolve({ ok: true, json: async () => workspace() })
        : Promise.resolve({ ok: true, json: async () => ({ version: 2 }) });
    });

    renderWorkspace();
    fireEvent.click(await screen.findByTestId('ratify-button'));

    // First click only reveals the confirmation. Nothing has been ratified.
    expect(screen.getByTestId('ratify-confirm')).toHaveTextContent('immutable');
    expect(urls.some((u) => u.includes('/ratify'))).toBe(false);

    fireEvent.click(screen.getByTestId('ratify-confirm-yes'));
    await waitFor(() => expect(urls.some((u) => u.includes('/ratify'))).toBe(true));
    // The notice is set after the response resolves, so wait for it rather than
    // for the request alone.
    await waitFor(() => expect(screen.getByTestId('icp-notice')).toHaveTextContent('is now the ratified ICP'));
  });

  it('does not show success when ratification fails', async () => {
    mockGet(workspace());
    mockApiFetch.mockImplementation((url: string) => (
      url.startsWith('/api/prospect-icp/versions')
        ? Promise.resolve({ ok: true, json: async () => workspace() })
        : Promise.resolve({ ok: false, status: 409, json: async () => ({ code: 'already_ratified', error: 'version 2 is already ratified' }) })));

    renderWorkspace();
    fireEvent.click(await screen.findByTestId('ratify-button'));
    fireEvent.click(screen.getByTestId('ratify-confirm-yes'));

    await waitFor(() => expect(screen.getByTestId('icp-notice')).toHaveTextContent('Ratification failed'));
    expect(screen.getByTestId('icp-notice')).not.toHaveTextContent('is now the ratified ICP');
  });

  it('never ratifies on page load', async () => {
    mockGet(workspace());
    renderWorkspace();
    await screen.findByTestId('proposal-version-2');
    expect(mockApiFetch.mock.calls.every(([u]: [string]) => !u.includes('/ratify'))).toBe(true);
  });

  it('blocks ratification while edits are unsaved', async () => {
    mockGet(workspace());
    renderWorkspace();
    await screen.findByTestId('title-union-editor');
    fireEvent.click(screen.getByLabelText('Remove Marketing Manager'));
    expect(screen.getByTestId('ratify-button')).toBeDisabled();
    expect(screen.getByTestId('edit-pending')).toHaveTextContent('never altered');
  });
});

describe('A2 — version handling makes no assumption about "current"', () => {
  it('requires the reviewer to choose when several proposals await a decision', async () => {
    const two = workspace({
      proposals: [proposalVersion({ version: 3, id: 'v-3' }), proposalVersion({ version: 2 })],
      proposalChoiceRequired: true,
    });
    mockGet(two);
    renderWorkspace();

    const choice = await screen.findByTestId('proposal-choice-required');
    expect(choice).toHaveTextContent('no automatic');
    // Nothing is pre-selected — the newest is NOT assumed current.
    expect(screen.queryByTestId('proposal-version-3')).not.toBeInTheDocument();
    expect(screen.queryByTestId('proposal-version-2')).not.toBeInTheDocument();

    fireEvent.click(screen.getByText('Review version 3 (2026-09-05T00:00:00.000Z)'));
    expect(screen.getByTestId('proposal-version-3')).toBeInTheDocument();
  });

  it('keeps the ratified version distinguishable from a newer proposal', async () => {
    mockGet(workspace({
      ratified: proposalVersion({ version: 1, status: 'ratified', ratifiedAt: '2026-09-01T00:00:00.000Z' }),
      proposals: [proposalVersion({ version: 2 })],
    }));
    renderWorkspace();

    expect(await screen.findByTestId('ratified-banner')).toHaveTextContent('version 1');
    expect(screen.getByTestId('ratified-banner')).toHaveTextContent('authoritative');
    expect(screen.getByTestId('newer-proposal-banner')).toHaveTextContent('remains authoritative until');
  });

  it('states plainly when nothing is ratified', async () => {
    mockGet(workspace());
    renderWorkspace();
    expect(await screen.findByTestId('no-ratified-banner')).toHaveTextContent('Nothing is being used for scoring');
  });
});

describe('A2 — generation surfaces the 422 refusal contract', () => {
  it('shows the refusal code and reason without claiming a proposal exists', async () => {
    mockGet(workspace({ proposals: [], history: [] }));
    mockApiFetch.mockImplementation((url: string) => (
      url.startsWith('/api/prospect-icp/versions')
        ? Promise.resolve({ ok: true, json: async () => workspace({ proposals: [], history: [] }) })
        : Promise.resolve({
          ok: false, status: 422,
          json: async () => ({ code: 'INSUFFICIENT_EVIDENCE', error: 'too few buyer signals to propose' }),
        })));

    renderWorkspace();
    fireEvent.click(await screen.findByTestId('generate-button'));
    await waitFor(() => expect(screen.getByTestId('icp-notice')).toHaveTextContent('INSUFFICIENT_EVIDENCE'));
    expect(screen.getByTestId('icp-notice')).toHaveTextContent('too few buyer signals');
  });
});

describe('A2 — tenant scoping', () => {
  it('sends the selected company on every request and never another tenant', async () => {
    mockCompanyId = 'company-A';
    mockGet(workspace());
    renderWorkspace();
    await screen.findByTestId('proposal-version-2');
    for (const [url] of mockApiFetch.mock.calls) {
      expect(url).toContain('company_id=company-A');
      expect(url).not.toContain('company-B');
    }
  });
});
