import { supabase } from './supabaseClient';
import { DecisionResult } from '../services/omnivyreClient';
import type { WeeklyBlueprintWeek } from '../services/campaignPlanParser';
import { fromStructuredPlan } from '../services/campaignBlueprintAdapter';
import type { CampaignBlueprint, CampaignBlueprintWeek } from '../types/CampaignBlueprint';

function totalPostsForWeek(week: { platform_allocation?: Record<string, number> }): number {
  const pa = week.platform_allocation ?? {};
  return Math.max(0, Object.values(pa).reduce((a, b) => a + (typeof b === 'number' ? b : 0), 0)) || 0;
}

async function upsertCampaignResourceProjection(campaignId: string, blueprint: CampaignBlueprint): Promise<void> {
  const rows = blueprint.weeks.map((w: CampaignBlueprintWeek) => ({
    campaign_id: campaignId,
    week_number: w.week_number,
    total_posts: totalPostsForWeek(w) || 1,
    platform_allocation: w.platform_allocation ?? {},
  }));
  if (rows.length === 0) return;
  const { error } = await supabase.from('campaign_resource_projection').upsert(rows, {
    onConflict: 'campaign_id,week_number',
  });
  if (error) {
    console.warn('campaign_resource_projection upsert failed:', error.message);
  }
}

export async function saveAiCampaignPlan(input: {
  campaignId: string;
  snapshot_hash: string;
  mode: string;
  response: string;
  omnivyre_decision: DecisionResult;
}): Promise<void> {
  const { error } = await supabase
    .from('12_week_plan')
    .insert({
      campaign_id: input.campaignId,
      snapshot_hash: input.snapshot_hash,
      mode: input.mode,
      response: input.response,
      omnivyre_decision: input.omnivyre_decision,
      source: 'ai',
      created_at: new Date().toISOString(),
    });

  if (error) {
    throw new Error(`Failed to save AI campaign plan: ${error.message}`);
  }
}

/** Supports both new blueprint format and legacy daily[] format for backward compatibility */
export async function saveStructuredCampaignPlan(input: {
  campaignId: string;
  snapshot_hash: string;
  weeks: WeeklyBlueprintWeek[];
  omnivyre_decision: DecisionResult;
  raw_plan_text: string;
}): Promise<void> {
  const plan = { weeks: input.weeks, campaign_id: input.campaignId };
  const blueprint: CampaignBlueprint = fromStructuredPlan(plan);

  const { error } = await supabase
    .from('12_week_plan')
    .insert({
      campaign_id: input.campaignId,
      snapshot_hash: input.snapshot_hash,
      weeks: input.weeks,
      raw_plan_text: input.raw_plan_text,
      omnivyre_decision: input.omnivyre_decision,
      source: 'ai',
      blueprint: blueprint as any,
      created_at: new Date().toISOString(),
    });

  if (error) {
    throw new Error(`Failed to save structured campaign plan: ${error.message}`);
  }
  await upsertCampaignResourceProjection(input.campaignId, blueprint);
}

export async function saveStructuredCampaignPlanDayUpdate(input: {
  campaignId: string;
  snapshot_hash: string;
  dayPlan: {
    week: number;
    day: string;
    objective: string;
    content: string;
    platforms: Record<string, string>;
    hashtags?: string[];
    seo_keywords?: string[];
    meta_title?: string;
    meta_description?: string;
    hook?: string;
    cta?: string;
    best_time?: string;
    effort_score?: number;
    success_projection?: number;
  };
  omnivyre_decision: DecisionResult;
  raw_plan_text: string;
}): Promise<void> {
  const { error } = await supabase
    .from('12_week_plan')
    .update({
      refined_day: input.dayPlan,
      raw_plan_text: input.raw_plan_text,
      omnivyre_decision: input.omnivyre_decision,
      updated_at: new Date().toISOString(),
    })
    .eq('campaign_id', input.campaignId)
    .eq('snapshot_hash', input.snapshot_hash);

  if (error) {
    throw new Error(`Failed to update structured campaign plan day: ${error.message}`);
  }
}

/**
 * Save blueprint from Flow A (recommendations) to 12_week_plan.
 * Used when weekly_plan is generated by campaignRecommendationService.
 */
export async function saveCampaignBlueprintFromRecommendation(input: {
  campaignId: string;
  companyId: string;
  blueprint: CampaignBlueprint;
}): Promise<void> {
  const snapshot_hash = `recommendation-${input.companyId}-${Date.now()}`;
  const weeksForDb = input.blueprint.weeks.map((w) => ({
    week: w.week_number,
    phase_label: w.phase_label,
    primary_objective: w.primary_objective,
    platform_allocation: w.platform_allocation,
    content_type_mix: w.content_type_mix,
    cta_type: w.cta_type,
    weekly_kpi_focus: w.weekly_kpi_focus,
  }));
  const { error } = await supabase.from('12_week_plan').insert({
    campaign_id: input.campaignId,
    snapshot_hash,
    weeks: weeksForDb,
    raw_plan_text: '',
    omnivyre_decision: { status: 'ok', recommendation: 'proceed' } as DecisionResult,
    source: 'recommendation',
    blueprint: input.blueprint as any,
    created_at: new Date().toISOString(),
  });
  if (error) throw new Error(`Failed to save blueprint: ${error.message}`);
  await upsertCampaignResourceProjection(input.campaignId, input.blueprint);
}

/**
 * Save blueprint from create-12week-plan (Flow C redirect).
 * Source: 'create-12week-plan'.
 */
export async function saveCampaignBlueprintFromLegacy(input: {
  campaignId: string;
  blueprint: CampaignBlueprint;
  source?: string;
}): Promise<void> {
  const snapshot_hash = `legacy-${input.campaignId}-${Date.now()}`;
  const weeksForDb = input.blueprint.weeks.map((w) => ({
    week: w.week_number,
    phase_label: w.phase_label,
    primary_objective: w.primary_objective,
    platform_allocation: w.platform_allocation,
    content_type_mix: w.content_type_mix,
    cta_type: w.cta_type,
    weekly_kpi_focus: w.weekly_kpi_focus,
  }));
  const { error } = await supabase.from('12_week_plan').insert({
    campaign_id: input.campaignId,
    snapshot_hash,
    weeks: weeksForDb,
    raw_plan_text: '',
    omnivyre_decision: { status: 'ok', recommendation: 'proceed' } as DecisionResult,
    source: input.source ?? 'create-12week-plan',
    blueprint: input.blueprint as any,
    created_at: new Date().toISOString(),
  });
  if (error) throw new Error(`Failed to save blueprint from legacy: ${error.message}`);
  await upsertCampaignResourceProjection(input.campaignId, input.blueprint);
}

export async function savePlatformCustomizedContent(input: {
  campaignId: string;
  snapshot_hash: string;
  day: string;
  platforms: Record<string, string>;
  omnivyre_decision: DecisionResult;
  raw_plan_text: string;
}): Promise<void> {
  const { error } = await supabase
    .from('12_week_plan')
    .update({
      platform_content: {
        day: input.day,
        platforms: input.platforms,
      },
      raw_plan_text: input.raw_plan_text,
      omnivyre_decision: input.omnivyre_decision,
      updated_at: new Date().toISOString(),
    })
    .eq('campaign_id', input.campaignId)
    .eq('snapshot_hash', input.snapshot_hash);

  if (error) {
    throw new Error(`Failed to save platform customized content: ${error.message}`);
  }
}
