/** useCampaignPlanningController — state/handlers of CampaignPlanningContent, verbatim. */
import React, { useState, useEffect } from 'react';
import { useRouter } from 'next/router';

import { 
  ArrowLeft, 
  Calendar, 
  Target, 
  Plus, 
  Trash2, 
  Edit3, 
  Save, 
  CheckCircle,
  AlertCircle,
  Clock,
  Users,
  TrendingUp,
  FileText,
  Image,
  Video,
  Mic,
  Loader2,
  Sparkles
} from 'lucide-react';
import CampaignAIChat from '../components/CampaignAIChat';
import { fetchWithAuth } from '../components/community-ai/fetchWithAuth';
import AIContentIntegration from '../components/AIContentIntegration';
import ContentCreationPanel from '../components/ContentCreationPanel';
import VoiceNotesComponent from '../components/VoiceNotesComponent';
import WeeklyRefinementInterface from '../components/WeeklyRefinementInterface';

import type { useCampaignPlanningState } from '../hooks/useCampaignPlanningState';

type CampaignState = ReturnType<typeof useCampaignPlanningState>;
import CampaignPlanDetailsSection from './CampaignPlanDetailsSection';

export function useCampaignPlanningController({ d }: { d: CampaignState }) {
  const {
    accuracyPct,
    activePlanningTab,
    addGoal,
    aiImprovements,
    aiImprovementsError,
    aiProgram,
    aiSuggestionContext,
    alignedPreview,
    alignedPreviewError,
    approveFrequencyRebalance,
    campaignData,
    campaignId,
    captureAIProgram,
    checkExistingPlan,
    contentTypes,
    continueToMarketAnalysis,
    createNewCampaign,
    expandedSuggestionIds,
    fetchAiImprovements,
    fetchForecastVsActual,
    fetchLeadConversionIntel,
    fetchMomentumData,
    fetchOptimizationAdvice,
    fetchPlatformAdvice,
    fetchReapprovalStatus,
    fetchStrategyStatus,
    fetchViralTopicMemory,
    forecastDelta,
    forecastError,
    forecastVsActual,
    generate12WeekPlan,
    generatePlanDescription,
    getContentTypeColor,
    getContentTypeIcon,
    getPlatformColor,
    getPriorityColor,
    groupedContext,
    hasExistingPlan,
    isAiImprovementsLoading,
    isChatOpen,
    isDraftMode,
    isEditMode,
    isForecastLoading,
    isLeadIntelLoading,
    isLoading,
    isMomentumLoading,
    isOptimizationLoading,
    isPlatformAdviceLoading,
    isRebalanceLoading,
    isRevisingStrategy,
    isStrategyLocked,
    isStrategyProposed,
    isStrategyStatusLoading,
    isViralTopicLoading,
    leadConversionIntel,
    leadIntelError,
    loadCampaign,
    loadExistingCampaign,
    momentumData,
    momentumError,
    newGoal,
    notice,
    notify,
    openDailyPlanning,
    optimizationAdvice,
    optimizationError,
    organizeProgramIntoGoals,
    planDescription,
    platformAccuracyEntries,
    platformAdvice,
    platformAdviceEntries,
    platformAdviceError,
    platformSortMode,
    platforms,
    priorities,
    programStartDate,
    proposeFrequencyRebalance,
    reapprovalStatus,
    rebalanceError,
    rebalanceProposal,
    rebalanceRejectReason,
    rebalanceStatus,
    recommendationContext,
    recommendationHash,
    regenerateAlignedPreview,
    rejectFrequencyRebalance,
    removeGoal,
    reviseError,
    reviseStrategyFromSuggestions,
    router,
    saveCampaign,
    selectedSuggestionIds,
    setActivePlanningTab,
    setAiImprovements,
    setAiImprovementsError,
    setAiProgram,
    setAiSuggestionContext,
    setAlignedPreview,
    setAlignedPreviewError,
    setCampaignData,
    setCampaignId,
    setExpandedSuggestionIds,
    setForecastError,
    setForecastVsActual,
    setGroupedContext,
    setHasExistingPlan,
    setIsAiImprovementsLoading,
    setIsChatOpen,
    setIsForecastLoading,
    setIsLeadIntelLoading,
    setIsLoading,
    setIsMomentumLoading,
    setIsOptimizationLoading,
    setIsPlatformAdviceLoading,
    setIsRebalanceLoading,
    setIsRevisingStrategy,
    setIsStrategyStatusLoading,
    setIsViralTopicLoading,
    setLeadConversionIntel,
    setLeadIntelError,
    setMomentumData,
    setMomentumError,
    setNewGoal,
    setNotice,
    setOptimizationAdvice,
    setOptimizationError,
    setPlanDescription,
    setPlatformAdvice,
    setPlatformAdviceError,
    setPlatformSortMode,
    setProgramStartDate,
    setReapprovalStatus,
    setRebalanceError,
    setRebalanceProposal,
    setRebalanceRejectReason,
    setRebalanceStatus,
    setRecommendationContext,
    setRecommendationHash,
    setReviseError,
    setSelectedSuggestionIds,
    setShowProgramCapture,
    setShowRebalanceRationale,
    setShowRebalanceRejectModal,
    setShowWeeklyRefinement,
    setStableThemesOpen,
    setStrategyStatus,
    setViralTopicError,
    setViralTopicMemory,
    showProgramCapture,
    showRebalanceRationale,
    showRebalanceRejectModal,
    showWeeklyRefinement,
    stableThemesOpen,
    strategyStatus,
    toggleSuggestionDetails,
    toggleSuggestionSelection,
    viralTopicError,
    viralTopicMemory,
  } = d;

  return {
    d,
    accuracyPct, activePlanningTab, addGoal, aiImprovements, aiImprovementsError, aiProgram, aiSuggestionContext, alignedPreview,
    alignedPreviewError, approveFrequencyRebalance, campaignData, campaignId, captureAIProgram, checkExistingPlan, contentTypes,
    continueToMarketAnalysis, createNewCampaign, expandedSuggestionIds, fetchAiImprovements, fetchForecastVsActual,
    fetchLeadConversionIntel, fetchMomentumData, fetchOptimizationAdvice, fetchPlatformAdvice, fetchReapprovalStatus,
    fetchStrategyStatus, fetchViralTopicMemory, forecastDelta, forecastError, forecastVsActual, generate12WeekPlan,
    generatePlanDescription, getContentTypeColor, getContentTypeIcon, getPlatformColor, getPriorityColor, groupedContext,
    hasExistingPlan, isAiImprovementsLoading, isChatOpen, isDraftMode, isEditMode, isForecastLoading, isLeadIntelLoading, isLoading,
    isMomentumLoading, isOptimizationLoading, isPlatformAdviceLoading, isRebalanceLoading, isRevisingStrategy, isStrategyLocked,
    isStrategyProposed, isStrategyStatusLoading, isViralTopicLoading, leadConversionIntel, leadIntelError, loadCampaign,
    loadExistingCampaign, momentumData, momentumError, newGoal, notice, notify, openDailyPlanning, optimizationAdvice,
    optimizationError, organizeProgramIntoGoals, planDescription, platformAccuracyEntries, platformAdvice, platformAdviceEntries,
    platformAdviceError, platformSortMode, platforms, priorities, programStartDate, proposeFrequencyRebalance, reapprovalStatus,
    rebalanceError, rebalanceProposal, rebalanceRejectReason, rebalanceStatus, recommendationContext, recommendationHash,
    regenerateAlignedPreview, rejectFrequencyRebalance, removeGoal, reviseError, reviseStrategyFromSuggestions, router, saveCampaign,
    selectedSuggestionIds, setActivePlanningTab, setAiImprovements, setAiImprovementsError, setAiProgram, setAiSuggestionContext,
    setAlignedPreview, setAlignedPreviewError, setCampaignData, setCampaignId, setExpandedSuggestionIds, setForecastError,
    setForecastVsActual, setGroupedContext, setHasExistingPlan, setIsAiImprovementsLoading, setIsChatOpen, setIsForecastLoading,
    setIsLeadIntelLoading, setIsLoading, setIsMomentumLoading, setIsOptimizationLoading, setIsPlatformAdviceLoading,
    setIsRebalanceLoading, setIsRevisingStrategy, setIsStrategyStatusLoading, setIsViralTopicLoading, setLeadConversionIntel,
    setLeadIntelError, setMomentumData, setMomentumError, setNewGoal, setNotice, setOptimizationAdvice, setOptimizationError,
    setPlanDescription, setPlatformAdvice, setPlatformAdviceError, setPlatformSortMode, setProgramStartDate, setReapprovalStatus,
    setRebalanceError, setRebalanceProposal, setRebalanceRejectReason, setRebalanceStatus, setRecommendationContext,
    setRecommendationHash, setReviseError, setSelectedSuggestionIds, setShowProgramCapture, setShowRebalanceRationale,
    setShowRebalanceRejectModal, setShowWeeklyRefinement, setStableThemesOpen, setStrategyStatus, setViralTopicError,
    setViralTopicMemory, showProgramCapture, showRebalanceRationale, showRebalanceRejectModal, showWeeklyRefinement,
    stableThemesOpen, strategyStatus, toggleSuggestionDetails, toggleSuggestionSelection, viralTopicError, viralTopicMemory
  };
}
