import React from 'react';
import { type AIChatProps } from './campaign-ai/types';
import { useCampaignAIExternalData } from './campaign-ai/useCampaignAIExternalData';
import { useCampaignAIChatState } from './campaign-ai/useCampaignAIChatState';
import { useCampaignAIController } from './campaign-ai/useCampaignAIController';
import { useCampaignAIControllerArgs } from './campaign-ai/useCampaignAIControllerArgs';
import { CampaignAIChatShell } from './campaign-ai/CampaignAIChatShell';
import { useCampaignAIViewProps } from './campaign-ai/useCampaignAIViewProps';

export default function AIChat({ isOpen, onClose, onMinimize, context = "general", companyId, campaignId, campaignData, recommendationContext, onProgramGenerated, governanceLocked, optimizationContext, prefilledPlanning, initialPlan, standalone = false, vetScope, collectedPlanningContext, forceFreshPlanningThread = false, onBackToRecommendation }: AIChatProps) {
  const {
    messages, setMessages, newMessage, setNewMessage, inputClearKey, setInputClearKey, isTyping, setIsTyping,
    showSettings, setShowSettings, showLearning, setShowLearning, isFullscreen, setIsFullscreen, selectedProvider, setSelectedProvider,
    isLoading, setIsLoading, modeLoading, setModeLoading, uiErrorMessage, setUiErrorMessage, campaignLearnings, setCampaignLearnings,
    showDateSelection, setShowDateSelection, commitStartDate, setCommitStartDate, commitDurationWeeks, setCommitDurationWeeks,
    selectedPlan, setSelectedPlan, showPlanPreview, setShowPlanPreview, structuredPlan, setStructuredPlan,
    structuredPlanMessageId, setStructuredPlanMessageId, hasGeneratedPlanInSession, setHasGeneratedPlanInSession,
    reviewWeekNumber, setReviewWeekNumber, replaceMode, setReplaceMode, replaceSelection, setReplaceSelection,
    showScheduleConfirm, setShowScheduleConfirm, isSchedulingPlan, setIsSchedulingPlan, uiSuccessMessage, setUiSuccessMessage,
    activeTab, setActiveTab, isAdmin, setIsAdmin, hasViewedPlanMessageId, setHasViewedPlanMessageId, showPlanOverview, setShowPlanOverview,
    pendingAmendment, setPendingAmendment, isSavingDraftForView, setIsSavingDraftForView, retrievePlanData, setRetrievePlanData,
    planSource, setPlanSource, isRetrievePlanLoading, setIsRetrievePlanLoading, isParsingSavedPlan, setIsParsingSavedPlan,
    selectedQuickOptions, setSelectedQuickOptions, quickPickPrimaryStyles, setQuickPickPrimaryStyles,
    quickPickSecondaryModifiers, setQuickPickSecondaryModifiers, quickCustomizeMode, setQuickCustomizeMode,
    quickCustomizeText, setQuickCustomizeText, quickCustomContentType, setQuickCustomContentType,
    quickCustomContentCount, setQuickCustomContentCount, quickCustomPlatform, setQuickCustomPlatform, hideQuickPickPanel, setHideQuickPickPanel,
    quickPickBackIndex, setQuickPickBackIndex, quickPickReplaceTruncateToRef, isNavigatingBackRef, quickDateYear, setQuickDateYear,
    quickDateMonth, setQuickDateMonth, quickDateDay, setQuickDateDay, quickCapacityCounts, setQuickCapacityCounts,
    planningAvailableCountsOverride, setPlanningAvailableCountsOverride, planningCapacityCountsOverride, setPlanningCapacityCountsOverride,
    quickCapacityCreationMode, setQuickCapacityCreationMode, showAllTypeCounters, setShowAllTypeCounters,
    planningSelectedPlatforms, setPlanningSelectedPlatforms, quickPlatformContentTypes, setQuickPlatformContentTypes,
    planningPlatformContentTypePrefs, setPlanningPlatformContentTypePrefs, planningPlatformContentRequests, setPlanningPlatformContentRequests,
    hasProvidedPlatformContentRequests, setHasProvidedPlatformContentRequests, planningCrossPlatformSharingEnabled, setPlanningCrossPlatformSharingEnabled,
    planningCrossPlatformScheduleMode, setPlanningCrossPlatformScheduleMode, showAllPlatformRequestTypes, setShowAllPlatformRequestTypes,
    planningAvailableTypeHints, setPlanningAvailableTypeHints, planningCapacityTypeHints, setPlanningCapacityTypeHints,
    planningExclusiveCampaigns, setPlanningExclusiveCampaigns, hasProvidedExclusiveCampaigns, setHasProvidedExclusiveCampaigns,
    lastCollectedPlanningContextFromApi, setLastCollectedPlanningContextFromApi, messagesEndRef, inputRef, freshThreadAppliedRef,
    planAbortRef, autoTriggerPlanRef, sendMessageRef, isBusy,
  } = useCampaignAIChatState();

  const {
    resolvedCompanyId,
    planningCatalog: {
      companyKeyMessages, companyProblemTransformation, planDurationLimit, platformCatalogPlatforms, companyConfiguredPlatforms,
      platformLabels, platformQuickPickOptions, configuredPlatformKeys, platformContentTypeOptions, platformContentTypeRawOptions,
      allCatalogContentTypeQuickPickOptions, creatorDependentQuickPickOptions, platformExtractCandidates, hasEffectiveCatalog,
    },
    ops: {
      aiHistory, isHistoryLoading, auditReport, isAuditLoading, healthReport, isHealthLoading, optimizeWeekNumber, setOptimizeWeekNumber,
      optimizeReason, setOptimizeReason, isOptimizingWeek, optimizeResult, executionPlan, isExecutionLoading, executionWeekNumber,
      setExecutionWeekNumber, schedulerPayload, contentAssets, isContentLoading, contentWeekNumber, setContentWeekNumber,
      regenerateInstruction, setRegenerateInstruction, setHealthReport, handleOptimizeWeek, loadExecutionPlan, handleApproveScheduling,
      loadContentAssets, handleGenerateContent, handleRegenerateContent, handleApproveContent, handleRejectContent,
    },
    insightOps: {
      analyticsReport, learningInsights, isPerformanceLoading, performanceWeekNumber, setPerformanceWeekNumber, campaignMemory,
      memoryOverlap, forecastReport, roiReport, businessReport, isBusinessLoading, platformIntelAssetId, setPlatformIntelAssetId,
      platformIntelPlatform, setPlatformIntelPlatform, platformIntelContentType, setPlatformIntelContentType, platformIntelData,
      isPlatformIntelLoading, handlePlatformIntel, handleTrackingLinkClick, handleApplyInsightsToWeek,
    },
    handleProviderChange, hasAnsweredPlanningKeyValue, getFirstUnansweredGatherKeyValue,
  } = useCampaignAIExternalData({
    props: { isOpen, onClose, onMinimize, context, companyId, campaignId, campaignData, recommendationContext, onProgramGenerated, governanceLocked, optimizationContext, prefilledPlanning, initialPlan, standalone, vetScope, collectedPlanningContext, forceFreshPlanningThread, onBackToRecommendation },
    selectedProvider,
    setSelectedProvider,
    messages,
    setMessages,
    setUiErrorMessage,
    setCampaignLearnings,
    setHasGeneratedPlanInSession,
    setReviewWeekNumber,
    setReplaceMode,
    setReplaceSelection,
    setLastCollectedPlanningContextFromApi,
    setRetrievePlanData,
    setIsRetrievePlanLoading,
    setIsAdmin,
    state: {
      structuredPlan,
      retrievePlanData,
      planningAvailableCountsOverride,
      planningCapacityCountsOverride,
      planningPlatformContentTypePrefs,
      planningSelectedPlatforms,
      quickPlatformContentTypes,
      hasProvidedPlatformContentRequests,
      planningPlatformContentRequests,
      planningCrossPlatformSharingEnabled,
      planningCrossPlatformScheduleMode,
      hasProvidedExclusiveCampaigns,
      planningExclusiveCampaigns,
      lastCollectedPlanningContextFromApi,
      freshThreadAppliedRef,
      autoTriggerPlanRef,
      activeTab,
      showPlanOverview,
    } as any,
    setters: {
      setPlanningSelectedPlatforms,
      setPlanningPlatformContentRequests,
      setPlanningCrossPlatformSharingEnabled,
      setPlanningCrossPlatformScheduleMode,
    },
  });

  const {
    quickPickState: {
      aiMessageIndices,
      displayedMessages,
      visibleMessages,
      quickPickAttachToMessageId,
      eligiblePlanningTypes,
      quickPickConfig,
    },
    persistence: {
      serializeStructuredPlanToText,
      saveAIContentForPlan,
      saveDraftAndViewOnCampaign,
      commitPlan,
      viewPlan,
      loadDraftPlanAndEdit,
      loadCommittedPlanAndEdit,
      loadSavedPlanAndEdit,
    },
    scheduleStructuredPlan,
    sendMessage,
    quickPick: {
      canGoBack,
      submitQuickPickAnswer,
      handleQuickPickBack,
      handleQuickPickBackDeeper,
    },
    applyPlanOverviewReplacement,
    handleKeyPress,
    hasPreviousQuestion,
    isWeeklyPlanMessage,
    isRecsChat,
    displayTopic,
  } = useCampaignAIController(useCampaignAIControllerArgs({
    props: {
      isOpen,
      onClose,
      onMinimize,
      context,
      companyId,
      campaignId,
      campaignData,
      recommendationContext,
      onProgramGenerated,
      governanceLocked,
      optimizationContext,
      prefilledPlanning,
      initialPlan,
      standalone,
      vetScope,
      collectedPlanningContext,
      forceFreshPlanningThread,
      onBackToRecommendation,
    },
    state: {
      messages,
      setMessages,
      newMessage,
      setNewMessage,
      inputClearKey,
      setInputClearKey,
      setIsTyping,
      isLoading,
      setIsLoading,
      setUiErrorMessage,
      selectedProvider,
      modeLoading,
      setModeLoading,
      structuredPlan,
      setStructuredPlan,
      structuredPlanMessageId,
      setStructuredPlanMessageId,
      setHasGeneratedPlanInSession,
      reviewWeekNumber,
      setReviewWeekNumber,
      replaceMode,
      setReplaceMode,
      replaceSelection,
      setReplaceSelection,
      setShowScheduleConfirm,
      setIsSchedulingPlan,
      setUiSuccessMessage,
      hasViewedPlanMessageId,
      setHasViewedPlanMessageId,
      showPlanOverview,
      setShowPlanOverview,
      isSavingDraftForView,
      setIsSavingDraftForView,
      retrievePlanData,
      setRetrievePlanData,
      planSource,
      setPlanSource,
      setShowDateSelection,
      selectedPlan,
      setSelectedPlan,
      commitStartDate,
      setCommitStartDate,
      commitDurationWeeks,
      setCommitDurationWeeks,
      selectedQuickOptions,
      setSelectedQuickOptions,
      quickPickPrimaryStyles,
      setQuickPickPrimaryStyles,
      quickPickSecondaryModifiers,
      setQuickPickSecondaryModifiers,
      quickCustomizeMode,
      setQuickCustomizeMode,
      quickCustomizeText,
      setQuickCustomizeText,
      quickCustomContentType,
      setQuickCustomContentType,
      quickCustomContentCount,
      setQuickCustomContentCount,
      quickCustomPlatform,
      setQuickCustomPlatform,
      hideQuickPickPanel,
      setHideQuickPickPanel,
      quickPickBackIndex,
      setQuickPickBackIndex,
      quickPickReplaceTruncateToRef,
      isNavigatingBackRef,
      quickDateYear,
      setQuickDateYear,
      quickDateMonth,
      setQuickDateMonth,
      quickDateDay,
      setQuickDateDay,
      quickCapacityCounts,
      setQuickCapacityCounts,
      planningAvailableCountsOverride,
      setPlanningAvailableCountsOverride,
      planningCapacityCountsOverride,
      setPlanningCapacityCountsOverride,
      quickCapacityCreationMode,
      setQuickCapacityCreationMode,
      showAllTypeCounters,
      setShowAllTypeCounters,
      planningSelectedPlatforms,
      setPlanningSelectedPlatforms,
      quickPlatformContentTypes,
      setQuickPlatformContentTypes,
      planningPlatformContentTypePrefs,
      setPlanningPlatformContentTypePrefs,
      planningPlatformContentRequests,
      setPlanningPlatformContentRequests,
      hasProvidedPlatformContentRequests,
      setHasProvidedPlatformContentRequests,
      planningCrossPlatformSharingEnabled,
      setPlanningCrossPlatformSharingEnabled,
      planningCrossPlatformScheduleMode,
      setPlanningCrossPlatformScheduleMode,
      showAllPlatformRequestTypes,
      setShowAllPlatformRequestTypes,
      planningAvailableTypeHints,
      setPlanningAvailableTypeHints,
      planningCapacityTypeHints,
      setPlanningCapacityTypeHints,
      planningExclusiveCampaigns,
      setPlanningExclusiveCampaigns,
      hasProvidedExclusiveCampaigns,
      setHasProvidedExclusiveCampaigns,
      lastCollectedPlanningContextFromApi,
      setLastCollectedPlanningContextFromApi,
      inputRef,
      messagesEndRef,
      planAbortRef,
      autoTriggerPlanRef,
      sendMessageRef,
      isBusy,
      pendingAmendment,
      setPendingAmendment,
      showPlanPreview,
      setShowPlanPreview,
      setIsParsingSavedPlan,
      campaignLearnings,
    },
    planningCatalog: {
      planDurationLimit,
      platformLabels,
      platformQuickPickOptions,
      configuredPlatformKeys,
      platformContentTypeOptions,
      allCatalogContentTypeQuickPickOptions,
      creatorDependentQuickPickOptions,
      platformExtractCandidates,
    },
    external: {
      resolvedCompanyId,
      hasAnsweredPlanningKeyValue,
    },
  }));

  const shellProps = useCampaignAIViewProps({
    props: {
      isOpen,
      standalone,
      onMinimize,
      onClose,
      campaignId,
      campaignData,
      governanceLocked,
      context,
      prefilledPlanning,
      initialPlan,
      collectedPlanningContext,
      onBackToRecommendation,
    },
    state: {
      campaignLearnings,
      selectedProvider,
      uiErrorMessage,
      uiSuccessMessage,
      activeTab,
      retrievePlanData,
      isRetrievePlanLoading,
      isParsingSavedPlan,
      showLearning,
      setShowLearning,
      showSettings,
      setShowSettings,
      isFullscreen,
      setIsFullscreen,
      messages,
      isTyping,
      modeLoading,
      planAbortRef,
      isSchedulingPlan,
      isLoading,
      messagesEndRef,
      structuredPlan,
      structuredPlanMessageId,
      isBusy,
      selectedQuickOptions,
      setSelectedQuickOptions,
      quickCustomizeMode,
      setQuickCustomizeMode,
      quickCustomizeText,
      setQuickCustomizeText,
      quickCustomContentType,
      setQuickCustomContentType,
      quickCustomContentCount,
      setQuickCustomContentCount,
      quickCustomPlatform,
      setQuickCustomPlatform,
      quickDateYear,
      setQuickDateYear,
      quickDateMonth,
      setQuickDateMonth,
      quickDateDay,
      setQuickDateDay,
      quickCapacityCounts,
      setQuickCapacityCounts,
      quickCapacityCreationMode,
      setQuickCapacityCreationMode,
      showAllTypeCounters,
      setShowAllTypeCounters,
      planningSelectedPlatforms,
      hideQuickPickPanel,
      setHideQuickPickPanel,
      planningPlatformContentRequests,
      setPlanningPlatformContentRequests,
      planningCrossPlatformSharingEnabled,
      setPlanningCrossPlatformSharingEnabled,
      planningCrossPlatformScheduleMode,
      setPlanningCrossPlatformScheduleMode,
      planningExclusiveCampaigns,
      setPlanningExclusiveCampaigns,
      planningAvailableCountsOverride,
      planningCapacityCountsOverride,
      planningPlatformContentTypePrefs,
      showAllPlatformRequestTypes,
      setShowAllPlatformRequestTypes,
      quickPickPrimaryStyles,
      setQuickPickPrimaryStyles,
      quickPickSecondaryModifiers,
      setQuickPickSecondaryModifiers,
      lastCollectedPlanningContextFromApi,
      hasProvidedPlatformContentRequests,
      showScheduleConfirm,
      setShowScheduleConfirm,
      showPlanOverview,
      setShowPlanOverview,
      reviewWeekNumber,
      setReviewWeekNumber,
      replaceMode,
      setReplaceMode,
      replaceSelection,
      setReplaceSelection,
      newMessage,
      setNewMessage,
      inputClearKey,
      isSavingDraftForView,
      inputRef,
      showPlanPreview,
      setShowPlanPreview,
      selectedPlan,
      hasViewedPlanMessageId,
      hasGeneratedPlanInSession,
      quickPickBackIndex,
      setUiErrorMessage,
    },
    external: {
      resolvedCompanyId,
      handleProviderChange,
      platformLabels,
      platformContentTypeOptions,
      platformContentTypeRawOptions,
      hasEffectiveCatalog,
      aiHistory,
      isHistoryLoading,
      auditReport,
      isAuditLoading,
      healthReport,
      isHealthLoading,
      optimizeWeekNumber,
      setOptimizeWeekNumber,
      optimizeReason,
      setOptimizeReason,
      isOptimizingWeek,
      optimizeResult,
      executionPlan,
      isExecutionLoading,
      executionWeekNumber,
      setExecutionWeekNumber,
      schedulerPayload,
      contentAssets,
      isContentLoading,
      contentWeekNumber,
      setContentWeekNumber,
      regenerateInstruction,
      setRegenerateInstruction,
      handleOptimizeWeek,
      loadExecutionPlan,
      handleApproveScheduling,
      handleTrackingLinkClick,
      handleGenerateContent,
      handleRegenerateContent,
      handleApproveContent,
      handleRejectContent,
      analyticsReport,
      learningInsights,
      isPerformanceLoading,
      performanceWeekNumber,
      setPerformanceWeekNumber,
      campaignMemory,
      memoryOverlap,
      forecastReport,
      roiReport,
      businessReport,
      isBusinessLoading,
      platformIntelAssetId,
      setPlatformIntelAssetId,
      platformIntelPlatform,
      setPlatformIntelPlatform,
      platformIntelContentType,
      setPlatformIntelContentType,
      platformIntelData,
      isPlatformIntelLoading,
      handlePlatformIntel,
      handleApplyInsightsToWeek,
    },
    controller: {
      isRecsChat,
      displayTopic,
      visibleMessages,
      quickPickAttachToMessageId,
      quickPickConfig,
      eligiblePlanningTypes,
      aiMessageIndices,
      canGoBack,
      submitQuickPickAnswer,
      handleQuickPickBack,
      handleQuickPickBackDeeper,
      sendMessage,
      applyPlanOverviewReplacement,
      saveDraftAndViewOnCampaign,
      saveAIContentForPlan,
      serializeStructuredPlanToText,
      commitPlan,
      viewPlan,
      loadSavedPlanAndEdit,
      loadCommittedPlanAndEdit,
      scheduleStructuredPlan,
      isWeeklyPlanMessage,
      handleKeyPress,
      hasPreviousQuestion,
      quickPlatformContentTypes,
    },
  });

  return <CampaignAIChatShell {...shellProps} />;
}

