import React, { useEffect, useMemo, useState } from 'react';
import { useRouter } from 'next/router';
import { useCompanyContext } from '../components/CompanyContext';
import { fetchWithAuth } from '../components/community-ai/fetchWithAuth';
import VoiceNotesComponent from '../components/VoiceNotesComponent';
import {
  buildTrendSourceCounts,
  getConfidenceLabel,
  hasNoExternalSignals,
  shouldShowNoveltyWarning,
} from '../backend/services/recommendationUiExplainability';
import TrendCampaignsTab from '../components/recommendations/tabs/TrendCampaignsTab';
import NextStrategicDirection from '../components/campaigns/NextStrategicDirection';
import { useRecommendationViewMode } from '../components/recommendations/hooks/useRecommendationViewMode';
import ActiveLeadsTab from '../components/recommendations/tabs/ActiveLeadsTab';
import MarketPulseTab from '../components/recommendations/tabs/MarketPulseTab';
import RecommendationStatusWidget from '../components/recommendations/RecommendationStatusWidget';
import StrategySignalsWidget from '../components/dashboard/StrategySignalsWidget';
import {
  type TrendSignal,
  type RecommendationEngineResult,
  type DetectedOpportunity,
  type TrendSourceLegendItem,
  type ExternalApiOption,
  OPPORTUNITY_TAB_TYPES,
  TREND_SOURCE_LEGEND,
} from '../pages/recommendations.types';

type IntelligentMixState = import('@/pages/command-center/intelligent-mix-strategy').IntelligentMixState;

import type { useRecommendationsState } from '../hooks/useRecommendationsState';

type RecState = ReturnType<typeof useRecommendationsState>;

export default function RecommendationsContent({ d }: { d: RecState }) {
  const {
    acceptPreviewAndDraftPlan,
    activeOpportunityTab,
    activeWorkspaceTab,
    addGroup,
    autoGenerated,
    availableApis,
    campaignIdLocked,
    campaigns,
    canGenerateDetectedPlaybook,
    canGroupRecommendations,
    canManageRecommendationState,
    canSeeDetectedOpportunities,
    companies,
    confidenceMeta,
    confidencePercent,
    confidenceRatio,
    confirmGroupedCampaign,
    detectedError,
    detectedLoading,
    detectedOpportunities,
    detectedPlaybookLoading,
    detectedPlaybookOpen,
    detectedPlaybooks,
    detectedReasoningOpen,
    detectedTopicSources,
    dismissDetectedOpportunity,
    dismissedOpportunities,
    draftError,
    engineOverrides,
    engineResult,
    errorMessage,
    evaluateDetectedOpportunity,
    expandedTrendKey,
    fetchDetectedOpportunities,
    fetchStateMap,
    generateRecommendations,
    generatorModalTarget,
    getSelectedRecommendationPayload,
    groupAssignments,
    groupNames,
    groupPreview,
    groupPreviewError,
    groupPreviewLoading,
    groupPreviewOpen,
    groupSortMode,
    handleCreateCampaignFromRecommendation,
    handleManualSubmit,
    handleOpportunityAction,
    handleOpportunityPromote,
    handlePreparePlanFromRecommendation,
    hasPermission,
    intelligentMixContext,
    isAdmin,
    isApiLoading,
    isAuthenticated,
    isCampaignLoading,
    isCompanyLoading,
    isCreatingGroupedCampaign,
    isLoading,
    isSubmittingManual,
    lastRefresh,
    lastRefreshSource,
    manualNarrative,
    manualObjective,
    manualPlatformPreference,
    manualTopic,
    noExternalSignals,
    omnivyraStatus,
    omnivyraStatusColor,
    openGroupPreview,
    openPreviewForDetectedOpportunity,
    openPreviewForRecommendation,
    opportunityRegions,
    prefillBlogId,
    previewConfidence,
    previewConfidenceRating,
    previewContentFrequency,
    previewCurrentState,
    previewData,
    previewError,
    previewLoading,
    previewModalOpen,
    previewOpinionNote,
    previewPriorityBucket,
    previewRecommendationId,
    previewSnapshotHash,
    recommendationBySnapshot,
    recommendationDetails,
    recommendationStates,
    recommendationSummaries,
    recommendedThisWeek,
    refreshRecommendations,
    regeneratePreview,
    removeEmptyGroup,
    resolveRecommendationIdBySnapshot,
    router,
    savePreviewOpinion,
    selectedApiIds,
    selectedCampaignId,
    selectedCampaignName,
    selectedCompanyId,
    selectedRecommendations,
    setActiveOpportunityTab,
    setActiveWorkspaceTab,
    setAutoGenerated,
    setAvailableApis,
    setCampaignIdLocked,
    setCampaigns,
    setDetectedError,
    setDetectedLoading,
    setDetectedOpportunities,
    setDetectedPlaybookLoading,
    setDetectedPlaybookOpen,
    setDetectedPlaybooks,
    setDetectedReasoningOpen,
    setDismissedOpportunities,
    setDraftError,
    setEngineOverride,
    setEngineOverrides,
    setEngineResult,
    setErrorMessage,
    setExpandedTrendKey,
    setGeneratorModalTarget,
    setGroupAssignments,
    setGroupNames,
    setGroupPreview,
    setGroupPreviewError,
    setGroupPreviewLoading,
    setGroupPreviewOpen,
    setGroupSortMode,
    setIsApiLoading,
    setIsCampaignLoading,
    setIsCreatingGroupedCampaign,
    setIsLoading,
    setIsSubmittingManual,
    setLastRefresh,
    setLastRefreshSource,
    setManualNarrative,
    setManualObjective,
    setManualPlatformPreference,
    setManualTopic,
    setOpportunityRegions,
    setPrefillBlogId,
    setPreviewConfidence,
    setPreviewConfidenceRating,
    setPreviewContentFrequency,
    setPreviewCurrentState,
    setPreviewData,
    setPreviewError,
    setPreviewLoading,
    setPreviewModalOpen,
    setPreviewOpinionNote,
    setPreviewPriorityBucket,
    setPreviewRecommendationId,
    setPreviewSnapshotHash,
    setRecommendationBySnapshot,
    setRecommendationDetails,
    setRecommendationStates,
    setRecommendationSummaries,
    setSelectedApiIds,
    setSelectedCampaignId,
    setSelectedCampaignName,
    setSelectedCompanyId,
    setSelectedRecommendations,
    setSimulateScenarios,
    setSortByPriority,
    setStateError,
    setTrendStrategicIntents,
    showLoadingState,
    showNoCompanyState,
    showNoveltyWarning,
    simulateScenarios,
    sortByPriority,
    stateError,
    toggleApiSelection,
    toggleDetectedPlaybook,
    toggleDetectedReasoning,
    toggleRecommendationSelection,
    trendCounts,
    trendExplanationMap,
    trendSourceLegend,
    trendStrategicIntents,
    updateRecommendationState,
    user,
    userRole,
    viewMode,
  } = d;

  return (
    <>
      <div className="max-w-6xl mx-auto space-y-8">
        {/* Recommendation Hub: engine-based workspace. Strategy Signals on left. */}
        <section className="flex flex-col lg:flex-row gap-6">
          {selectedCompanyId && (
            <aside className="lg:w-56 shrink-0 order-first">
              <StrategySignalsWidget companyId={selectedCompanyId} fetchWithAuth={fetchWithAuth} />
              {selectedCampaignId && (
                <NextStrategicDirection
                  campaignId={selectedCampaignId}
                  campaignName={selectedCampaignName || undefined}
                  className="mt-4"
                />
              )}
            </aside>
          )}
          <div className="flex-1 min-w-0">
          <div className="flex flex-col sm:flex-row sm:items-start sm:justify-between gap-4 mb-3">
            <h2 className="text-xl font-semibold text-gray-900">Recommendation Hub</h2>
            {selectedCompanyId && (
              <RecommendationStatusWidget companyId={selectedCompanyId} fetchWithAuth={fetchWithAuth} />
            )}
          </div>
          <div className="flex flex-wrap gap-2 border-b border-gray-200 pb-3 mb-3">
            {OPPORTUNITY_TAB_TYPES.map(({ type, label }) => (
              <button
                key={type}
                type="button"
                onClick={() => setActiveOpportunityTab(type)}
                className={`px-3 py-2 rounded-lg text-sm font-medium ${
                  activeOpportunityTab === type
                    ? 'bg-indigo-600 text-white'
                    : 'bg-gray-100 text-gray-700 hover:bg-gray-200'
                }`}
              >
                {label}
              </button>
            ))}
          </div>
          <div className="mb-4 rounded-lg border border-indigo-200 bg-indigo-50 px-4 py-3 text-sm text-indigo-900">
            Market Pulse and Active Leads now live in the dashboard Intelligence hub.
            <button
              type="button"
              onClick={() => void router.push('/intelligence')}
              className="ml-2 font-semibold underline"
            >
              Open Intelligence
            </button>
          </div>
          <div className="min-h-[120px] pt-2">
            {activeOpportunityTab === 'TREND' && (
              <TrendCampaignsTab
                companyId={selectedCompanyId}
                regions={
                  opportunityRegions.trim()
                    ? opportunityRegions.split(',').map((r) => r.trim()).filter(Boolean)
                    : undefined
                }
                engineRecommendations={(engineResult?.trends_used as Array<Record<string, unknown>> | undefined) ?? []}
                onPromote={handleOpportunityPromote}
                onAction={handleOpportunityAction}
                fetchWithAuth={fetchWithAuth}
                overrideText={engineOverrides['TREND'] ?? ''}
                onOverrideChange={(v) => setEngineOverride('TREND', v)}
                strategicIntents={trendStrategicIntents}
                onStrategicIntentsChange={setTrendStrategicIntents}
                viewMode={viewMode}
                campaignId={selectedCampaignId || null}
                initialBlogId={prefillBlogId}
                intelligentMixContext={intelligentMixContext}
              />
            )}
            {activeOpportunityTab === 'LEAD' && (
              <ActiveLeadsTab
                companyId={selectedCompanyId}
                onPromote={handleOpportunityPromote}
                onAction={handleOpportunityAction}
                fetchWithAuth={fetchWithAuth}
                onSwitchTab={setActiveOpportunityTab}
                overrideText={engineOverrides['LEAD'] ?? ''}
                onOverrideChange={(v) => setEngineOverride('LEAD', v)}
              />
            )}
            {activeOpportunityTab === 'PULSE' && (
              <MarketPulseTab
                companyId={selectedCompanyId}
                regions={
                  opportunityRegions.trim()
                    ? opportunityRegions.split(',').map((r) => r.trim()).filter(Boolean)
                    : undefined
                }
                onPromote={handleOpportunityPromote}
                onAction={handleOpportunityAction}
                fetchWithAuth={fetchWithAuth}
                onSwitchTab={setActiveOpportunityTab}
                overrideText={engineOverrides['PULSE'] ?? ''}
                onOverrideChange={(v) => setEngineOverride('PULSE', v)}
              />
            )}
          </div>
          </div>
        </section>

        {generatorModalTarget && (
          <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 px-4">
            <div className="max-w-2xl w-full rounded-xl bg-white shadow-xl border border-gray-200 p-6">
              <div className="flex items-center justify-between mb-4">
                <h3 className="text-lg font-semibold text-gray-900">Quick content generator</h3>
                <button
                  onClick={() => setGeneratorModalTarget(null)}
                  className="text-gray-500 hover:text-gray-700"
                  aria-label="Close"
                >
                  ✕
                </button>
              </div>
              <p className="text-sm text-gray-600">
                Generator: <span className="font-medium text-gray-900">{generatorModalTarget}</span>
              </p>
              <p className="text-xs text-gray-500 mt-2">
                Integrate your existing quick-content generator here.
              </p>
              <div className="mt-4 flex justify-end">
                <button
                  onClick={() => setGeneratorModalTarget(null)}
                  className="px-3 py-2 text-sm rounded-lg border border-gray-300 text-gray-700 hover:bg-gray-50"
                >
                  Close
                </button>
              </div>
            </div>
          </div>
        )}

        {previewModalOpen && (
          <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 px-4">
            <div className="max-w-2xl w-full rounded-xl bg-white shadow-xl border border-gray-200 p-6">
              <div className="flex items-center justify-between mb-4">
                <h3 className="text-lg font-semibold text-gray-900">Strategy Preview</h3>
                <button
                  onClick={() => {
                    setPreviewModalOpen(false);
                    setPreviewData(null);
                    setPreviewError(null);
                  }}
                  className="text-gray-500 hover:text-gray-700"
                >
                  ✕
                </button>
              </div>

              {previewLoading && (
                <div className="text-sm text-gray-500">Generating preview...</div>
              )}
              {previewError && (
                <div className="text-sm text-red-600 mb-3">{previewError}</div>
              )}

              {previewData && (
                <div className="space-y-3 text-sm text-gray-700">
                  <div>
                    <div className="text-xs text-gray-500">Confidence</div>
                    <div className="font-medium text-gray-900">
                      {typeof previewConfidence === 'number' ? previewConfidence : '—'}
                    </div>
                  </div>
                  <div>
                    <div className="text-xs text-gray-500">Platform Mix</div>
                    <div className="font-medium text-gray-900">
                      {Array.isArray(previewData.platform_mix)
                        ? previewData.platform_mix.join(', ')
                        : '—'}
                    </div>
                  </div>
                  <div>
                    <div className="text-xs text-gray-500">Content Mix</div>
                    <div className="font-medium text-gray-900">
                      {Array.isArray(previewData.content_mix)
                        ? previewData.content_mix.join(', ')
                        : '—'}
                    </div>
                  </div>
                  <div>
                    <div className="text-xs text-gray-500">Weekly Frequency</div>
                    <div className="font-medium text-gray-900 whitespace-pre-wrap">
                      {previewData.frequency_plan
                        ? JSON.stringify(previewData.frequency_plan, null, 2)
                        : '—'}
                    </div>
                  </div>
                  <div>
                    <div className="text-xs text-gray-500">Content Frequency</div>
                    <div className="font-medium text-gray-900 whitespace-pre-wrap">
                      {previewContentFrequency
                        ? JSON.stringify(previewContentFrequency, null, 2)
                        : '—'}
                    </div>
                  </div>
                  <div>
                    <div className="text-xs text-gray-500">Reuse Strategy</div>
                    <div className="font-medium text-gray-900">
                      {Array.isArray(previewData.reuse_plan)
                        ? previewData.reuse_plan.join(', ')
                        : '—'}
                    </div>
                  </div>
                  <div>
                    <div className="text-xs text-gray-500">Narrative Direction</div>
                    <div className="font-medium text-gray-900 whitespace-pre-wrap">
                      {previewData.narrative_direction || '—'}
                    </div>
                  </div>
                </div>
              )}

              <div className="mt-4 space-y-3">
                <div>
                  <label className="block text-xs text-gray-500">Opinion note</label>
                  <textarea
                    value={previewOpinionNote}
                    onChange={(event) => setPreviewOpinionNote(event.target.value)}
                    className="mt-1 w-full border border-gray-300 rounded-lg px-3 py-2 text-sm"
                    rows={3}
                  />
                </div>
                <div>
                  <label className="block text-xs text-gray-500">Confidence rating (1-5)</label>
                  <select
                    value={previewConfidenceRating}
                    onChange={(event) =>
                      setPreviewConfidenceRating(
                        event.target.value ? Number(event.target.value) : ''
                      )
                    }
                    className="mt-1 w-full border border-gray-300 rounded-lg px-3 py-2 text-sm"
                  >
                    <option value="">Select</option>
                    {[1, 2, 3, 4, 5].map((value) => (
                      <option key={value} value={value}>
                        {value}
                      </option>
                    ))}
                  </select>
                </div>
              </div>

              <div className="mt-5 flex flex-wrap gap-2">
                <button
                  onClick={regeneratePreview}
                  disabled={previewLoading}
                  className="px-3 py-2 text-xs rounded-lg border border-gray-300"
                >
                  Regenerate Preview
                </button>
                <button
                  onClick={savePreviewOpinion}
                  disabled={previewLoading || !previewRecommendationId}
                  className="px-3 py-2 text-xs rounded-lg border border-gray-300"
                >
                  Add Opinion
                </button>
                <button
                  onClick={acceptPreviewAndDraftPlan}
                  disabled={previewLoading || !previewRecommendationId || !previewSnapshotHash}
                  className="px-3 py-2 text-xs rounded-lg bg-emerald-600 text-white"
                >
                  Accept Preview
                </button>
                {!previewRecommendationId && (
                  <div className="text-xs text-gray-500">
                    Evaluate with AI to enable opinions and drafting.
                  </div>
                )}
              </div>
            </div>
          </div>
        )}

        {groupPreviewOpen && (
          <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 px-4">
            <div className="max-w-4xl w-full rounded-xl bg-white shadow-xl border border-gray-200 p-6">
              <div className="flex items-center justify-between mb-4">
                <h3 className="text-lg font-semibold text-gray-900">Group Recommendations</h3>
                <button
                  onClick={() => setGroupPreviewOpen(false)}
                  className="text-gray-500 hover:text-gray-700"
                >
                  ✕
                </button>
              </div>
              {groupPreviewError && (
                <div className="mb-3 text-sm text-red-600">{groupPreviewError}</div>
              )}
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-sm">
                <div className="space-y-3">
                  <div className="text-xs font-semibold text-gray-700">Groups</div>
                  {Object.entries(groupNames)
                    .sort((a, b) => {
                      const aGroup = groupPreview?.groups?.find((grp: any) => grp.group_id === a[0]) || {};
                      const bGroup = groupPreview?.groups?.find((grp: any) => grp.group_id === b[0]) || {};
                      if (groupSortMode === 'reach') {
                        const rank = (value: string) =>
                          value === 'High' ? 3 : value === 'Medium' ? 2 : value === 'Low' ? 1 : 0;
                        return rank(bGroup.expected_reach) - rank(aGroup.expected_reach);
                      }
                      if (groupSortMode === 'lead') {
                        const rank = (value: string) =>
                          value === 'High' ? 3 : value === 'Medium' ? 2 : value === 'Low' ? 1 : 0;
                        return rank(bGroup.expected_lead_potential) - rank(aGroup.expected_lead_potential);
                      }
                      if (groupSortMode === 'priority') {
                        const aPriority =
                          typeof aGroup.go_live_priority === 'number' ? aGroup.go_live_priority : 999;
                        const bPriority =
                          typeof bGroup.go_live_priority === 'number' ? bGroup.go_live_priority : 999;
                        return aPriority - bPriority;
                      }
                      if (groupSortMode === 'urgency') {
                        const aDays =
                          typeof aGroup.execution_window?.recommended_start_within_days === 'number'
                            ? aGroup.execution_window.recommended_start_within_days
                            : 999;
                        const bDays =
                          typeof bGroup.execution_window?.recommended_start_within_days === 'number'
                            ? bGroup.execution_window.recommended_start_within_days
                            : 999;
                        return aDays - bDays;
                      }
                      if (groupSortMode === 'revenue') {
                        const aRevenue = aGroup.growth_forecast?.estimated_revenue_30d?.max ?? 0;
                        const bRevenue = bGroup.growth_forecast?.estimated_revenue_30d?.max ?? 0;
                        return bRevenue - aRevenue;
                      }
                      if (groupSortMode === 'leads') {
                        const aLeads = aGroup.growth_forecast?.estimated_leads_30d?.max ?? 0;
                        const bLeads = bGroup.growth_forecast?.estimated_leads_30d?.max ?? 0;
                        return bLeads - aLeads;
                      }
                      if (groupSortMode === 'roi') {
                        const complexityRank = (value: string) =>
                          value === 'Low' ? 3 : value === 'Medium' ? 2 : value === 'High' ? 1 : 0;
                        const aRevenue = aGroup.growth_forecast?.estimated_revenue_30d?.max ?? 0;
                        const bRevenue = bGroup.growth_forecast?.estimated_revenue_30d?.max ?? 0;
                        const aComplex = complexityRank(aGroup.execution_complexity);
                        const bComplex = complexityRank(bGroup.execution_complexity);
                        const aScore = aComplex ? aRevenue / aComplex : aRevenue;
                        const bScore = bComplex ? bRevenue / bComplex : bRevenue;
                        return bScore - aScore;
                      }
                      if (groupSortMode === 'reliability') {
                        const aConfidence =
                          aGroup.growth_forecast?.forecast_confidence_band?.confidence_percentage_range?.max ?? 0;
                        const bConfidence =
                          bGroup.growth_forecast?.forecast_confidence_band?.confidence_percentage_range?.max ?? 0;
                        return bConfidence - aConfidence;
                      }
                      const rank = (value: string) =>
                        value === 'Low' ? 3 : value === 'Medium' ? 2 : value === 'High' ? 1 : 0;
                      return rank(bGroup.execution_complexity) - rank(aGroup.execution_complexity);
                    })
                    .map(([groupId, name]) => {
                    const groupData = groupPreview?.groups?.find((grp: any) => grp.group_id === groupId) || {};
                    return (
                    <div key={groupId} className="border rounded-lg p-3">
                      <input
                        value={name}
                        onChange={(event) =>
                          setGroupNames((prev) => ({ ...prev, [groupId]: event.target.value }))
                        }
                        className="w-full border border-gray-200 rounded px-2 py-1 text-xs"
                      />
                      <div className="mt-2 flex flex-wrap gap-2 text-[10px]">
                        {typeof groupData.go_live_priority === 'number' && (
                          <span className="rounded-full bg-indigo-600 px-2 py-1 text-white">
                            #{groupData.go_live_priority}
                          </span>
                        )}
                        {groupData.execution_window?.urgency_level && (
                          <span className="rounded-full bg-red-100 px-2 py-1 text-red-700">
                            Urgency: {groupData.execution_window.urgency_level}
                          </span>
                        )}
                        {typeof groupData.execution_window?.recommended_start_within_days === 'number' && (
                          <span className="rounded-full bg-rose-100 px-2 py-1 text-rose-700">
                            Start within {groupData.execution_window.recommended_start_within_days} days
                          </span>
                        )}
                        {groupData.expected_reach && (
                          <span className="rounded-full bg-emerald-100 px-2 py-1 text-emerald-700">
                            Reach: {groupData.expected_reach}
                          </span>
                        )}
                        {groupData.expected_engagement && (
                          <span className="rounded-full bg-blue-100 px-2 py-1 text-blue-700">
                            Engagement: {groupData.expected_engagement}
                          </span>
                        )}
                        {groupData.execution_complexity && (
                          <span className="rounded-full bg-amber-100 px-2 py-1 text-amber-800">
                            Complexity: {groupData.execution_complexity}
                          </span>
                        )}
                        {groupData.expected_lead_potential && (
                          <span className="rounded-full bg-purple-100 px-2 py-1 text-purple-700">
                            Lead Potential: {groupData.expected_lead_potential}
                          </span>
                        )}
                      </div>
                      {groupData.priority_rationale && (
                        <div className="mt-2 text-[11px] text-gray-600">
                          {groupData.priority_rationale}
                        </div>
                      )}
                      {groupData.execution_window?.timing_rationale && (
                        <div className="mt-1 text-[11px] text-gray-500">
                          {groupData.execution_window.timing_rationale}
                        </div>
                      )}
                      {groupData.growth_forecast && (
                        <div className="mt-3 text-[11px] text-gray-600 space-y-2">
                          <div>
                            Estimated Leads: {groupData.growth_forecast.estimated_leads_30d?.min ?? '—'}–
                            {groupData.growth_forecast.estimated_leads_30d?.max ?? '—'}
                          </div>
                          <div>
                            Estimated Revenue: {groupData.growth_forecast.estimated_revenue_30d?.min ?? '—'}–
                            {groupData.growth_forecast.estimated_revenue_30d?.max ?? '—'}{' '}
                            {groupData.growth_forecast.estimated_revenue_30d?.currency || 'INR'}
                          </div>
                          {(() => {
                            const band = groupData.growth_forecast.forecast_confidence_band;
                            if (!band) {
                              return null;
                            }
                            const level = band.level || 'Low';
                            const minRange = band.confidence_percentage_range?.min ?? 0;
                            const maxRange = band.confidence_percentage_range?.max ?? 0;
                            const barValue = Math.max(0, Math.min(100, maxRange));
                            const barClass =
                              level === 'High'
                                ? 'bg-green-500'
                                : level === 'Medium'
                                ? 'bg-amber-500'
                                : 'bg-red-500';
                            return (
                              <div className="space-y-1">
                                <div className="flex items-center gap-2">
                                  <span
                                    className={`rounded-full px-2 py-1 text-[10px] ${
                                      level === 'High'
                                        ? 'bg-green-100 text-green-700'
                                        : level === 'Medium'
                                        ? 'bg-amber-100 text-amber-700'
                                        : 'bg-red-100 text-red-700'
                                    }`}
                                  >
                                    Forecast Confidence: {level}
                                  </span>
                                  <span className="text-[10px] text-gray-500">
                                    {minRange}%–{maxRange}%
                                  </span>
                                </div>
                                <div className="h-2 w-full rounded bg-gray-100">
                                  <div className={`h-2 rounded ${barClass}`} style={{ width: `${barValue}%` }} />
                                </div>
                                {Array.isArray(band.drivers) && band.drivers.length > 0 && (
                                  <div className="text-[10px] text-gray-500">
                                    Key drivers: {band.drivers.join(', ')}
                                  </div>
                                )}
                              </div>
                            );
                          })()}
                          {Array.isArray(groupData.growth_forecast.recommended_budget_allocation) && (
                            <div>
                              <div className="text-[10px] text-gray-500 mb-1">Budget Split</div>
                              <div className="space-y-1">
                                {groupData.growth_forecast.recommended_budget_allocation.map(
                                  (item: any) => (
                                    <div key={item.platform} className="flex items-center gap-2">
                                      <div className="w-20 text-[10px] text-gray-600">
                                        {item.platform}
                                      </div>
                                      <div className="flex-1 h-2 bg-gray-100 rounded">
                                        <div
                                          className="h-2 bg-indigo-500 rounded"
                                          style={{ width: `${Math.min(100, item.percentage || 0)}%` }}
                                        />
                                      </div>
                                      <div className="text-[10px] text-gray-600 w-10 text-right">
                                        {item.percentage ?? 0}%
                                      </div>
                                    </div>
                                  )
                                )}
                              </div>
                            </div>
                          )}
                        </div>
                      )}
                      <div className="mt-2 text-[11px] text-gray-500">
                        {groupData?.rationale || '—'}
                      </div>
                      <button
                        onClick={() => removeEmptyGroup(groupId)}
                        className="mt-2 text-[10px] text-red-600"
                      >
                        Remove empty group
                      </button>
                    </div>
                  )})}
                  <button
                    onClick={addGroup}
                    className="px-2 py-1 text-xs rounded border border-gray-300"
                  >
                    Add Group
                  </button>
                </div>
                <div className="space-y-3">
                  <div className="text-xs font-semibold text-gray-700">Recommendations</div>
                  {getSelectedRecommendationPayload().map((item: any) => (
                    <div key={item.snapshot_hash} className="border rounded-lg p-3">
                      <div className="text-xs font-semibold text-gray-900">{item.topic}</div>
                      <div className="mt-2">
                        <label className="text-[10px] text-gray-500">Group</label>
                        <select
                          value={groupAssignments[item.snapshot_hash] || ''}
                          onChange={(event) =>
                            setGroupAssignments((prev) => ({
                              ...prev,
                              [item.snapshot_hash]: event.target.value,
                            }))
                          }
                          className="mt-1 w-full border border-gray-200 rounded px-2 py-1 text-xs"
                        >
                          <option value="">Unassigned</option>
                          {Object.entries(groupNames).map(([groupId, name]) => (
                            <option key={groupId} value={groupId}>
                              {name}
                            </option>
                          ))}
                        </select>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
              <div className="mt-4 flex flex-wrap gap-2 text-[11px] text-gray-600">
                <span className="text-xs font-semibold text-gray-700">Sort groups by:</span>
                <button
                  onClick={() => setGroupSortMode('reach')}
                  className={`px-2 py-1 rounded border ${
                    groupSortMode === 'reach' ? 'bg-indigo-600 text-white' : 'border-gray-300'
                  }`}
                >
                  Highest reach
                </button>
                <button
                  onClick={() => setGroupSortMode('lead')}
                  className={`px-2 py-1 rounded border ${
                    groupSortMode === 'lead' ? 'bg-indigo-600 text-white' : 'border-gray-300'
                  }`}
                >
                  Highest lead potential
                </button>
                <button
                  onClick={() => setGroupSortMode('priority')}
                  className={`px-2 py-1 rounded border ${
                    groupSortMode === 'priority' ? 'bg-indigo-600 text-white' : 'border-gray-300'
                  }`}
                >
                  Recommended launch order
                </button>
                <button
                  onClick={() => setGroupSortMode('urgency')}
                  className={`px-2 py-1 rounded border ${
                    groupSortMode === 'urgency' ? 'bg-indigo-600 text-white' : 'border-gray-300'
                  }`}
                >
                  Most time sensitive
                </button>
                <button
                  onClick={() => setGroupSortMode('revenue')}
                  className={`px-2 py-1 rounded border ${
                    groupSortMode === 'revenue' ? 'bg-indigo-600 text-white' : 'border-gray-300'
                  }`}
                >
                  Highest revenue
                </button>
                <button
                  onClick={() => setGroupSortMode('leads')}
                  className={`px-2 py-1 rounded border ${
                    groupSortMode === 'leads' ? 'bg-indigo-600 text-white' : 'border-gray-300'
                  }`}
                >
                  Highest leads
                </button>
                <button
                  onClick={() => setGroupSortMode('roi')}
                  className={`px-2 py-1 rounded border ${
                    groupSortMode === 'roi' ? 'bg-indigo-600 text-white' : 'border-gray-300'
                  }`}
                >
                  Best ROI
                </button>
                <button
                  onClick={() => setGroupSortMode('reliability')}
                  className={`px-2 py-1 rounded border ${
                    groupSortMode === 'reliability' ? 'bg-indigo-600 text-white' : 'border-gray-300'
                  }`}
                >
                  Most reliable forecast
                </button>
                <button
                  onClick={() => setGroupSortMode('complexity')}
                  className={`px-2 py-1 rounded border ${
                    groupSortMode === 'complexity' ? 'bg-indigo-600 text-white' : 'border-gray-300'
                  }`}
                >
                  Lowest complexity
                </button>
              </div>
              <div className="mt-5 flex flex-wrap gap-2">
                <button
                  onClick={confirmGroupedCampaign}
                  disabled={isCreatingGroupedCampaign}
                  className="px-3 py-2 text-xs rounded bg-indigo-600 text-white disabled:opacity-50"
                >
                  {isCreatingGroupedCampaign ? 'Creating...' : 'Confirm & Create Campaign'}
                </button>
              </div>
            </div>
          </div>
        )}

        {errorMessage && (
          <div className="bg-red-50 border border-red-200 text-red-800 text-sm rounded-lg p-3">
            {errorMessage}
          </div>
        )}
        {noExternalSignals && (
          <div className="bg-yellow-50 border border-yellow-200 text-yellow-900 text-sm rounded-lg p-3">
            Not enough trend data available. Using fallback strategy.
          </div>
        )}
        {showNoveltyWarning && (
          <div className="bg-orange-50 border border-orange-200 text-orange-900 text-sm rounded-lg p-3">
            ⚠️ Some themes were regenerated to avoid repeating past campaigns.
            <div className="text-xs text-orange-800 mt-1">
              Campaign memory detected overlap. Confidence adjusted accordingly.
            </div>
          </div>
        )}

        <div className="space-y-4">
          {engineResult ? (
            <>
              <div className="bg-white rounded-lg shadow p-6 space-y-4">
                <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-4">
                  <div>
                    <h2 className="text-lg font-semibold text-gray-900">Recommendation Overview</h2>
                    <p className="text-sm text-gray-500">{engineResult.explanation}</p>
                  </div>
                  <div className="w-full md:w-64">
                    <div className="text-xs text-gray-500 mb-1">Confidence</div>
                    <div className="h-2 bg-gray-100 rounded-full overflow-hidden">
                      <div
                        className="h-full bg-indigo-500"
                        style={{ width: `${confidencePercent}%` }}
                      />
                    </div>
                    <div className={`text-xs mt-1 ${confidenceMeta.className}`}>
                      {confidenceMeta.label} • {confidencePercent}%
                    </div>
                  </div>
                </div>
                <div className="text-xs text-gray-600">
                  Sources: {engineResult.sources?.length ? engineResult.sources.join(', ') : '—'}
                </div>
              </div>

              {(engineResult.persona_summary || engineResult.scoring_adjustments) && (
                <div className="bg-white rounded-lg shadow p-6">
                  <h3 className="text-sm font-semibold text-gray-900 mb-3">Persona & Scoring</h3>
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-xs text-gray-700">
                    <div className="border rounded-lg p-3">
                      <div className="font-semibold text-gray-900">Persona Summary</div>
                      <div className="mt-2 text-xs text-gray-600">
                        Personas:{' '}
                        {engineResult.persona_summary?.personas?.length
                          ? engineResult.persona_summary.personas.join(', ')
                          : '—'}
                      </div>
                      <div className="text-xs text-gray-600 mt-1">
                        Tone: {engineResult.persona_summary?.tone || '—'}
                      </div>
                      <div className="text-xs text-gray-600 mt-1">
                        Preferred platforms:{' '}
                        {engineResult.persona_summary?.platform_preferences?.length
                          ? engineResult.persona_summary.platform_preferences.join(', ')
                          : '—'}
                      </div>
                    </div>
                    <div className="border rounded-lg p-3">
                      <div className="font-semibold text-gray-900">Scoring Adjustments</div>
                      <div className="mt-2 text-xs text-gray-600">
                        Base confidence: {engineResult.scoring_adjustments?.base_confidence ?? '—'}
                      </div>
                      <div className="text-xs text-gray-600">
                        Adjusted confidence: {engineResult.scoring_adjustments?.adjusted_confidence ?? '—'}
                      </div>
                      <div className="text-xs text-gray-600">
                        Persona fit: {engineResult.scoring_adjustments?.persona_fit ?? '—'}
                      </div>
                      <div className="text-xs text-gray-600">
                        Budget fit: {engineResult.scoring_adjustments?.budget_fit ?? '—'}
                      </div>
                      <div className="text-xs text-gray-600">
                        Competitor gap: {engineResult.scoring_adjustments?.competitor_gap ?? '—'}
                      </div>
                    </div>
                  </div>
                </div>
              )}

              {engineResult.scenario_outcomes && (
                <div className="bg-white rounded-lg shadow p-6">
                  <h3 className="text-sm font-semibold text-gray-900 mb-3">Scenario Outcomes</h3>
                  <div className="grid grid-cols-1 md:grid-cols-3 gap-3 text-xs text-gray-700">
                    <div className="border rounded-lg p-3">
                      <div className="text-gray-500">Best case</div>
                      <div className="text-lg font-semibold text-gray-900">
                        {engineResult.scenario_outcomes.best_case}%
                      </div>
                    </div>
                    <div className="border rounded-lg p-3">
                      <div className="text-gray-500">Likely case</div>
                      <div className="text-lg font-semibold text-gray-900">
                        {engineResult.scenario_outcomes.likely_case}%
                      </div>
                    </div>
                    <div className="border rounded-lg p-3">
                      <div className="text-gray-500">Worst case</div>
                      <div className="text-lg font-semibold text-gray-900">
                        {engineResult.scenario_outcomes.worst_case}%
                      </div>
                    </div>
                  </div>
                </div>
              )}

              <div className="bg-white rounded-lg shadow p-6">
                <h3 className="text-sm font-semibold text-gray-900 mb-3">Trend Sources</h3>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-3 text-xs text-gray-700">
                  {trendSourceLegend.map((item) => (
                    <div
                      key={item.key}
                      className="flex items-center justify-between border rounded-lg px-3 py-2"
                      title={item.description}
                    >
                      <span className="font-medium">{item.label}</span>
                      <span className={`px-2 py-0.5 rounded-full text-[11px] ${item.badgeClass}`}>
                        {(trendCounts as any)[item.key] || 0} trends
                      </span>
                    </div>
                  ))}
                  <div
                    className="flex items-center justify-between border rounded-lg px-3 py-2"
                    title="Trends ignored due to relevance or duplication."
                  >
                    <span className="font-medium">Ignored</span>
                    <span className="px-2 py-0.5 rounded-full text-[11px] bg-gray-100 text-gray-700">
                      {engineResult.trends_ignored.length} trends
                    </span>
                  </div>
                </div>
              </div>

              {engineResult.signal_quality && (
                <div className="bg-white rounded-lg shadow p-6">
                  <h3 className="text-sm font-semibold text-gray-900 mb-3">Signal Quality</h3>
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-xs text-gray-700">
                    <div className="border rounded-lg p-3">
                      <div className="font-semibold text-gray-900">API Health</div>
                      <div className="mt-2 space-y-1">
                        {(engineResult.signal_quality.external_api_health_snapshot || []).map((item) => {
                          const score = item.health_score ?? 0;
                          const status =
                            score >= 0.75 ? 'bg-green-100 text-green-700' : score >= 0.4 ? 'bg-yellow-100 text-yellow-700' : 'bg-red-100 text-red-700';
                          return (
                            <div key={item.api_source_id} className="flex items-center justify-between">
                              <span className="text-xs text-gray-600">{item.api_source_id}</span>
                              <span className={`px-2 py-0.5 rounded-full text-[11px] ${status}`}>
                                {(score * 100).toFixed(0)}%
                              </span>
                            </div>
                          );
                        })}
                        {(engineResult.signal_quality.external_api_health_snapshot || []).length === 0 && (
                          <div className="text-xs text-gray-500">No API health data.</div>
                        )}
                      </div>
                    </div>
                    <div className="border rounded-lg p-3">
                      <div className="font-semibold text-gray-900">Cache & Rate Limit</div>
                      <div className="mt-2 text-xs text-gray-600">
                        Cache hits: {engineResult.signal_quality.cache_hits?.hits ?? 0}
                      </div>
                      <div className="text-xs text-gray-600">
                        Cache misses: {engineResult.signal_quality.cache_hits?.misses ?? 0}
                      </div>
                      <div className="mt-2 text-xs text-gray-600">
                        Rate-limited sources:{' '}
                        {engineResult.signal_quality.rate_limited_sources?.length
                          ? engineResult.signal_quality.rate_limited_sources.join(', ')
                          : 'None'}
                      </div>
                      <div className="mt-2 text-xs text-gray-600">
                        Signal confidence avg:{' '}
                        {engineResult.signal_quality.signal_confidence_summary?.average ?? '—'}
                      </div>
                    </div>
                  </div>
                </div>
              )}

              {omnivyraStatus && (
                <div className="bg-white rounded-lg shadow p-6">
                  <h3 className="text-sm font-semibold text-gray-900 mb-3">Omnivyra Status</h3>
                  <div className="flex items-center gap-2 text-xs text-gray-700">
                    <span className={`px-2 py-0.5 rounded-full ${omnivyraStatusColor}`}>
                      {omnivyraStatus.status}
                    </span>
                    <span>Endpoint: {omnivyraStatus.endpoint || '—'}</span>
                  </div>
                  <div className="mt-2 grid grid-cols-1 md:grid-cols-2 gap-2 text-xs text-gray-600">
                    <div>Confidence: {omnivyraStatus.confidence ?? '—'}</div>
                    <div>Contract version: {omnivyraStatus.contract_version ?? '—'}</div>
                    <div>Latency: {omnivyraStatus.latency_ms ?? '—'} ms</div>
                    <div>Last error: {omnivyraStatus.last_error ?? '—'}</div>
                    <div>Fallback reason: {omnivyraStatus.fallback_reason ?? '—'}</div>
                  </div>
                </div>
              )}

              {engineResult.omnivyra_metadata && (
                <div className="bg-white rounded-lg shadow p-6">
                  <details className="text-sm text-gray-700">
                    <summary className="cursor-pointer text-sm font-semibold text-gray-900">
                      Why these recommendations?
                    </summary>
                    <div className="mt-2 text-sm text-gray-600">
                      {engineResult.omnivyra_metadata.explanation || 'Omnivyra explanation not available.'}
                    </div>
                    <div className="mt-2 text-xs text-gray-500">
                      Decision ID: {engineResult.omnivyra_metadata.decision_id || '—'}
                    </div>
                    <div className="mt-1 text-xs text-gray-500">
                      Confidence: {engineResult.omnivyra_metadata.confidence ?? '—'}
                    </div>
                    {engineResult.omnivyra_metadata.placeholders?.length ? (
                      <div className="mt-2 text-xs text-gray-500">
                        Placeholders: {engineResult.omnivyra_metadata.placeholders.join(', ')}
                      </div>
                    ) : null}
                  </details>
                </div>
              )}

              {engineResult.omnivyra_learning && (
                <div className="bg-white rounded-lg shadow p-6">
                  <h3 className="text-sm font-semibold text-gray-900 mb-2">
                    Learning sent to Omnivyra
                  </h3>
                  <div className="text-xs text-gray-700">
                    {engineResult.omnivyra_learning.status === 'sent' && '✅ Sent'}
                    {engineResult.omnivyra_learning.status === 'failed' && '⚠️ Failed'}
                    {engineResult.omnivyra_learning.status === 'skipped' && '⏭ Skipped (flag off)'}
                  </div>
                  {engineResult.omnivyra_learning.error && (
                    <div className="text-xs text-red-600 mt-1">
                      {engineResult.omnivyra_learning.error}
                    </div>
                  )}
                </div>
              )}

              <div className="bg-white rounded-lg shadow p-6">
                <h3 className="text-sm font-semibold text-gray-900 mb-3">Trend Recommendations</h3>
                <div className="flex flex-wrap gap-2">
                  {engineResult.trends_used.map((trend, index) => (
                    <div key={`${trend.topic}-${index}`} className="flex flex-col">
                      <div className="text-xs bg-indigo-50 text-indigo-700 px-2 py-1 rounded-full flex items-center gap-2">
                        <span>{trend.topic}</span>
                        {trendExplanationMap.has(trend.topic.trim().toLowerCase()) ? (
                          <button
                            type="button"
                            onClick={() => {
                              const key = `${trend.topic}-${index}`;
                              setExpandedTrendKey((prev) => (prev === key ? null : key));
                            }}
                            className="text-[10px] text-indigo-500 hover:text-indigo-700"
                            aria-expanded={expandedTrendKey === `${trend.topic}-${index}`}
                            aria-label="Toggle explanation"
                          >
                            Context
                          </button>
                        ) : null}
                      </div>
                      {expandedTrendKey === `${trend.topic}-${index}` ? (
                        <ul className="mt-1 text-[11px] text-gray-500 list-disc pl-4 space-y-1">
                          {(trendExplanationMap.get(trend.topic.trim().toLowerCase()) || []).map(
                            (explanation, idx) => (
                              <li key={`${trend.topic}-${index}-exp-${idx}`}>{explanation}</li>
                            )
                          )}
                        </ul>
                      ) : null}
                    </div>
                  ))}
                  {engineResult.trends_used.length === 0 && (
                    <span className="text-xs text-gray-500">No external trends used.</span>
                  )}
                </div>
              </div>

              <div className="bg-white rounded-lg shadow p-6">
                <h3 className="text-sm font-semibold text-gray-900 mb-3">Trends Ignored</h3>
                <div className="flex flex-wrap gap-2">
                  {engineResult.trends_ignored.map((trend, index) => (
                    <span
                      key={`${trend.topic}-${index}`}
                      className="text-xs bg-gray-100 text-gray-700 px-2 py-1 rounded-full"
                    >
                      {trend.topic}
                    </span>
                  ))}
                  {engineResult.trends_ignored.length === 0 && (
                    <span className="text-xs text-gray-500">No ignored trends.</span>
                  )}
                </div>
              </div>

              <div className="bg-white rounded-lg shadow p-6">
                <h3 className="text-sm font-semibold text-gray-900 mb-3">Strategy Recommendations</h3>
                <div className="space-y-3 text-sm text-gray-700">
                  {engineResult.weekly_plan.map((week) => (
                    <div key={`week-${week.week_number}`} className="border rounded-lg p-3">
                      <div className="font-semibold text-gray-900">
                        Week {week.week_number}: {week.theme}
                      </div>
                      <div className="text-xs text-gray-500 mt-1">
                        Trends: {(week.trend_influence || []).join(', ') || '—'}
                      </div>
                      <div className="text-xs text-gray-500">
                        Platforms: {(week.platforms || []).join(', ') || '—'}
                      </div>
                    </div>
                  ))}
                  {engineResult.weekly_plan.length === 0 && (
                    <div className="text-xs text-gray-500">Weekly plan not available.</div>
                  )}
                </div>
              </div>

              <div className="bg-white rounded-lg shadow p-6">
                <h3 className="text-sm font-semibold text-gray-900 mb-3">Daily Plan</h3>
                <div className="space-y-2 text-sm text-gray-700">
                  {engineResult.daily_plan.slice(0, 14).map((day, index) => (
                    <div key={`day-${index}`} className="flex items-center justify-between border-b pb-2">
                      <div>
                        <div className="font-medium text-gray-900">{day.date}</div>
                        <div className="text-xs text-gray-500">
                          {day.platform} • {day.content_type}
                        </div>
                      </div>
                      <div className="text-xs text-gray-600 text-right max-w-xs">
                        {day.topic}
                      </div>
                    </div>
                  ))}
                  {engineResult.daily_plan.length === 0 && (
                    <div className="text-xs text-gray-500">Daily plan not available.</div>
                  )}
                  {engineResult.daily_plan.length > 14 && (
                    <div className="text-xs text-gray-500">
                      Showing first 14 entries. Generate the campaign for full plan.
                    </div>
                  )}
                </div>
              </div>
            </>
          ) : (
            !isLoading && <div className="text-sm text-gray-500">No recommendations yet.</div>
          )}
        </div>
      </div>
    </>
  );
}
