/** RecommendationsSectionsA — verbatim JSX slice of RecommendationsContent (babel-verified). */
import React, { useEffect, useMemo, useState } from 'react';
import { useRouter } from 'next/router';
import { useCompanyContext } from '../components/CompanyContext';
import { fetchWithAuth } from '../components/community-ai/fetchWithAuth';
import VoiceNotesComponent from '../components/VoiceNotesComponent';
import {
  buildTrendSourceCounts,
  getConfidenceLabel,
  hasNoExternalSignals,
  shouldShowNoveltyWarning,
} from '../backend/services/recommendationUiExplainability';
import TrendCampaignsTab from '../components/recommendations/tabs/TrendCampaignsTab';
import NextStrategicDirection from '../components/campaigns/NextStrategicDirection';
import { useRecommendationViewMode } from '../components/recommendations/hooks/useRecommendationViewMode';
import ActiveLeadsTab from '../components/recommendations/tabs/ActiveLeadsTab';
import MarketPulseTab from '../components/recommendations/tabs/MarketPulseTab';
import RecommendationStatusWidget from '../components/recommendations/RecommendationStatusWidget';
import StrategySignalsWidget from '../components/dashboard/StrategySignalsWidget';
import {
  type TrendSignal,
  type RecommendationEngineResult,
  type DetectedOpportunity,
  type TrendSourceLegendItem,
  type ExternalApiOption,
  OPPORTUNITY_TAB_TYPES,
  TREND_SOURCE_LEGEND,
} from '../pages/recommendations.types';

type IntelligentMixState = import('@/pages/command-center/intelligent-mix-strategy').IntelligentMixState;

import type { useRecommendationsState } from '../hooks/useRecommendationsState';

type RecState = ReturnType<typeof useRecommendationsState>;

import { useRecommendationsContentController } from './RecommendationsContentController';

export default function RecommendationsSectionsA({ f }: { f: ReturnType<typeof useRecommendationsContentController> }) {
  const {
    d,
    acceptPreviewAndDraftPlan, activeOpportunityTab, activeWorkspaceTab, addGroup, autoGenerated, availableApis, campaignIdLocked,
    campaigns, canGenerateDetectedPlaybook, canGroupRecommendations, canManageRecommendationState, canSeeDetectedOpportunities,
    companies, confidenceMeta, confidencePercent, confidenceRatio, confirmGroupedCampaign, detectedError, detectedLoading,
    detectedOpportunities, detectedPlaybookLoading, detectedPlaybookOpen, detectedPlaybooks, detectedReasoningOpen,
    detectedTopicSources, dismissDetectedOpportunity, dismissedOpportunities, draftError, engineOverrides, engineResult,
    errorMessage, evaluateDetectedOpportunity, expandedTrendKey, fetchDetectedOpportunities, fetchStateMap, generateRecommendations,
    generatorModalTarget, getSelectedRecommendationPayload, groupAssignments, groupNames, groupPreview, groupPreviewError,
    groupPreviewLoading, groupPreviewOpen, groupSortMode, handleCreateCampaignFromRecommendation, handleManualSubmit,
    handleOpportunityAction, handleOpportunityPromote, handlePreparePlanFromRecommendation, hasPermission, intelligentMixContext,
    isAdmin, isApiLoading, isAuthenticated, isCampaignLoading, isCompanyLoading, isCreatingGroupedCampaign, isLoading,
    isSubmittingManual, lastRefresh, lastRefreshSource, manualNarrative, manualObjective, manualPlatformPreference, manualTopic,
    noExternalSignals, omnivyraStatus, omnivyraStatusColor, openGroupPreview, openPreviewForDetectedOpportunity,
    openPreviewForRecommendation, opportunityRegions, prefillBlogId, previewConfidence, previewConfidenceRating,
    previewContentFrequency, previewCurrentState, previewData, previewError, previewLoading, previewModalOpen, previewOpinionNote,
    previewPriorityBucket, previewRecommendationId, previewSnapshotHash, recommendationBySnapshot, recommendationDetails,
    recommendationStates, recommendationSummaries, recommendedThisWeek, refreshRecommendations, regeneratePreview, removeEmptyGroup,
    resolveRecommendationIdBySnapshot, router, savePreviewOpinion, selectedApiIds, selectedCampaignId, selectedCampaignName,
    selectedCompanyId, selectedRecommendations, setActiveOpportunityTab, setActiveWorkspaceTab, setAutoGenerated, setAvailableApis,
    setCampaignIdLocked, setCampaigns, setDetectedError, setDetectedLoading, setDetectedOpportunities, setDetectedPlaybookLoading,
    setDetectedPlaybookOpen, setDetectedPlaybooks, setDetectedReasoningOpen, setDismissedOpportunities, setDraftError,
    setEngineOverride, setEngineOverrides, setEngineResult, setErrorMessage, setExpandedTrendKey, setGeneratorModalTarget,
    setGroupAssignments, setGroupNames, setGroupPreview, setGroupPreviewError, setGroupPreviewLoading, setGroupPreviewOpen,
    setGroupSortMode, setIsApiLoading, setIsCampaignLoading, setIsCreatingGroupedCampaign, setIsLoading, setIsSubmittingManual,
    setLastRefresh, setLastRefreshSource, setManualNarrative, setManualObjective, setManualPlatformPreference, setManualTopic,
    setOpportunityRegions, setPrefillBlogId, setPreviewConfidence, setPreviewConfidenceRating, setPreviewContentFrequency,
    setPreviewCurrentState, setPreviewData, setPreviewError, setPreviewLoading, setPreviewModalOpen, setPreviewOpinionNote,
    setPreviewPriorityBucket, setPreviewRecommendationId, setPreviewSnapshotHash, setRecommendationBySnapshot,
    setRecommendationDetails, setRecommendationStates, setRecommendationSummaries, setSelectedApiIds, setSelectedCampaignId,
    setSelectedCampaignName, setSelectedCompanyId, setSelectedRecommendations, setSimulateScenarios, setSortByPriority,
    setStateError, setTrendStrategicIntents, showLoadingState, showNoCompanyState, showNoveltyWarning, simulateScenarios,
    sortByPriority, stateError, toggleApiSelection, toggleDetectedPlaybook, toggleDetectedReasoning, toggleRecommendationSelection,
    trendCounts, trendExplanationMap, trendSourceLegend, trendStrategicIntents, updateRecommendationState, user, userRole, viewMode
  } = f;
  return (
    <>
        <section className="flex flex-col lg:flex-row gap-6">
          {selectedCompanyId && (
            <aside className="lg:w-56 shrink-0 order-first">
              <StrategySignalsWidget companyId={selectedCompanyId} fetchWithAuth={fetchWithAuth} />
              {selectedCampaignId && (
                <NextStrategicDirection
                  campaignId={selectedCampaignId}
                  campaignName={selectedCampaignName || undefined}
                  className="mt-4"
                />
              )}
            </aside>
          )}
          <div className="flex-1 min-w-0">
          <div className="flex flex-col sm:flex-row sm:items-start sm:justify-between gap-4 mb-3">
            <h2 className="text-xl font-semibold text-gray-900">Recommendation Hub</h2>
            {selectedCompanyId && (
              <RecommendationStatusWidget companyId={selectedCompanyId} fetchWithAuth={fetchWithAuth} />
            )}
          </div>
          <div className="flex flex-wrap gap-2 border-b border-gray-200 pb-3 mb-3">
            {OPPORTUNITY_TAB_TYPES.map(({ type, label }) => (
              <button
                key={type}
                type="button"
                onClick={() => setActiveOpportunityTab(type)}
                className={`px-3 py-2 rounded-lg text-sm font-medium ${
                  activeOpportunityTab === type
                    ? 'bg-indigo-600 text-white'
                    : 'bg-gray-100 text-gray-700 hover:bg-gray-200'
                }`}
              >
                {label}
              </button>
            ))}
          </div>
          <div className="mb-4 rounded-lg border border-indigo-200 bg-indigo-50 px-4 py-3 text-sm text-indigo-900">
            Market Pulse and Active Leads now live in the dashboard Intelligence hub.
            <button
              type="button"
              onClick={() => void router.push('/intelligence')}
              className="ml-2 font-semibold underline"
            >
              Open Intelligence
            </button>
          </div>
          <div className="min-h-[120px] pt-2">
            {activeOpportunityTab === 'TREND' && (
              <TrendCampaignsTab
                companyId={selectedCompanyId}
                regions={
                  opportunityRegions.trim()
                    ? opportunityRegions.split(',').map((r) => r.trim()).filter(Boolean)
                    : undefined
                }
                engineRecommendations={(engineResult?.trends_used as Array<Record<string, unknown>> | undefined) ?? []}
                onPromote={handleOpportunityPromote}
                onAction={handleOpportunityAction}
                fetchWithAuth={fetchWithAuth}
                overrideText={engineOverrides['TREND'] ?? ''}
                onOverrideChange={(v) => setEngineOverride('TREND', v)}
                strategicIntents={trendStrategicIntents}
                onStrategicIntentsChange={setTrendStrategicIntents}
                viewMode={viewMode}
                campaignId={selectedCampaignId || null}
                initialBlogId={prefillBlogId}
                intelligentMixContext={intelligentMixContext}
              />
            )}
            {activeOpportunityTab === 'LEAD' && (
              <ActiveLeadsTab
                companyId={selectedCompanyId}
                onPromote={handleOpportunityPromote}
                onAction={handleOpportunityAction}
                fetchWithAuth={fetchWithAuth}
                onSwitchTab={setActiveOpportunityTab}
                overrideText={engineOverrides['LEAD'] ?? ''}
                onOverrideChange={(v) => setEngineOverride('LEAD', v)}
              />
            )}
            {activeOpportunityTab === 'PULSE' && (
              <MarketPulseTab
                companyId={selectedCompanyId}
                regions={
                  opportunityRegions.trim()
                    ? opportunityRegions.split(',').map((r) => r.trim()).filter(Boolean)
                    : undefined
                }
                onPromote={handleOpportunityPromote}
                onAction={handleOpportunityAction}
                fetchWithAuth={fetchWithAuth}
                onSwitchTab={setActiveOpportunityTab}
                overrideText={engineOverrides['PULSE'] ?? ''}
                onOverrideChange={(v) => setEngineOverride('PULSE', v)}
              />
            )}
          </div>
          </div>
        </section>

        {generatorModalTarget && (
          <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 px-4">
            <div className="max-w-2xl w-full rounded-xl bg-white shadow-xl border border-gray-200 p-6">
              <div className="flex items-center justify-between mb-4">
                <h3 className="text-lg font-semibold text-gray-900">Quick content generator</h3>
                <button
                  onClick={() => setGeneratorModalTarget(null)}
                  className="text-gray-500 hover:text-gray-700"
                  aria-label="Close"
                >
                  ✕
                </button>
              </div>
              <p className="text-sm text-gray-600">
                Generator: <span className="font-medium text-gray-900">{generatorModalTarget}</span>
              </p>
              <p className="text-xs text-gray-500 mt-2">
                Integrate your existing quick-content generator here.
              </p>
              <div className="mt-4 flex justify-end">
                <button
                  onClick={() => setGeneratorModalTarget(null)}
                  className="px-3 py-2 text-sm rounded-lg border border-gray-300 text-gray-700 hover:bg-gray-50"
                >
                  Close
                </button>
              </div>
            </div>
          </div>
        )}

        {previewModalOpen && (
          <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 px-4">
            <div className="max-w-2xl w-full rounded-xl bg-white shadow-xl border border-gray-200 p-6">
              <div className="flex items-center justify-between mb-4">
                <h3 className="text-lg font-semibold text-gray-900">Strategy Preview</h3>
                <button
                  onClick={() => {
                    setPreviewModalOpen(false);
                    setPreviewData(null);
                    setPreviewError(null);
                  }}
                  className="text-gray-500 hover:text-gray-700"
                >
                  ✕
                </button>
              </div>

              {previewLoading && (
                <div className="text-sm text-gray-500">Generating preview...</div>
              )}
              {previewError && (
                <div className="text-sm text-red-600 mb-3">{previewError}</div>
              )}

              {previewData && (
                <div className="space-y-3 text-sm text-gray-700">
                  <div>
                    <div className="text-xs text-gray-500">Confidence</div>
                    <div className="font-medium text-gray-900">
                      {typeof previewConfidence === 'number' ? previewConfidence : '—'}
                    </div>
                  </div>
                  <div>
                    <div className="text-xs text-gray-500">Platform Mix</div>
                    <div className="font-medium text-gray-900">
                      {Array.isArray(previewData.platform_mix)
                        ? previewData.platform_mix.join(', ')
                        : '—'}
                    </div>
                  </div>
                  <div>
                    <div className="text-xs text-gray-500">Content Mix</div>
                    <div className="font-medium text-gray-900">
                      {Array.isArray(previewData.content_mix)
                        ? previewData.content_mix.join(', ')
                        : '—'}
                    </div>
                  </div>
                  <div>
                    <div className="text-xs text-gray-500">Weekly Frequency</div>
                    <div className="font-medium text-gray-900 whitespace-pre-wrap">
                      {previewData.frequency_plan
                        ? JSON.stringify(previewData.frequency_plan, null, 2)
                        : '—'}
                    </div>
                  </div>
                  <div>
                    <div className="text-xs text-gray-500">Content Frequency</div>
                    <div className="font-medium text-gray-900 whitespace-pre-wrap">
                      {previewContentFrequency
                        ? JSON.stringify(previewContentFrequency, null, 2)
                        : '—'}
                    </div>
                  </div>
                  <div>
                    <div className="text-xs text-gray-500">Reuse Strategy</div>
                    <div className="font-medium text-gray-900">
                      {Array.isArray(previewData.reuse_plan)
                        ? previewData.reuse_plan.join(', ')
                        : '—'}
                    </div>
                  </div>
                  <div>
                    <div className="text-xs text-gray-500">Narrative Direction</div>
                    <div className="font-medium text-gray-900 whitespace-pre-wrap">
                      {previewData.narrative_direction || '—'}
                    </div>
                  </div>
                </div>
              )}

              <div className="mt-4 space-y-3">
                <div>
                  <label className="block text-xs text-gray-500">Opinion note</label>
                  <textarea
                    value={previewOpinionNote}
                    onChange={(event) => setPreviewOpinionNote(event.target.value)}
                    className="mt-1 w-full border border-gray-300 rounded-lg px-3 py-2 text-sm"
                    rows={3}
                  />
                </div>
                <div>
                  <label className="block text-xs text-gray-500">Confidence rating (1-5)</label>
                  <select
                    value={previewConfidenceRating}
                    onChange={(event) =>
                      setPreviewConfidenceRating(
                        event.target.value ? Number(event.target.value) : ''
                      )
                    }
                    className="mt-1 w-full border border-gray-300 rounded-lg px-3 py-2 text-sm"
                  >
                    <option value="">Select</option>
                    {[1, 2, 3, 4, 5].map((value) => (
                      <option key={value} value={value}>
                        {value}
                      </option>
                    ))}
                  </select>
                </div>
              </div>

              <div className="mt-5 flex flex-wrap gap-2">
                <button
                  onClick={regeneratePreview}
                  disabled={previewLoading}
                  className="px-3 py-2 text-xs rounded-lg border border-gray-300"
                >
                  Regenerate Preview
                </button>
                <button
                  onClick={savePreviewOpinion}
                  disabled={previewLoading || !previewRecommendationId}
                  className="px-3 py-2 text-xs rounded-lg border border-gray-300"
                >
                  Add Opinion
                </button>
                <button
                  onClick={acceptPreviewAndDraftPlan}
                  disabled={previewLoading || !previewRecommendationId || !previewSnapshotHash}
                  className="px-3 py-2 text-xs rounded-lg bg-emerald-600 text-white"
                >
                  Accept Preview
                </button>
                {!previewRecommendationId && (
                  <div className="text-xs text-gray-500">
                    Evaluate with AI to enable opinions and drafting.
                  </div>
                )}
              </div>
            </div>
          </div>
        )}
    </>
  );
}
