import { NextApiRequest, NextApiResponse } from 'next';
import { supabase } from '../../../utils/supabaseClient.js';
import { evaluateCampaignReadiness } from '../../../backend/services/campaignReadinessService';
import { enforceCompanyAccess } from '../../../backend/services/userContextService';

const resolveCampaignCompanyId = async (campaignId: string) => {
  const { data: campRow } = await supabase
    .from('campaigns')
    .select('company_id')
    .eq('id', campaignId)
    .maybeSingle();
  const direct = (campRow as { company_id?: string | null } | null)?.company_id;
  if (direct) return direct;
  const { data, error } = await supabase
    .from('campaign_versions')
    .select('company_id')
    .eq('campaign_id', campaignId)
    .limit(1)
    .maybeSingle();
  if (error || !data?.company_id) {
    return null;
  }
  return data.company_id as string;
};

const validatePlaybookReference = async (playbookId: string, companyId: string) => {
  const { data, error } = await supabase
    .from('virality_playbooks')
    .select('id, company_id, status')
    .eq('id', playbookId)
    .single();
  if (error || !data) {
    return { ok: false, error: 'INVALID_PLAYBOOK_REFERENCE' };
  }
  if (data.company_id !== companyId) {
    return { ok: false, error: 'INVALID_PLAYBOOK_REFERENCE' };
  }
  return { ok: true, error: null };
};

async function handler(req: NextApiRequest, res: NextApiResponse) {
  const { id } = req.query;

  if (!id || typeof id !== 'string') {
    return res.status(400).json({ error: 'Campaign ID is required' });
  }

  // SECURITY: derive the campaign's owning company from the resource itself,
  // never trust ?companyId= from query/body. Without this gate, a caller could
  // authenticate against their own company and then operate on another company's
  // campaign by guessing the path id.
  const campaignCompanyId = await resolveCampaignCompanyId(id);
  if (!campaignCompanyId) {
    return res.status(404).json({ error: 'Campaign not found' });
  }
  const tenantContext = await enforceCompanyAccess({
    req,
    res,
    companyId: campaignCompanyId,
  });
  if (!tenantContext) return;

  if (req.method === 'GET') {
    try {
      const { data: campaign, error } = await supabase
        .from('campaigns')
        .select('id, name, description, status, current_stage, start_date, end_date, company_id')
        .eq('id', id)
        .maybeSingle();
      if (error || !campaign) {
        return res.status(404).json({ error: 'Campaign not found' });
      }
      const out = { ...campaign, company_id: (campaign as any).company_id ?? campaignCompanyId };
      return res.status(200).json({ campaign: out });
    } catch (err) {
      return res.status(500).json({ error: 'Failed to fetch campaign' });
    }
  }

  if (req.method === 'DELETE') {
    try {
      const { releaseThemeFromCampaign } = await import('../../../backend/services/companyThemeStateService');
      await releaseThemeFromCampaign(id);

      // Clean up ALL campaign-generated data before deleting the campaign.
      // Delete scheduled_posts first (has triggers on calendar_events_index).
      // Deletes all statuses — scheduled, draft, pending, published, failed —
      // because these posts were generated by the campaign pipeline.
      // Posts with campaign_id = NULL are user-created and never touched.
      const { error: spErr } = await supabase
        .from('scheduled_posts')
        .delete()
        .eq('campaign_id', id);
      if (spErr) console.warn('[delete-campaign] scheduled_posts cleanup error:', spErr.message);

      // Clean up calendar_events_index for this campaign (in case trigger missed any)
      try {
        await supabase.from('calendar_events_index').delete().eq('campaign_id', id);
      } catch { /* table may not exist */ }

      const relatedTables = [
        'daily_content_plans',
        'campaign_versions',
        'campaign_week_plan',
        'bolt_content_jobs',
        'bolt_execution_runs',
        'platform_content_slots',
        'campaign_goals',
        'campaign_metrics',
        'campaign_analytics',
        'campaign_execution_state',
      ];
      for (const table of relatedTables) {
        try {
          await supabase.from(table).delete().eq('campaign_id', id);
        } catch {
          // Table may not exist or have no rows — non-fatal
        }
      }

      // Delete campaign itself (scoped by company for defense-in-depth)
      const { error } = await supabase
        .from('campaigns')
        .delete()
        .eq('id', id)
        .eq('company_id', campaignCompanyId);

      if (error) {
        console.error('Error deleting campaign:', error);
        return res.status(500).json({ error: 'Failed to delete campaign' });
      }

      res.status(200).json({
        success: true,
        message: 'Campaign deleted successfully'
      });

    } catch (error) {
      console.error('Error in delete campaign API:', error);
      res.status(500).json({ error: 'Internal server error' });
    }
  } else if (req.method === 'PUT') {
    try {
      const {
        name,
        description,
        status,
        current_stage,
        start_date,
        end_date,
        virality_playbook_id,
        viralityPlaybookId,
        playbook,
        api_inputs,
      } = req.body;
      // Ensure playbook is reference-only: ignore any playbook payload fields.
      const playbookFieldProvided =
        Object.prototype.hasOwnProperty.call(req.body || {}, 'virality_playbook_id') ||
        Object.prototype.hasOwnProperty.call(req.body || {}, 'viralityPlaybookId');
      const resolvedPlaybookId = virality_playbook_id ?? viralityPlaybookId ?? null;
      if (playbookFieldProvided && resolvedPlaybookId) {
        const validation = await validatePlaybookReference(resolvedPlaybookId, campaignCompanyId);
        if (!validation.ok) {
          return res.status(400).json({ error: 'INVALID_PLAYBOOK_REFERENCE' });
        }
      }

      if (status === 'active') {
        const readiness = await evaluateCampaignReadiness(id);
        if (readiness.readiness_state !== 'ready') {
          return res.status(409).json({
            error: 'Campaign is not ready to activate',
            readiness: {
              readiness_percentage: readiness.readiness_percentage,
              readiness_state: readiness.readiness_state,
              blocking_issues: readiness.blocking_issues,
            },
          });
        }
      }

      // Update campaign (scoped by company for defense-in-depth)
      const { data: campaign, error } = await supabase
        .from('campaigns')
        .update({
          name,
          description,
          status,
          current_stage,
          start_date,
          end_date,
          // Playbook reference only. It does NOT affect scheduling, publishing,
          // approvals, or content generation. Campaign behavior remains unchanged.
          ...(playbookFieldProvided && { virality_playbook_id: resolvedPlaybookId }),
          updated_at: new Date().toISOString()
        })
        .eq('id', id)
        .eq('company_id', campaignCompanyId)
        .select()
        .single();

      if (error) {
        console.error('Error updating campaign:', error);
        return res.status(500).json({ error: 'Failed to update campaign' });
      }

      res.status(200).json({ 
        success: true, 
        campaign,
        message: 'Campaign updated successfully' 
      });

    } catch (error) {
      console.error('Error in update campaign API:', error);
      res.status(500).json({ error: 'Internal server error' });
    }
  } else {
    res.status(405).json({ error: 'Method not allowed' });
  }
}

export default handler;