import React, { useEffect, useMemo, useRef, useState } from 'react';
import { useRouter } from 'next/router';
import { useCompanyContext } from '../components/CompanyContext';
import Header from '../components/Header';
import { fetchWithAuth } from '../components/community-ai/fetchWithAuth';
import VoiceNotesComponent from '../components/VoiceNotesComponent';
import {
  buildTrendSourceCounts,
  getConfidenceLabel,
  hasNoExternalSignals,
  shouldShowNoveltyWarning,
} from '../backend/services/recommendationUiExplainability';
import TrendCampaignsTab from '../components/recommendations/tabs/TrendCampaignsTab';
import NextStrategicDirection from '../components/campaigns/NextStrategicDirection';
import { useRecommendationViewMode } from '../components/recommendations/hooks/useRecommendationViewMode';
import ActiveLeadsTab from '../components/recommendations/tabs/ActiveLeadsTab';
import MarketPulseTab from '../components/recommendations/tabs/MarketPulseTab';
import RecommendationStatusWidget from '../components/recommendations/RecommendationStatusWidget';
import StrategySignalsWidget from '../components/dashboard/StrategySignalsWidget';
import {
  type TrendSignal,
  type RecommendationEngineResult,
  type DetectedOpportunity,
  type TrendSourceLegendItem,
  type ExternalApiOption,
  OPPORTUNITY_TAB_TYPES,
  TREND_SOURCE_LEGEND,
} from '../pages/recommendations.types';
import { getUserScopedLocalStorage, setUserScopedLocalStorage } from '../utils/authStorage';

type IntelligentMixState = import('@/pages/command-center/intelligent-mix-strategy').IntelligentMixState;

export function useRecommendationsState() {
  const router = useRouter();
  const {
    user,
    companies,
    selectedCompanyId,
    selectedCompanyName,
    setSelectedCompanyId,
    isLoading: isCompanyLoading,
    userRole,
    hasPermission,
    isAuthenticated,
  } = useCompanyContext();
  const viewMode = useRecommendationViewMode();
  const [engineResult, setEngineResult] = useState<RecommendationEngineResult | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [errorMessage, setErrorMessage] = useState<string | null>(null);
  const [campaigns, setCampaigns] = useState<Array<{ id: string; name: string; status: string }>>([]);
  const [isCampaignLoading, setIsCampaignLoading] = useState(false);
  const [selectedCampaignId, setSelectedCampaignId] = useState<string>('');
  const [selectedCampaignName, setSelectedCampaignName] = useState<string>('');
  const [campaignIdLocked, setCampaignIdLocked] = useState(false);
  const [autoGenerated, setAutoGenerated] = useState(false);
  const [lastRefresh, setLastRefresh] = useState<string | null>(null);
  const [lastRefreshSource, setLastRefreshSource] = useState<string | null>(null);
  const [simulateScenarios, setSimulateScenarios] = useState(false);
  const [expandedTrendKey, setExpandedTrendKey] = useState<string | null>(null);
  const [availableApis, setAvailableApis] = useState<ExternalApiOption[]>([]);
  const [selectedApiIds, setSelectedApiIds] = useState<string[]>([]);
  const [isApiLoading, setIsApiLoading] = useState(false);
  const [activeWorkspaceTab, setActiveWorkspaceTab] = useState<'all' | 'shortlisted' | 'discarded'>(
    'all'
  );
  const [recommendationStates, setRecommendationStates] = useState<Record<string, string>>({});
  const [recommendationDetails, setRecommendationDetails] = useState<
    Record<
      string,
      { state: string; actor_user_id: string | null; created_at: string | null; snapshot_hash?: string | null }
    >
  >({});
  const [recommendationSummaries, setRecommendationSummaries] = useState<
    Record<
      string,
      {
        shortlisted_count: number;
        discarded_count: number;
        active_count: number;
        priority_score?: number;
        priority_bucket?: 'High' | 'Medium' | 'Low';
        last_admin_decision?: { state: string; actor_user_id: string | null; created_at: string | null };
        last_discarded?: { actor_user_id: string | null; created_at: string | null };
      }
    >
  >({});
  const [recommendationBySnapshot, setRecommendationBySnapshot] = useState<Record<string, string>>(
    {}
  );
  const [manualTopic, setManualTopic] = useState('');
  const [manualNarrative, setManualNarrative] = useState('');
  const [manualObjective, setManualObjective] = useState('');
  const [manualPlatformPreference, setManualPlatformPreference] = useState('');
  const [isSubmittingManual, setIsSubmittingManual] = useState(false);
  const [stateError, setStateError] = useState<string | null>(null);
  const [sortByPriority, setSortByPriority] = useState(true);
  const [draftError, setDraftError] = useState<string | null>(null);
  const [detectedOpportunities, setDetectedOpportunities] = useState<DetectedOpportunity[]>([]);
  const [detectedLoading, setDetectedLoading] = useState(false);
  const [detectedError, setDetectedError] = useState<string | null>(null);
  const [dismissedOpportunities, setDismissedOpportunities] = useState<Set<string>>(new Set());
  const [detectedPlaybooks, setDetectedPlaybooks] = useState<Record<string, any>>({});
  const [detectedPlaybookLoading, setDetectedPlaybookLoading] = useState<Record<string, boolean>>(
    {}
  );
  const [detectedPlaybookOpen, setDetectedPlaybookOpen] = useState<Set<string>>(new Set());
  const [detectedReasoningOpen, setDetectedReasoningOpen] = useState<Set<string>>(new Set());
  const [previewModalOpen, setPreviewModalOpen] = useState(false);
  const [generatorModalTarget, setGeneratorModalTarget] = useState<string | null>(null);
  const [previewLoading, setPreviewLoading] = useState(false);
  const [previewError, setPreviewError] = useState<string | null>(null);
  const [previewData, setPreviewData] = useState<any | null>(null);
  const [previewRecommendationId, setPreviewRecommendationId] = useState<string | null>(null);
  const [previewSnapshotHash, setPreviewSnapshotHash] = useState<string | null>(null);
  const [previewPriorityBucket, setPreviewPriorityBucket] = useState<string | null>(null);
  const [previewCurrentState, setPreviewCurrentState] = useState<string | null>(null);
  const [previewOpinionNote, setPreviewOpinionNote] = useState('');
  const [previewConfidenceRating, setPreviewConfidenceRating] = useState<number | ''>('');
  const [previewConfidence, setPreviewConfidence] = useState<number | null>(null);
  const [previewContentFrequency, setPreviewContentFrequency] = useState<any | null>(null);
  const [selectedRecommendations, setSelectedRecommendations] = useState<Set<string>>(new Set());
  const [groupPreviewOpen, setGroupPreviewOpen] = useState(false);
  const [groupPreviewLoading, setGroupPreviewLoading] = useState(false);
  const [groupPreviewError, setGroupPreviewError] = useState<string | null>(null);
  const [groupPreview, setGroupPreview] = useState<any | null>(null);
  const [groupAssignments, setGroupAssignments] = useState<Record<string, string>>({});
  const [groupNames, setGroupNames] = useState<Record<string, string>>({});
  const [isCreatingGroupedCampaign, setIsCreatingGroupedCampaign] = useState(false);
  const [groupSortMode, setGroupSortMode] = useState<
    | 'reach'
    | 'complexity'
    | 'lead'
    | 'priority'
    | 'urgency'
    | 'revenue'
    | 'leads'
    | 'roi'
    | 'reliability'
  >('reach');
  const [activeOpportunityTab, setActiveOpportunityTab] = useState<string>('TREND');
  const [prefillBlogId, setPrefillBlogId] = useState<string | null>(null);
  const intelligentMixContext = useMemo<IntelligentMixState | null>(() => {
    try {
      if (typeof router.query.intelligentMix !== 'string' || router.query.intelligentMix !== '1') {
        return null;
      }
      if (typeof window === 'undefined') return null;
      const raw = sessionStorage.getItem('intelligent-mix-strategy-state');
      return raw ? JSON.parse(raw) as IntelligentMixState : null;
    } catch {
      return null;
    }
  }, [router.query.intelligentMix]);
  const [opportunityRegions, setOpportunityRegions] = useState<string>('');
  const [trendStrategicIntents, setTrendStrategicIntents] = useState<string[]>([]);
  const [engineOverrides, setEngineOverrides] = useState<Record<string, string>>({});
  const isAdmin = useMemo(() => user?.role === 'admin', [user]);
  const canManageRecommendationState = useMemo(() => {
    const role = (userRole || '').toUpperCase();
    return ['COMPANY_ADMIN', 'CONTENT_CREATOR', 'SUPER_ADMIN'].includes(role);
  }, [userRole]);
  const canSeeDetectedOpportunities = useMemo(() => {
    const role = (userRole || '').toUpperCase();
    return ['COMPANY_ADMIN', 'CONTENT_CREATOR', 'CONTENT_MANAGER', 'SUPER_ADMIN'].includes(role);
  }, [userRole]);
  const canGenerateDetectedPlaybook = useMemo(() => {
    const role = (userRole || '').toUpperCase();
    return ['COMPANY_ADMIN', 'CONTENT_MANAGER'].includes(role);
  }, [userRole]);
  const canGroupRecommendations = useMemo(() => {
    const role = (userRole || '').toUpperCase();
    return ['COMPANY_ADMIN', 'CONTENT_MANAGER'].includes(role);
  }, [userRole]);
  const recommendedThisWeek = useMemo(() => {
    const withPriority = detectedOpportunities.map((item) => {
      const score = typeof item.priority_score === 'number' ? item.priority_score : 0;
      const bucket = score >= 0.6 ? 'High' : score >= 0.35 ? 'Medium' : 'Low';
      return { ...item, priority_bucket: bucket };
    });
    const sortFn = (a: any, b: any) => {
      if (b.priority_score !== a.priority_score) return b.priority_score - a.priority_score;
      const aMomentum = a.trend_classification === 'Momentum' ? 1 : 0;
      const bMomentum = b.trend_classification === 'Momentum' ? 1 : 0;
      return bMomentum - aMomentum;
    };
    const high = withPriority.filter((item) => item.priority_bucket === 'High').sort(sortFn);
    const medium = withPriority.filter((item) => item.priority_bucket === 'Medium').sort(sortFn);
    const selected = [...high, ...medium].slice(0, 3);
    return selected;
  }, [detectedOpportunities]);
  const detectedTopicSources = useMemo(() => {
    const map = new Map<string, Set<string>>();
    detectedOpportunities.forEach((item) => {
      const key = String(item.topic || '').toLowerCase().trim();
      if (!key) return;
      if (!map.has(key)) {
        map.set(key, new Set());
      }
      if (item.source) {
        map.get(key)?.add(String(item.source));
      }
    });
    return map;
  }, [detectedOpportunities]);
  const trendExplanationMap = useMemo(() => {
    const map = new Map<string, string[]>();
    const explanations = engineResult?.chat_meta?.trend_explanations || [];
    explanations.forEach((entry) => {
      const key = entry.topic?.trim().toLowerCase();
      if (!key || map.has(key)) return;
      map.set(key, entry.explanations || []);
    });
    return map;
  }, [engineResult?.chat_meta?.trend_explanations]);

  // SECURITY: clear all server-fetched state when the authenticated identity
  // changes. Without this, fetched data (engine results, recommendations,
  // detected opportunities, previews, etc.) from a previous session can remain
  // visible after a sign-out → sign-in in the same tab.
  const previousUserIdRef = useRef<string | null>(null);
  useEffect(() => {
    const currentUserId = user?.userId ?? null;
    const previousUserId = previousUserIdRef.current;
    if (previousUserId && previousUserId !== currentUserId) {
      setEngineResult(null);
      setCampaigns([]);
      setSelectedCampaignId('');
      setSelectedCampaignName('');
      setCampaignIdLocked(false);
      setAutoGenerated(false);
      setLastRefresh(null);
      setLastRefreshSource(null);
      setRecommendationStates({});
      setRecommendationDetails({});
      setRecommendationSummaries({});
      setRecommendationBySnapshot({});
      setDetectedOpportunities([]);
      setDismissedOpportunities(new Set());
      setDetectedPlaybooks({});
      setDetectedPlaybookLoading({});
      setDetectedPlaybookOpen(new Set());
      setDetectedReasoningOpen(new Set());
      setPreviewData(null);
      setPreviewRecommendationId(null);
      setPreviewSnapshotHash(null);
      setPreviewPriorityBucket(null);
      setPreviewCurrentState(null);
      setPreviewModalOpen(false);
      setSelectedRecommendations(new Set());
      setGroupAssignments({});
      setGroupNames({});
      setGroupPreview(null);
      setGroupPreviewOpen(false);
      setEngineOverrides({});
      setErrorMessage(null);
      setStateError(null);
      setDetectedError(null);
    }
    previousUserIdRef.current = currentUserId;
  }, [user?.userId]);

  // Sync URL params when router is ready (e.g. opening from Content Architect "Open recommendation cards" link)
  useEffect(() => {
    if (!router.isReady) return;
    const query = router.query as Record<string, string | string[] | undefined>;
    const queryCompanyId = typeof query.companyId === 'string' ? query.companyId.trim() : '';
    const queryTab = typeof query.tab === 'string' ? query.tab.toUpperCase() : '';
    const queryCampaignId = typeof query.campaignId === 'string' ? query.campaignId.trim() : '';
    const queryBlogId = typeof query.blog_id === 'string' ? query.blog_id.trim() : '';
    if (queryCompanyId && selectedCompanyId !== queryCompanyId) {
      setSelectedCompanyId(queryCompanyId);
    }
    if (queryTab && ['TREND', 'LEAD', 'PULSE'].includes(queryTab)) {
      setActiveOpportunityTab(queryTab);
    }
    if (queryCampaignId) {
      setSelectedCampaignId(queryCampaignId);
      setCampaignIdLocked(true);
      if (typeof window !== 'undefined') {
        setUserScopedLocalStorage('selected_campaign_id', user?.userId ?? null, queryCampaignId);
      }
    }
    // Blog → Campaign flow: pre-fill assist panel with the originating blog
    if (queryBlogId) {
      setPrefillBlogId(queryBlogId);
      setActiveOpportunityTab('TREND');
    }
  }, [router.isReady, router.query.companyId, router.query.tab, router.query.campaignId, router.query.blog_id, user?.userId]);

  useEffect(() => {
    if (!router.isReady) return;
    if (activeOpportunityTab !== 'LEAD' && activeOpportunityTab !== 'PULSE') return;
    const intelTab = activeOpportunityTab === 'LEAD' ? 'active-leads' : 'market-pulse';
    void router.replace(`/dashboard?tab=intelligence&intelTab=${intelTab}`);
  }, [activeOpportunityTab, router]);

  useEffect(() => {
    if (!selectedCompanyId) {
      setCampaigns([]);
      setSelectedCampaignId('');
      setSelectedCampaignName('');
      return;
    }
    // Do not overwrite campaign from URL when opened via Content Architect link (campaignIdLocked)
    if (campaignIdLocked) return;
    const stored = typeof window !== 'undefined'
      ? getUserScopedLocalStorage('selected_campaign_id', user?.userId ?? null) || ''
      : '';
    if (stored && stored !== selectedCampaignId) {
      setSelectedCampaignId(stored);
    }
  }, [selectedCompanyId, campaignIdLocked, user?.userId]);

  useEffect(() => {
    if (!selectedCompanyId || !selectedCampaignId) {
      setDetectedOpportunities([]);
      setDismissedOpportunities(new Set());
      return;
    }
    fetchDetectedOpportunities();
  }, [selectedCompanyId, selectedCampaignId, canSeeDetectedOpportunities]);

  const toggleApiSelection = (apiId: string) => {
    setSelectedApiIds((prev) =>
      prev.includes(apiId) ? prev.filter((id) => id !== apiId) : [...prev, apiId]
    );
  };

  useEffect(() => {
    if (!selectedCompanyId) return;
    const loadCampaigns = async () => {
      setIsCampaignLoading(true);
      try {
        const response = await fetchWithAuth(`/api/campaigns?companyId=${encodeURIComponent(selectedCompanyId)}`);
        if (!response.ok) {
          throw new Error('Failed to load campaigns');
        }
        const data = await response.json();
        const list = (data.campaigns || []).map((item: any) => ({
          id: item.id,
          name: item.name || `Campaign ${item.id}`,
          status: item.status || 'planning',
        }));
        setCampaigns(list);
        const matched = list.find((item) => item.id === selectedCampaignId);
        if (matched) {
          setSelectedCampaignName(matched.name);
        } else if (!campaignIdLocked) {
          setSelectedCampaignId('');
          setSelectedCampaignName('');
        }
      } catch (error) {
        console.error('Unable to load campaigns');
        setCampaigns([]);
      } finally {
        setIsCampaignLoading(false);
      }
    };
    loadCampaigns();
  }, [selectedCompanyId, campaignIdLocked]);

  const handleOpportunityPromote = async (opportunityId: string) => {
    if (!selectedCompanyId) return;
    const res = await fetchWithAuth(`/api/opportunities/${opportunityId}/action`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ action: 'PROMOTED', companyId: selectedCompanyId }),
    });
    if (!res.ok) {
      const err = await res.json().catch(() => ({}));
      const message = err?.error || 'Failed to promote';
      const e = new Error(message) as Error & { status?: number };
      e.status = res.status;
      throw e;
    }
    const data = await res.json();
    const campaignId = data?.campaignId ?? data?.campaign_id;
    if (campaignId) {
      const params = new URLSearchParams({ companyId: selectedCompanyId });
      window.location.href = `/campaign-details/${campaignId}?${params.toString()}`;
    }
  };

  const handleOpportunityAction = async (
    opportunityId: string,
    action: string,
    opts?: { scheduled_for?: string }
  ) => {
    if (!selectedCompanyId) {
      throw new Error('companyId required');
    }
    const res = await fetchWithAuth(`/api/opportunities/${opportunityId}/action`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ action, companyId: selectedCompanyId, ...opts }),
    });
    if (!res.ok) {
      const err = await res.json().catch(() => ({}));
      throw new Error(err?.error || 'Action failed');
    }
  };

  useEffect(() => {
    const loadApiDefaults = async () => {
      if (!selectedCompanyId) {
        setAvailableApis([]);
        setSelectedApiIds([]);
        return;
      }
      try {
        setIsApiLoading(true);
        const response = await fetchWithAuth(
          `/api/external-apis/access?companyId=${encodeURIComponent(selectedCompanyId)}`
        );
        if (!response.ok) {
          setAvailableApis([]);
          setSelectedApiIds([]);
          return;
        }
        const data = await response.json();
        setAvailableApis(data.availableApis || []);
        setSelectedApiIds(Array.isArray(data.companyDefaultApis) ? data.companyDefaultApis : []);
      } catch {
        setAvailableApis([]);
        setSelectedApiIds([]);
      } finally {
        setIsApiLoading(false);
      }
    };
    loadApiDefaults();
  }, [selectedCompanyId]);

  // User-initiated only: no automatic recommendation generation when campaign is selected.
  // Recommendations are generated only via explicit "Generate".

  useEffect(() => {
    if (!selectedCampaignId) return;
    const match = campaigns.find((campaign) => campaign.id === selectedCampaignId);
    if (match) {
      setSelectedCampaignName(match.name);
      if (typeof window !== 'undefined') {
        setUserScopedLocalStorage('selected_campaign_id', user?.userId ?? null, selectedCampaignId);
      }
      console.log('SELECTED_CAMPAIGN', {
        companyId: selectedCompanyId,
        campaignId: selectedCampaignId,
        campaignName: match.name,
      });
    }
  }, [selectedCampaignId, campaigns, selectedCompanyId, user?.userId]);

  const generateRecommendations = async (manualContext?: {
    type?: string;
    topic?: string;
    narrative?: string;
    objective?: string;
    platform_preferences?: string[];
    source?: string;
  }): Promise<RecommendationEngineResult | null> => {
    if (!selectedCompanyId) {
      setErrorMessage('Please select a company first.');
      return null;
    }
    try {
      setIsLoading(true);
      setErrorMessage(null);
      setExpandedTrendKey(null);
      const response = await fetchWithAuth('/api/recommendations/generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          companyId: selectedCompanyId,
          campaignId: selectedCampaignId || null,
          simulate: simulateScenarios,
          chat: true,
          selected_api_ids: selectedApiIds,
          ...(manualContext ? { manual_context: manualContext } : {}),
        }),
      });
      if (!response.ok) {
        const errBody = await response.json().catch(() => ({}));
        const detail = errBody?.detail ?? errBody?.error;
        throw new Error(typeof detail === 'string' ? detail : 'Failed to generate recommendations');
      }
      const data = await response.json();
      setEngineResult(data);
      setLastRefresh(new Date().toLocaleString());
      setLastRefreshSource(
        manualContext?.type === 'opportunity'
          ? 'opportunity'
          : manualContext?.type === 'detected_opportunity'
          ? 'detected_opportunity'
          : 'manual'
      );
      return data;
    } catch (error) {
      console.error('Error generating recommendations:', error);
      setErrorMessage(error instanceof Error ? error.message : 'Failed to generate recommendations.');
      return null;
    } finally {
      setIsLoading(false);
    }
  };

  const refreshRecommendations = async () => {
    if (!selectedCompanyId) {
      setErrorMessage('Please select a company first.');
      return;
    }
    if (!hasPermission('GENERATE_RECOMMENDATIONS')) {
      setErrorMessage('You do not have permission to refresh recommendations.');
      return;
    }
    try {
      setIsLoading(true);
      setErrorMessage(null);
      const response = await fetchWithAuth('/api/recommendations/refresh', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          mode: 'company',
          companyId: selectedCompanyId,
        }),
      });
      if (!response.ok) {
        const data = await response.json().catch(() => null);
        const message =
          data?.error ||
          (response.status ? `Failed to refresh recommendations (${response.status}).` : null) ||
          'Failed to refresh recommendations.';
        throw new Error(message);
      }
      setLastRefresh(new Date().toLocaleString());
      setLastRefreshSource('profile_update');
      await generateRecommendations();
    } catch (error) {
      console.error('Error refreshing recommendations:', error);
      setErrorMessage(error instanceof Error ? error.message : 'Failed to refresh recommendations.');
      setIsLoading(false);
    }
  };

  const fetchDetectedOpportunities = async () => {
    if (!selectedCompanyId || !selectedCampaignId || !canSeeDetectedOpportunities) return;
    try {
      setDetectedLoading(true);
      setDetectedError(null);
      const params = new URLSearchParams({
        companyId: selectedCompanyId,
        campaignId: selectedCampaignId,
      });
      const response = await fetch(`/api/recommendations/detected-opportunities?${params.toString()}`);
      const data = await response.json().catch(() => ({}));
      if (!response.ok) {
        const msg = data?.error || data?.message || `Failed to load detected opportunities (${response.status})`;
        console.error('Detected opportunities API error:', response.status, msg, data);
        setDetectedError(msg);
        setDetectedOpportunities([]);
        return;
      }
      setDetectedOpportunities(Array.isArray(data?.opportunities) ? data.opportunities : []);
    } catch (error) {
      console.error('Error loading detected opportunities:', error);
      setDetectedError('Failed to load detected opportunities.');
      setDetectedOpportunities([]);
    } finally {
      setDetectedLoading(false);
    }
  };

  const fetchStateMap = async () => {
    if (!selectedCompanyId) return;
    try {
      const snapshotHashes =
        engineResult?.trends_used?.map((t) => (t as { snapshot_hash?: string }).snapshot_hash).filter(Boolean) || [];
      const params = new URLSearchParams({ companyId: selectedCompanyId });
      if (snapshotHashes.length > 0) {
        params.set('snapshot_hashes', snapshotHashes.join(','));
      }
      const response = await fetch(`/api/recommendations/state-map?${params.toString()}`);
      if (!response.ok) {
        setRecommendationStates({});
        setRecommendationDetails({});
        setRecommendationBySnapshot({});
        return;
      }
      const data = await response.json();
      setRecommendationStates(data?.states || {});
      setRecommendationDetails(data?.details || {});
      setRecommendationSummaries(data?.summaries || {});
      setRecommendationBySnapshot(data?.recommendations || {});
    } catch (error) {
      console.error('Error loading recommendation states:', error);
      setRecommendationStates({});
      setRecommendationDetails({});
      setRecommendationSummaries({});
      setRecommendationBySnapshot({});
    }
  };

  const resolveRecommendationIdBySnapshot = async (snapshotHash: string) => {
    if (recommendationBySnapshot[snapshotHash]) {
      return recommendationBySnapshot[snapshotHash];
    }
    if (!selectedCompanyId) return null;
    try {
      const params = new URLSearchParams({
        companyId: selectedCompanyId,
        snapshot_hashes: snapshotHash,
      });
      const response = await fetch(`/api/recommendations/state-map?${params.toString()}`);
      if (!response.ok) return null;
      const data = await response.json();
      const mapping = data?.recommendations || {};
      if (mapping) {
        setRecommendationStates((prev) => ({ ...prev, ...(data?.states || {}) }));
        setRecommendationDetails((prev) => ({ ...prev, ...(data?.details || {}) }));
        setRecommendationSummaries((prev) => ({ ...prev, ...(data?.summaries || {}) }));
        setRecommendationBySnapshot((prev) => ({ ...prev, ...mapping }));
      }
      return mapping?.[snapshotHash] || null;
    } catch (error) {
      console.error('Error resolving recommendation id:', error);
      return null;
    }
  };

  const evaluateDetectedOpportunity = async (
    opportunity: DetectedOpportunity,
    options?: { state?: 'shortlisted' | 'discarded' }
  ) => {
    const data = await generateRecommendations({
      type: 'detected_opportunity',
      topic: opportunity.topic,
      source: opportunity.source || undefined,
    });
    if (!data) return;
    const match = (data.trends_used || []).find(
      (trend: any) => String(trend.topic || '').toLowerCase() === opportunity.topic.toLowerCase()
    );
    const snapshotHash = (match as { snapshot_hash?: string } | undefined)?.snapshot_hash;
    if (snapshotHash && options?.state) {
      const recommendationId = await resolveRecommendationIdBySnapshot(String(snapshotHash));
      if (recommendationId) {
        await updateRecommendationState(recommendationId, options.state);
      }
    }
  };

  const openPreviewForDetectedOpportunity = async (opportunity: DetectedOpportunity) => {
    if (!selectedCompanyId) {
      setPreviewError('Select a company to preview.');
      return;
    }
    try {
      setPreviewError(null);
      setPreviewLoading(true);
      setPreviewModalOpen(true);
      setPreviewRecommendationId(null);
      setPreviewSnapshotHash(null);
      setPreviewPriorityBucket(null);
      setPreviewCurrentState(null);
      setPreviewOpinionNote('');
      setPreviewConfidenceRating('');
      setPreviewConfidence(null);
      setPreviewContentFrequency(null);
      const previewResponse = await fetch(`/api/recommendations/manual/preview-strategy`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          company_id: selectedCompanyId,
          preview_context: {
            topic: opportunity.topic,
            source: opportunity.source || null,
            category: opportunity.category || null,
          },
        }),
      });
      if (!previewResponse.ok) {
        throw new Error('Failed to generate preview');
      }
      const data = await previewResponse.json();
      setPreviewData(data?.preview || null);
      setPreviewConfidence(typeof data?.confidence === 'number' ? data.confidence : null);
      setPreviewContentFrequency(data?.content_frequency ?? null);
    } catch (error) {
      console.error('Error generating detected preview:', error);
      setPreviewError('Failed to generate preview.');
    } finally {
      setPreviewLoading(false);
    }
  };

  const dismissDetectedOpportunity = (key: string) => {
    setDismissedOpportunities((prev) => new Set([...Array.from(prev), key]));
  };

  const toggleDetectedReasoning = (key: string) => {
    setDetectedReasoningOpen((prev) => {
      const next = new Set(prev);
      if (next.has(key)) {
        next.delete(key);
      } else {
        next.add(key);
      }
      return next;
    });
  };

  const toggleDetectedPlaybook = async (key: string, opportunity: DetectedOpportunity) => {
    if (!canGenerateDetectedPlaybook) return;
    if (detectedPlaybooks[key]) {
      setDetectedPlaybookOpen((prev) => {
        const next = new Set(prev);
        if (next.has(key)) {
          next.delete(key);
        } else {
          next.add(key);
        }
        return next;
      });
      return;
    }
    try {
      setDetectedPlaybookLoading((prev) => ({ ...prev, [key]: true }));
      let previewResponse: Response | null = null;
      const match = (engineResult?.trends_used || []).find(
        (trend: any) => String(trend.topic || '').toLowerCase() === opportunity.topic.toLowerCase()
      );
      const snapshotHash = (match as { snapshot_hash?: string } | undefined)?.snapshot_hash;
      const recommendationId = snapshotHash ? recommendationBySnapshot[snapshotHash] : null;
      if (recommendationId) {
        previewResponse = await fetch(
          `/api/recommendations/${encodeURIComponent(recommendationId)}/preview-strategy`,
          {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
          }
        );
      } else {
        previewResponse = await fetch(`/api/recommendations/manual/preview-strategy`, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            company_id: selectedCompanyId,
            preview_context: {
              topic: opportunity.topic,
              category: opportunity.category || null,
              source: opportunity.source || null,
              priority_bucket: opportunity.priority_score ?? null,
              trend_classification: opportunity.trend_classification || null,
            },
          }),
        });
      }
      if (!previewResponse?.ok) {
        throw new Error('Failed to generate playbook');
      }
      const data = await previewResponse.json();
      setDetectedPlaybooks((prev) => ({ ...prev, [key]: data?.preview || null }));
      setDetectedPlaybookOpen((prev) => new Set([...Array.from(prev), key]));
    } catch (error) {
      console.error('Error generating playbook:', error);
    } finally {
      setDetectedPlaybookLoading((prev) => ({ ...prev, [key]: false }));
    }
  };

  const updateRecommendationState = async (recommendationId: string, state: string) => {
    if (!recommendationId) return;
    try {
      setStateError(null);
      const response = await fetch(`/api/recommendations/${recommendationId}/state`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ state }),
      });
      if (!response.ok) {
        setStateError('Failed to update recommendation state.');
        return;
      }
      await fetchStateMap();
    } catch (error) {
      console.error('Error updating recommendation state:', error);
      setStateError('Failed to update recommendation state.');
    }
  };

  const handleCreateCampaignFromRecommendation = async (recommendationId?: string) => {
    if (!recommendationId) {
      setErrorMessage('Recommendation ID not available.');
      return;
    }
    try {
      setIsLoading(true);
      const response = await fetch(`/api/recommendations/${recommendationId}/create-campaign`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ durationWeeks: 12 }),
      });
      if (!response.ok) {
        throw new Error('Failed to create campaign');
      }
      const data = await response.json();
      if (data?.campaign_id) {
        const qs = new URLSearchParams();
        if (selectedCompanyId) qs.set('companyId', selectedCompanyId);
        qs.set('fromRecommendation', '1');
        qs.set('recommendationId', recommendationId);
        window.location.href = `/campaign-details/${data.campaign_id}?${qs.toString()}`;
      }
    } catch (error) {
      console.error('Error creating campaign:', error);
      setErrorMessage('Failed to create campaign.');
    } finally {
      setIsLoading(false);
    }
  };

  const handlePreparePlanFromRecommendation = async (
    recommendationId?: string,
    _snapshotHash?: string | null,
    options?: { draft?: boolean; priorityBucket?: string }
  ) => {
    if (!recommendationId) {
      setErrorMessage('Recommendation context not available.');
      return;
    }
    try {
      setDraftError(null);
      setIsLoading(true);
      const response = await fetch(`/api/recommendations/${recommendationId}/create-campaign`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          durationWeeks: options?.draft ? 6 : 12,
          priority_bucket: options?.priorityBucket ?? null,
        }),
      });
      if (!response.ok) {
        throw new Error('Failed to create campaign from recommendation');
      }
      const data = await response.json();
      if (data?.campaign_id) {
        const qs = new URLSearchParams();
        if (selectedCompanyId) qs.set('companyId', selectedCompanyId);
        qs.set('fromRecommendation', '1');
        qs.set('recommendationId', recommendationId);
        window.location.href = `/campaign-details/${data.campaign_id}?${qs.toString()}`;
      }
    } catch (error) {
      console.error('Error creating plan from recommendation:', error);
      setDraftError('Failed to create plan from recommendation.');
    } finally {
      setIsLoading(false);
    }
  };

  const openPreviewForRecommendation = async (
    recommendationId?: string,
    snapshotHash?: string | null,
    currentState?: string | null,
    priorityBucket?: string | null
  ) => {
    if (!recommendationId || !snapshotHash) {
      setDraftError('Preview unavailable for this recommendation.');
      return;
    }
    try {
      setPreviewError(null);
      setPreviewLoading(true);
      setPreviewModalOpen(true);
      setPreviewRecommendationId(recommendationId);
      setPreviewSnapshotHash(snapshotHash);
      setPreviewPriorityBucket(priorityBucket || null);
      setPreviewCurrentState(currentState || null);
      setPreviewOpinionNote('');
      setPreviewConfidenceRating('');
      setPreviewConfidence(null);
      setPreviewContentFrequency(null);
      const response = await fetch(`/api/recommendations/${recommendationId}/preview-strategy`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
      });
      if (!response.ok) {
        throw new Error('Failed to generate preview');
      }
      const data = await response.json();
      setPreviewData(data?.preview || null);
      setPreviewConfidence(typeof data?.confidence === 'number' ? data.confidence : null);
      setPreviewContentFrequency(data?.content_frequency ?? null);
      if (data?.snapshot_hash) {
        setPreviewSnapshotHash(String(data.snapshot_hash));
      }
      setPreviewRecommendationId(String(data?.recommendation_id || recommendationId));
    } catch (error) {
      console.error('Error generating preview:', error);
      setPreviewError('Failed to generate preview.');
    } finally {
      setPreviewLoading(false);
    }
  };

  const regeneratePreview = async () => {
    if (!previewRecommendationId) return;
    try {
      setPreviewError(null);
      setPreviewLoading(true);
      const response = await fetch(
        `/api/recommendations/${previewRecommendationId}/preview-strategy`,
        {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ preview_overrides: previewData || null }),
        }
      );
      if (!response.ok) {
        throw new Error('Failed to regenerate preview');
      }
      const data = await response.json();
      setPreviewData(data?.preview || null);
      setPreviewConfidence(typeof data?.confidence === 'number' ? data.confidence : null);
      setPreviewContentFrequency(data?.content_frequency ?? null);
    } catch (error) {
      console.error('Error regenerating preview:', error);
      setPreviewError('Failed to regenerate preview.');
    } finally {
      setPreviewLoading(false);
    }
  };

  const savePreviewOpinion = async () => {
    if (!previewRecommendationId || !previewCurrentState) {
      return;
    }
    try {
      const response = await fetch(`/api/recommendations/${previewRecommendationId}/state`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          state: previewCurrentState,
          opinion_note: previewOpinionNote || null,
          confidence_rating:
            typeof previewConfidenceRating === 'number' ? previewConfidenceRating : null,
        }),
      });
      if (!response.ok) {
        throw new Error('Failed to save opinion');
      }
      await fetchStateMap();
    } catch (error) {
      console.error('Error saving opinion:', error);
    }
  };

  const acceptPreviewAndDraftPlan = async () => {
    if (!previewRecommendationId || !previewSnapshotHash) {
      setPreviewError('Preview context missing.');
      return;
    }
    try {
      setPreviewError(null);
      setPreviewLoading(true);
      const response = await fetch(`/api/recommendations/${previewRecommendationId}/state`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          state: 'shortlisted',
          opinion_note: previewOpinionNote || null,
          confidence_rating:
            typeof previewConfidenceRating === 'number' ? previewConfidenceRating : null,
          accept_preview: true,
        }),
      });
      if (!response.ok) {
        throw new Error('Failed to accept preview');
      }
      if (typeof window !== 'undefined' && previewData) {
        window.sessionStorage.setItem(
          `recommendation_preview_${previewSnapshotHash}`,
          JSON.stringify({
            ...previewData,
            recommendation_id: previewRecommendationId,
            snapshot_hash: previewSnapshotHash,
            confidence: previewConfidence,
            content_frequency: previewContentFrequency,
          })
        );
      }
      setPreviewModalOpen(false);
      await handlePreparePlanFromRecommendation(previewRecommendationId, previewSnapshotHash, {
        draft: true,
        priorityBucket: previewPriorityBucket || undefined,
      });
    } catch (error) {
      console.error('Error accepting preview:', error);
      setPreviewError('Failed to accept preview.');
    } finally {
      setPreviewLoading(false);
    }
  };

  const handleManualSubmit = async () => {
    if (!manualTopic.trim() && !manualNarrative.trim() && !manualObjective.trim()) {
      setErrorMessage('Enter a topic, narrative, or objective to continue.');
      return;
    }
    try {
      setIsSubmittingManual(true);
      await generateRecommendations({
        type: 'opportunity',
        topic: manualTopic.trim() || undefined,
        narrative: manualNarrative.trim() || undefined,
        objective: manualObjective.trim() || undefined,
        platform_preferences: manualPlatformPreference
          .split(',')
          .map((value) => value.trim())
          .filter(Boolean),
      });
    } finally {
      setIsSubmittingManual(false);
    }
  };

  const toggleRecommendationSelection = (snapshotHash?: string | null) => {
    if (!snapshotHash) return;
    setSelectedRecommendations((prev) => {
      const next = new Set(prev);
      if (next.has(snapshotHash)) {
        next.delete(snapshotHash);
      } else {
        next.add(snapshotHash);
      }
      return next;
    });
  };

  const getSelectedRecommendationPayload = () => {
    const selected = Array.from(selectedRecommendations);
    return (engineResult?.trends_used || [])
      .filter((trend: any) => selected.includes(trend.snapshot_hash))
      .map((trend: any) => {
        const snapshotHash = trend.snapshot_hash;
        const recommendationId = snapshotHash ? recommendationBySnapshot[snapshotHash] : undefined;
        const summary = recommendationId ? recommendationSummaries[recommendationId] : undefined;
        return {
          id: recommendationId || null,
          snapshot_hash: snapshotHash,
          topic: trend.topic,
          priority_score: summary?.priority_score ?? null,
          trend_classification: summary?.priority_bucket ? summary.priority_bucket : null,
          category: trend.category ?? null,
        };
      })
      .filter((item: any) => item.snapshot_hash);
  };

  const openGroupPreview = async () => {
    if (!selectedCompanyId) return;
    const selectedPayload = getSelectedRecommendationPayload();
    if (selectedPayload.length < 2) return;
    try {
      setGroupPreviewError(null);
      setGroupPreviewLoading(true);
      const response = await fetch('/api/recommendations/group-preview', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          // withRBAC resolves the company from `companyId`; the handler operates on
          // `company_id`. Send both so the RBAC wrapper and the route's own tenant
          // guard authorize the SAME company (RECOMMENDATIONS-SEC-001).
          companyId: selectedCompanyId,
          company_id: selectedCompanyId,
          selected_recommendations: selectedPayload,
        }),
      });
      if (!response.ok) {
        throw new Error('Failed to generate grouping preview');
      }
      const data = await response.json();
      setGroupPreview(data);
      const assignments: Record<string, string> = {};
      const names: Record<string, string> = {};
      (data?.groups || []).forEach((group: any) => {
        const groupId = group.group_id || `group_${Math.random().toString(36).slice(2, 8)}`;
        names[groupId] = group.theme_name || 'Group';
        (group.recommendations || []).forEach((hash: string) => {
          assignments[hash] = groupId;
        });
      });
      selectedPayload.forEach((item: any) => {
        if (!assignments[item.snapshot_hash]) {
          const fallback = Object.keys(names)[0] || `group_${Math.random().toString(36).slice(2, 8)}`;
          if (!names[fallback]) names[fallback] = 'Group';
          assignments[item.snapshot_hash] = fallback;
        }
      });
      setGroupAssignments(assignments);
      setGroupNames(names);
      setGroupPreviewOpen(true);
    } catch (error) {
      console.error('Group preview failed', error);
      setGroupPreviewError('Failed to generate grouping preview.');
      setGroupPreviewOpen(true);
    } finally {
      setGroupPreviewLoading(false);
    }
  };

  const addGroup = () => {
    const groupId = `group_${Math.random().toString(36).slice(2, 8)}`;
    setGroupNames((prev) => ({ ...prev, [groupId]: 'New Group' }));
  };

  const removeEmptyGroup = (groupId: string) => {
    const hasMembers = Object.values(groupAssignments).some((id) => id === groupId);
    if (hasMembers) return;
    setGroupNames((prev) => {
      const next = { ...prev };
      delete next[groupId];
      return next;
    });
  };

  const confirmGroupedCampaign = async () => {
    if (!selectedCompanyId) return;
    const selectedPayload = getSelectedRecommendationPayload();
    if (selectedPayload.length < 2) return;
    try {
      setIsCreatingGroupedCampaign(true);
      const grouped: Record<string, string[]> = {};
      Object.entries(groupAssignments).forEach(([hash, groupId]) => {
        if (!grouped[groupId]) grouped[groupId] = [];
        grouped[groupId].push(hash);
      });
      const groups = Object.entries(grouped).map(([groupId, hashes]) => ({
        group_id: groupId,
        theme_name: groupNames[groupId] || 'Group',
        recommendations: hashes,
        rationale:
          groupPreview?.groups?.find((grp: any) => grp.group_id === groupId)?.rationale || null,
      }));
      const response = await fetch('/api/recommendations/create-campaign-from-group', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          // withRBAC resolves the company from `companyId`; the handler operates on
          // `company_id`. Send both so the RBAC wrapper and the route's own tenant
          // guard authorize the SAME company (RECOMMENDATIONS-SEC-001).
          companyId: selectedCompanyId,
          company_id: selectedCompanyId,
          selected_recommendations: selectedPayload,
          groups,
          suggested_platform_mix: groupPreview?.suggested_platform_mix || [],
          suggested_frequency: groupPreview?.suggested_frequency || {},
        }),
      });
      if (!response.ok) {
        throw new Error('Failed to create grouped campaign');
      }
      const data = await response.json();
      if (typeof window !== 'undefined' && data?.campaign_id) {
        window.sessionStorage.setItem(
          `recommendation_grouping_${data.campaign_id}`,
          JSON.stringify({
            groups,
            suggested_platform_mix: groupPreview?.suggested_platform_mix || [],
            suggested_frequency: groupPreview?.suggested_frequency || {},
          })
        );
      }
      setSelectedRecommendations(new Set());
      setGroupPreviewOpen(false);
      if (data?.campaign_id) {
        const params = selectedCompanyId ? `?companyId=${encodeURIComponent(selectedCompanyId)}&grouped=1` : '?grouped=1';
        window.location.href = `/campaign-details/${data.campaign_id}${params}`;
      }
    } catch (error) {
      console.error('Grouped campaign failed', error);
      setGroupPreviewError('Failed to create grouped campaign.');
    } finally {
      setIsCreatingGroupedCampaign(false);
    }
  };
  const confidencePercent = engineResult?.confidence_score ?? 0;
  const confidenceRatio = Math.max(0, Math.min(1, confidencePercent / 100));
  const confidenceMeta = getConfidenceLabel(confidenceRatio);
  const noExternalSignals = hasNoExternalSignals(engineResult?.omnivyra_metadata?.placeholders);
  const showNoveltyWarning = shouldShowNoveltyWarning(engineResult?.novelty_score);
  const trendCounts = buildTrendSourceCounts(engineResult?.trends_used || []);
  const trendSourceLegend = TREND_SOURCE_LEGEND;
  const omnivyraStatus = engineResult?.omnivyra_status;
  useEffect(() => {
    if (!selectedCompanyId || !engineResult?.trends_used?.length) {
      setRecommendationStates({});
      setRecommendationDetails({});
      setRecommendationSummaries({});
      setRecommendationBySnapshot({});
      return;
    }
    fetchStateMap();
  }, [selectedCompanyId, engineResult?.trends_used]);
  const omnivyraStatusColor =
    omnivyraStatus?.status === 'healthy'
      ? 'bg-green-100 text-green-700'
      : omnivyraStatus?.status === 'degraded'
      ? 'bg-yellow-100 text-yellow-700'
      : omnivyraStatus?.status === 'down'
      ? 'bg-red-100 text-red-700'
      : 'bg-gray-100 text-gray-700';

  const showLoadingState = isCompanyLoading;
  const showNoCompanyState = !isCompanyLoading && !selectedCompanyId;

  const setEngineOverride = (engineType: string, value: string) => {
    setEngineOverrides((prev) => ({ ...prev, [engineType]: value }));
  };


  return {
    acceptPreviewAndDraftPlan,
    activeOpportunityTab,
    activeWorkspaceTab,
    addGroup,
    autoGenerated,
    availableApis,
    campaignIdLocked,
    campaigns,
    canGenerateDetectedPlaybook,
    canGroupRecommendations,
    canManageRecommendationState,
    canSeeDetectedOpportunities,
    companies,
    confidenceMeta,
    confidencePercent,
    confidenceRatio,
    confirmGroupedCampaign,
    detectedError,
    detectedLoading,
    detectedOpportunities,
    detectedPlaybookLoading,
    detectedPlaybookOpen,
    detectedPlaybooks,
    detectedReasoningOpen,
    detectedTopicSources,
    dismissDetectedOpportunity,
    dismissedOpportunities,
    draftError,
    engineOverrides,
    engineResult,
    errorMessage,
    evaluateDetectedOpportunity,
    expandedTrendKey,
    fetchDetectedOpportunities,
    fetchStateMap,
    generateRecommendations,
    generatorModalTarget,
    getSelectedRecommendationPayload,
    groupAssignments,
    groupNames,
    groupPreview,
    groupPreviewError,
    groupPreviewLoading,
    groupPreviewOpen,
    groupSortMode,
    handleCreateCampaignFromRecommendation,
    handleManualSubmit,
    handleOpportunityAction,
    handleOpportunityPromote,
    handlePreparePlanFromRecommendation,
    hasPermission,
    intelligentMixContext,
    isAdmin,
    isApiLoading,
    isAuthenticated,
    isCampaignLoading,
    isCompanyLoading,
    isCreatingGroupedCampaign,
    isLoading,
    isSubmittingManual,
    lastRefresh,
    lastRefreshSource,
    manualNarrative,
    manualObjective,
    manualPlatformPreference,
    manualTopic,
    noExternalSignals,
    omnivyraStatus,
    omnivyraStatusColor,
    openGroupPreview,
    openPreviewForDetectedOpportunity,
    openPreviewForRecommendation,
    opportunityRegions,
    prefillBlogId,
    previewConfidence,
    previewConfidenceRating,
    previewContentFrequency,
    previewCurrentState,
    previewData,
    previewError,
    previewLoading,
    previewModalOpen,
    previewOpinionNote,
    previewPriorityBucket,
    previewRecommendationId,
    previewSnapshotHash,
    recommendationBySnapshot,
    recommendationDetails,
    recommendationStates,
    recommendationSummaries,
    recommendedThisWeek,
    refreshRecommendations,
    regeneratePreview,
    removeEmptyGroup,
    resolveRecommendationIdBySnapshot,
    router,
    savePreviewOpinion,
    selectedApiIds,
    selectedCampaignId,
    selectedCampaignName,
    selectedCompanyId,
    selectedRecommendations,
    setActiveOpportunityTab,
    setActiveWorkspaceTab,
    setAutoGenerated,
    setAvailableApis,
    setCampaignIdLocked,
    setCampaigns,
    setDetectedError,
    setDetectedLoading,
    setDetectedOpportunities,
    setDetectedPlaybookLoading,
    setDetectedPlaybookOpen,
    setDetectedPlaybooks,
    setDetectedReasoningOpen,
    setDismissedOpportunities,
    setDraftError,
    setEngineOverride,
    setEngineOverrides,
    setEngineResult,
    setErrorMessage,
    setExpandedTrendKey,
    setGeneratorModalTarget,
    setGroupAssignments,
    setGroupNames,
    setGroupPreview,
    setGroupPreviewError,
    setGroupPreviewLoading,
    setGroupPreviewOpen,
    setGroupSortMode,
    setIsApiLoading,
    setIsCampaignLoading,
    setIsCreatingGroupedCampaign,
    setIsLoading,
    setIsSubmittingManual,
    setLastRefresh,
    setLastRefreshSource,
    setManualNarrative,
    setManualObjective,
    setManualPlatformPreference,
    setManualTopic,
    setOpportunityRegions,
    setPrefillBlogId,
    setPreviewConfidence,
    setPreviewConfidenceRating,
    setPreviewContentFrequency,
    setPreviewCurrentState,
    setPreviewData,
    setPreviewError,
    setPreviewLoading,
    setPreviewModalOpen,
    setPreviewOpinionNote,
    setPreviewPriorityBucket,
    setPreviewRecommendationId,
    setPreviewSnapshotHash,
    setRecommendationBySnapshot,
    setRecommendationDetails,
    setRecommendationStates,
    setRecommendationSummaries,
    setSelectedApiIds,
    setSelectedCampaignId,
    setSelectedCampaignName,
    setSelectedCompanyId,
    setSelectedRecommendations,
    setSimulateScenarios,
    setSortByPriority,
    setStateError,
    setTrendStrategicIntents,
    showLoadingState,
    showNoCompanyState,
    showNoveltyWarning,
    simulateScenarios,
    sortByPriority,
    stateError,
    toggleApiSelection,
    toggleDetectedPlaybook,
    toggleDetectedReasoning,
    toggleRecommendationSelection,
    trendCounts,
    trendExplanationMap,
    trendSourceLegend,
    trendStrategicIntents,
    updateRecommendationState,
    user,
    userRole,
    viewMode,
  };
}
