import React, { useEffect, useState } from 'react';
import { useRouter } from 'next/router';

type Recommendation = {
  id?: string;
  recommendation_id?: string;
  trend: string;
  category?: string;
  audience?: any;
  geo?: any;
  platforms?: Array<{
    platform: string;
    content_types: string[];
    required_metadata: string[];
  }>;
  promotion_mode: 'organic' | 'paid' | 'mixed';
  effort_score: number;
  expected_reach: number;
  expected_growth: number;
  final_score: number;
  rationale: string;
  title?: string;
  description?: string;
  trend_source?: string;
  trend_source_health?: {
    freshness_score: number;
    reliability_score: number;
  };
  scores?: {
    trend_score: number;
    geo_fit_score: number;
    audience_fit_score?: number;
    category_fit_score?: number;
    source_consensus_score?: number;
    health_multiplier?: number;
    historical_accuracy_score?: number;
    platform_fit_score: number;
    demographic_fit_score: number;
    promotion_fit_score: number;
    effort_score: number;
    final_score: number;
  };
  confidence?: number;
  explanation?: string;
};

export default function RecommendationsPage() {
  const router = useRouter();
  const [recommendations, setRecommendations] = useState<Recommendation[]>([]);
  const [isLoading, setIsLoading] = useState(false);
  const [errorMessage, setErrorMessage] = useState<string | null>(null);
  const [creatingId, setCreatingId] = useState<string | null>(null);
  const [isAdmin, setIsAdmin] = useState(false);
  const [companyIdInput, setCompanyIdInput] = useState<string>('');
  const [campaignIdInput, setCampaignIdInput] = useState<string>('');
  const [campaignIdLocked, setCampaignIdLocked] = useState(false);
  const [autoGenerated, setAutoGenerated] = useState(false);
  const [lastRefresh, setLastRefresh] = useState<string | null>(null);
  const [lastRefreshSource, setLastRefreshSource] = useState<string | null>(null);

  useEffect(() => {
    const queryCampaignId =
      typeof router.query.campaignId === 'string' ? router.query.campaignId : '';
    if (queryCampaignId) {
      setCampaignIdInput(queryCampaignId);
      setCampaignIdLocked(true);
    }
  }, [router.query.campaignId]);

  useEffect(() => {
    const loadAdminStatus = async () => {
      try {
        const response = await fetch('/api/admin/check-super-admin');
        if (!response.ok) return;
        const data = await response.json();
        setIsAdmin(!!data?.isSuperAdmin);
      } catch (error) {
        console.warn('Unable to load admin status');
      }
    };
    loadAdminStatus();
  }, []);

  useEffect(() => {
    const loadCompanyProfile = async () => {
      try {
        const response = await fetch('/api/company-profile');
        if (!response.ok) return;
        const data = await response.json();
        if (data?.profile?.company_id) {
          setCompanyIdInput(data.profile.company_id);
        }
      } catch (error) {
        console.warn('Unable to load company profile context');
      }
    };

    loadCompanyProfile();
  }, []);

  useEffect(() => {
    if (!campaignIdInput || !campaignIdLocked || autoGenerated || isLoading) return;
    setAutoGenerated(true);
    generateRecommendations();
  }, [campaignIdInput, campaignIdLocked, autoGenerated, isLoading]);

  const generateRecommendations = async () => {
    try {
      setIsLoading(true);
      setErrorMessage(null);
      const response = await fetch('/api/recommendations/generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          companyId: companyIdInput || undefined,
          campaignId: campaignIdInput || undefined,
        }),
      });
      if (!response.ok) throw new Error('Failed to generate recommendations');
      const data = await response.json();
      setRecommendations(
        (data.recommendations || []).map((rec: Recommendation) => ({
          ...rec,
          recommendation_id: rec.recommendation_id,
          id: rec.id ?? rec.recommendation_id ?? rec.snapshot_id ?? undefined,
        }))
      );
      setLastRefresh(new Date().toLocaleString());
      setLastRefreshSource('manual');
    } catch (error) {
      console.error('Error generating recommendations:', error);
      setErrorMessage('Failed to generate recommendations.');
    } finally {
      setIsLoading(false);
    }
  };

  const refreshRecommendations = async () => {
    try {
      setIsLoading(true);
      setErrorMessage(null);
      const mode = companyIdInput ? 'company' : 'weekly';
      const response = await fetch('/api/recommendations/refresh', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          mode,
          companyId: companyIdInput || undefined,
        }),
      });
      if (!response.ok) throw new Error('Failed to refresh recommendations');
      setLastRefresh(new Date().toLocaleString());
      setLastRefreshSource(mode === 'weekly' ? 'auto_weekly' : 'profile_update');
      await generateRecommendations();
    } catch (error) {
      console.error('Error refreshing recommendations:', error);
      setErrorMessage('Failed to refresh recommendations.');
      setIsLoading(false);
    }
  };

  const createCampaignFromRecommendation = async (rec: Recommendation) => {
    if (!rec.id) {
      setErrorMessage('Recommendation ID is missing.');
      return;
    }
    try {
      setCreatingId(rec.id);
      setErrorMessage(null);
      const response = await fetch(`/api/recommendations/${rec.id}/create-campaign`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ durationWeeks: 12 }),
      });
      if (!response.ok) throw new Error('Failed to create campaign');
      const data = await response.json();
      if (data?.campaign_id) {
        if (typeof window !== 'undefined') {
          const summaryPayload = {
            recommendation_id: rec.id,
            trend: rec.trend,
            category: rec.category,
            audience: rec.audience,
            geo: rec.geo,
            platforms: rec.platforms,
            promotion_mode: rec.promotion_mode,
          };
          window.sessionStorage.setItem(
            `recommendation_summary_${rec.id}`,
            JSON.stringify(summaryPayload)
          );
        }
        window.location.href = `/campaign-details/${data.campaign_id}?fromRecommendation=true&recommendationId=${encodeURIComponent(
          rec.id
        )}`;
      }
    } catch (error) {
      console.error('Error creating campaign from recommendation:', error);
      setErrorMessage('Failed to create campaign from recommendation.');
    } finally {
      setCreatingId(null);
    }
  };

  const getConfidenceBadge = (confidence?: number) => {
    if (confidence === undefined || confidence === null) return 'bg-gray-200 text-gray-700';
    if (confidence > 75) return 'bg-green-100 text-green-700';
    if (confidence >= 40) return 'bg-yellow-100 text-yellow-700';
    return 'bg-gray-100 text-gray-700';
  };

  const getHealthBadge = (health?: Recommendation['trend_source_health']) => {
    if (!health) return { className: 'bg-gray-100 text-gray-700', label: 'Health: N/A' };
    const combined = health.freshness_score * health.reliability_score;
    if (combined >= 0.75) return { className: 'bg-green-100 text-green-700', label: 'Health: Good' };
    if (combined >= 0.4) return { className: 'bg-yellow-100 text-yellow-700', label: 'Health: Fair' };
    return { className: 'bg-red-100 text-red-700', label: 'Health: Poor' };
  };

  const scoreMeta: Array<{ key: keyof NonNullable<Recommendation['scores']>; label: string; tip: string }> = [
    {
      key: 'trend_score',
      label: 'Trend',
      tip: 'Trend momentum based on volume, velocity, and sentiment.',
    },
    {
      key: 'source_consensus_score',
      label: 'Consensus',
      tip: 'Agreement across Google Trends, YouTube, Reddit, and News.',
    },
    {
      key: 'geo_fit_score',
      label: 'Geo',
      tip: 'Match between trend geography and company geo focus.',
    },
    {
      key: 'audience_fit_score',
      label: 'Audience',
      tip: 'Match between trend topic and target audience persona/age/gender.',
    },
    {
      key: 'category_fit_score',
      label: 'Category',
      tip: 'Alignment with company categories and content themes.',
    },
    {
      key: 'health_multiplier',
      label: 'Health',
      tip: 'Freshness and reliability of trend sources.',
    },
    {
      key: 'historical_accuracy_score',
      label: 'Accuracy',
      tip: 'Historical accuracy of similar recommendations.',
    },
    {
      key: 'platform_fit_score',
      label: 'Platform',
      tip: 'Fit based on active platform strategies and content types.',
    },
  ];

  return (
    <div className="min-h-screen bg-gray-50 p-6">
      <div className="max-w-5xl mx-auto space-y-6">
        <div className="bg-white rounded-lg shadow p-6">
          <div className="flex items-center justify-between">
            <div>
              <h1 className="text-2xl font-bold text-gray-900 mb-2">Recommendations</h1>
              <p className="text-sm text-gray-600">
                Trend-aligned campaign recommendations based on your profile and signals.
              </p>
              {lastRefresh && (
                <div className="text-xs text-gray-500 mt-1">
                  Last refreshed: {lastRefresh} • Source: {lastRefreshSource || 'manual'}
                </div>
              )}
            </div>
            <div className="flex items-center gap-2">
              <button
                onClick={generateRecommendations}
                disabled={isLoading}
                className="px-4 py-2 bg-indigo-600 text-white rounded-lg text-sm disabled:opacity-50"
              >
                {isLoading ? 'Generating...' : 'Generate'}
              </button>
              <button
                onClick={refreshRecommendations}
                disabled={isLoading}
                className="px-4 py-2 bg-gray-100 text-gray-900 rounded-lg text-sm disabled:opacity-50"
              >
                🔄 Refresh Recommendations
              </button>
              {isAdmin && (
                <button
                  onClick={() => {
                    const campaignId =
                      typeof router.query.campaignId === 'string' ? router.query.campaignId : '';
                    const target = campaignId
                      ? `/recommendations/policy?campaignId=${encodeURIComponent(campaignId)}`
                      : '/recommendations/policy';
                    window.location.href = target;
                  }}
                  className="px-4 py-2 bg-gray-900 text-white rounded-lg text-sm"
                >
                  Adjust Policy / Simulate
                </button>
              )}
              {isAdmin && (
                <button
                  onClick={() => {
                    const campaignId =
                      typeof router.query.campaignId === 'string' ? router.query.campaignId : '';
                    const target = campaignId
                      ? `/recommendations/analytics?campaignId=${encodeURIComponent(campaignId)}`
                      : '/recommendations/analytics';
                    window.location.href = target;
                  }}
                  className="px-4 py-2 bg-indigo-700 text-white rounded-lg text-sm"
                >
                  Analytics
                </button>
              )}
            </div>
          </div>
          <div className="mt-4 grid grid-cols-1 md:grid-cols-2 gap-4 text-sm text-gray-700">
            <div>
              <label className="block text-xs text-gray-500">Company ID</label>
              <input
                value={companyIdInput}
                onChange={(e) => setCompanyIdInput(e.target.value)}
                placeholder="default"
                className="mt-1 w-full border border-gray-300 rounded-lg px-3 py-2 text-sm"
              />
            </div>
            <div>
              <label className="block text-xs text-gray-500">Campaign ID (optional)</label>
              <input
                value={campaignIdInput}
                onChange={(e) => setCampaignIdInput(e.target.value)}
                placeholder="campaign-id"
                className="mt-1 w-full border border-gray-300 rounded-lg px-3 py-2 text-sm"
                disabled={campaignIdLocked}
              />
              {campaignIdLocked && (
                <p className="text-xs text-gray-500 mt-1">Prefilled from campaign link.</p>
              )}
            </div>
          </div>
        </div>

        {errorMessage && (
          <div className="bg-red-50 border border-red-200 text-red-800 text-sm rounded-lg p-3">
            {errorMessage}
          </div>
        )}

        <div className="space-y-4">
          {recommendations.map((rec, idx) => (
            <div key={`${rec.trend}-${idx}`} className="bg-white rounded-lg shadow p-6">
              <div className="flex items-center justify-between">
                <div>
                  <h2 className="text-lg font-semibold text-gray-900">{rec.title || rec.trend}</h2>
                  <p className="text-sm text-gray-500">{rec.description || rec.category}</p>
                  {rec.trend_source && (
                    <div className="flex items-center gap-2 text-xs text-gray-400">
                      <span>Source: {rec.trend_source}</span>
                      <span
                        className={`inline-flex items-center px-2 py-0.5 rounded-full text-[11px] font-medium ${getHealthBadge(
                          rec.trend_source_health
                        ).className}`}
                        title="Based on freshness & reliability of data source"
                      >
                        {getHealthBadge(rec.trend_source_health).label}
                      </span>
                    </div>
                  )}
                  {rec.recommendation_id && (
                    <p className="text-xs text-gray-400">ID: {rec.recommendation_id}</p>
                  )}
                </div>
                <div className="text-right text-sm text-gray-600">
                  <div>Score: {rec.final_score}</div>
                  <div>Effort: {rec.effort_score}</div>
                  {rec.confidence !== undefined && (
                    <span
                      className={`inline-flex items-center px-2 py-1 rounded-full text-xs font-medium ${getConfidenceBadge(
                        rec.confidence
                      )}`}
                    >
                      Confidence: {rec.confidence}%
                    </span>
                  )}
                </div>
              </div>

              <div className="mt-4 grid grid-cols-1 md:grid-cols-3 gap-4 text-sm text-gray-700">
                <div>
                  <div className="font-medium text-gray-900">Geo</div>
                  <div>{typeof rec.geo === 'string' ? rec.geo : JSON.stringify(rec.geo)}</div>
                </div>
                <div>
                  <div className="font-medium text-gray-900">Audience</div>
                  <div>
                    {typeof rec.audience === 'string'
                      ? rec.audience
                      : JSON.stringify(rec.audience)}
                  </div>
                </div>
                <div>
                  <div className="font-medium text-gray-900">Platforms</div>
                  <div>{rec.platforms?.map((p) => p.platform).join(', ') || '—'}</div>
                </div>
              </div>

              <div className="mt-4 text-sm text-gray-700">
                <div>Promotion: {rec.promotion_mode}</div>
                <div>Expected reach: {rec.expected_reach}</div>
                <div>Expected growth: {rec.expected_growth}</div>
              </div>

              {rec.platforms && rec.platforms.length > 0 && (
                <div className="mt-4 grid grid-cols-1 md:grid-cols-3 gap-3 text-xs text-gray-700">
                  {rec.platforms.map((platform) => (
                    <div key={platform.platform} className="border rounded-lg p-3 bg-gray-50">
                      <div className="font-semibold text-gray-900 capitalize">{platform.platform}</div>
                      <div className="mt-1">
                        Content: {platform.content_types?.join(', ') || '—'}
                      </div>
                      <div className="mt-1">
                        Needs: {platform.required_metadata?.join(', ') || '—'}
                      </div>
                      <div className="mt-1">Mode: {rec.promotion_mode}</div>
                    </div>
                  ))}
                </div>
              )}

              <details className="mt-4 text-sm text-gray-700">
                <summary className="cursor-pointer text-sm font-medium text-gray-800">
                  Why this recommendation?
                </summary>
                <div className="mt-2 text-sm text-gray-600">
                  {rec.explanation || rec.rationale}
                </div>
                {rec.scores && (
                  <div className="mt-2 text-xs text-gray-600 grid grid-cols-2 gap-2">
                    {scoreMeta.map((item) => (
                      <div key={item.key} title={item.tip} className="flex items-center gap-1">
                        <span className="font-medium">{item.label}:</span>
                        <span>{(rec.scores as any)[item.key] ?? '—'}</span>
                      </div>
                    ))}
                    <div title="Promotion mode fit based on selected strategy.">
                      <span className="font-medium">Promotion:</span> {rec.scores.promotion_fit_score}
                    </div>
                    <div title="Estimated effort to execute this recommendation.">
                      <span className="font-medium">Effort:</span> {rec.scores.effort_score}
                    </div>
                  </div>
                )}
              </details>

              <div className="mt-4">
                <button
                  onClick={() => createCampaignFromRecommendation(rec)}
                  disabled={!rec.id || creatingId === rec.id}
                  className="px-4 py-2 bg-gray-100 text-gray-900 rounded-lg text-sm disabled:opacity-50"
                >
                  {creatingId === rec.id ? 'Creating...' : 'Create Campaign'}
                </button>
              </div>
            </div>
          ))}
          {recommendations.length === 0 && !isLoading && (
            <div className="text-sm text-gray-500">No recommendations yet.</div>
          )}
        </div>
      </div>
    </div>
  );
}
