import React, { useEffect, useMemo, useState } from 'react';
import { useRouter } from 'next/router';
import { useCompanyContext } from '../components/CompanyContext';
import {
  buildTrendSourceCounts,
  getConfidenceLabel,
  hasNoExternalSignals,
  shouldShowNoveltyWarning,
} from '../backend/services/recommendationUiExplainability';

type TrendSignal = {
  topic: string;
  source?: string;
  sources?: string[];
  geo?: string;
  velocity?: number;
  sentiment?: number;
  volume?: number;
  frequency?: number;
  platform_tag?: string;
};

type RecommendationEngineResult = {
  trends_used: TrendSignal[];
  trends_ignored: TrendSignal[];
  weekly_plan: Array<{
    week_number: number;
    theme: string;
    trend_influence?: string[];
    platforms?: string[];
  }>;
  daily_plan: Array<{
    date: string;
    platform: string;
    content_type: string;
    topic: string;
    CTA?: string;
  }>;
  confidence_score: number;
  explanation: string;
  sources: string[];
  signal_quality?: {
    external_api_health_snapshot?: Array<{
      api_source_id: string;
      health_score: number;
      avg_latency_ms: number;
    }>;
    cache_hits?: { hits: number; misses: number };
    rate_limited_sources?: string[];
    signal_confidence_summary?: { average: number; min: number; max: number } | null;
  };
  omnivyra_metadata?: {
    decision_id?: string;
    confidence?: number;
    explanation?: string;
    placeholders?: string[];
  };
  novelty_score?: number;
  omnivyra_learning?: {
    status: 'sent' | 'failed' | 'skipped';
    error?: string;
  };
  omnivyra_status?: {
    status: 'healthy' | 'degraded' | 'down' | 'disabled';
    confidence?: number;
    contract_version?: string;
    latency_ms?: number;
    fallback_reason?: string | null;
    last_error?: string | null;
    endpoint?: string | null;
  };
};

type TrendSourceLegendItem = {
  key: string;
  label: string;
  description: string;
  badgeClass: string;
};

export default function RecommendationsPage() {
  const router = useRouter();
  const {
    user,
    companies,
    selectedCompanyId,
    selectedCompanyName,
    setSelectedCompanyId,
    isLoading: isCompanyLoading,
  } = useCompanyContext();
  const [engineResult, setEngineResult] = useState<RecommendationEngineResult | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [errorMessage, setErrorMessage] = useState<string | null>(null);
  const [campaigns, setCampaigns] = useState<Array<{ id: string; name: string; status: string }>>([]);
  const [isCampaignLoading, setIsCampaignLoading] = useState(false);
  const [selectedCampaignId, setSelectedCampaignId] = useState<string>('');
  const [selectedCampaignName, setSelectedCampaignName] = useState<string>('');
  const [campaignIdLocked, setCampaignIdLocked] = useState(false);
  const [autoGenerated, setAutoGenerated] = useState(false);
  const [lastRefresh, setLastRefresh] = useState<string | null>(null);
  const [lastRefreshSource, setLastRefreshSource] = useState<string | null>(null);
  const isAdmin = useMemo(() => user?.role === 'admin', [user]);

  useEffect(() => {
    const queryCampaignId =
      typeof router.query.campaignId === 'string' ? router.query.campaignId : '';
    if (queryCampaignId) {
      setSelectedCampaignId(queryCampaignId);
      setCampaignIdLocked(true);
    }
  }, [router.query.campaignId]);

  useEffect(() => {
    if (!selectedCompanyId) {
      setCampaigns([]);
      setSelectedCampaignId('');
      setSelectedCampaignName('');
      return;
    }
    const stored = typeof window !== 'undefined'
      ? window.localStorage.getItem('selected_campaign_id') || ''
      : '';
    if (stored && stored !== selectedCampaignId) {
      setSelectedCampaignId(stored);
    }
  }, [selectedCompanyId]);

  useEffect(() => {
    if (!selectedCompanyId) return;
    const loadCampaigns = async () => {
      setIsCampaignLoading(true);
      try {
        const response = await fetch(`/api/campaigns?companyId=${encodeURIComponent(selectedCompanyId)}`);
        if (!response.ok) {
          throw new Error('Failed to load campaigns');
        }
        const data = await response.json();
        const list = (data.campaigns || []).map((item: any) => ({
          id: item.id,
          name: item.name || `Campaign ${item.id}`,
          status: item.status || 'planning',
        }));
        setCampaigns(list);
        const matched = list.find((item) => item.id === selectedCampaignId);
        if (matched) {
          setSelectedCampaignName(matched.name);
        } else if (!campaignIdLocked) {
          setSelectedCampaignId('');
          setSelectedCampaignName('');
        }
      } catch (error) {
        console.error('Unable to load campaigns');
        setCampaigns([]);
      } finally {
        setIsCampaignLoading(false);
      }
    };
    loadCampaigns();
  }, [selectedCompanyId, campaignIdLocked]);

  useEffect(() => {
    if (!selectedCampaignId || !campaignIdLocked || autoGenerated || isLoading) return;
    setAutoGenerated(true);
    generateRecommendations();
  }, [selectedCampaignId, campaignIdLocked, autoGenerated, isLoading]);

  useEffect(() => {
    if (!selectedCampaignId) return;
    const match = campaigns.find((campaign) => campaign.id === selectedCampaignId);
    if (match) {
      setSelectedCampaignName(match.name);
      if (typeof window !== 'undefined') {
        window.localStorage.setItem('selected_campaign_id', selectedCampaignId);
      }
      console.log('SELECTED_CAMPAIGN', {
        companyId: selectedCompanyId,
        campaignId: selectedCampaignId,
        campaignName: match.name,
      });
    }
  }, [selectedCampaignId, campaigns, selectedCompanyId]);

  const generateRecommendations = async () => {
    if (!selectedCompanyId || !selectedCampaignId) {
      setErrorMessage('Please select or create a campaign first.');
      return;
    }
    try {
      setIsLoading(true);
      setErrorMessage(null);
      const response = await fetch('/api/recommendations/generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          companyId: selectedCompanyId,
          campaignId: selectedCampaignId,
        }),
      });
      if (!response.ok) throw new Error('Failed to generate recommendations');
      const data = await response.json();
      setEngineResult(data);
      setLastRefresh(new Date().toLocaleString());
      setLastRefreshSource('manual');
    } catch (error) {
      console.error('Error generating recommendations:', error);
      setErrorMessage('Failed to generate recommendations.');
    } finally {
      setIsLoading(false);
    }
  };

  const refreshRecommendations = async () => {
    if (!selectedCompanyId) {
      setErrorMessage('Please select or create a campaign first.');
      return;
    }
    try {
      setIsLoading(true);
      setErrorMessage(null);
      const response = await fetch('/api/recommendations/refresh', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          mode: 'company',
          companyId: selectedCompanyId,
        }),
      });
      if (!response.ok) throw new Error('Failed to refresh recommendations');
      setLastRefresh(new Date().toLocaleString());
      setLastRefreshSource('profile_update');
      await generateRecommendations();
    } catch (error) {
      console.error('Error refreshing recommendations:', error);
      setErrorMessage('Failed to refresh recommendations.');
      setIsLoading(false);
    }
  };
  const confidencePercent = engineResult?.confidence_score ?? 0;
  const confidenceRatio = Math.max(0, Math.min(1, confidencePercent / 100));
  const confidenceMeta = getConfidenceLabel(confidenceRatio);
  const noExternalSignals = hasNoExternalSignals(engineResult?.omnivyra_metadata?.placeholders);
  const showNoveltyWarning = shouldShowNoveltyWarning(engineResult?.novelty_score);
  const trendCounts = buildTrendSourceCounts(engineResult?.trends_used || []);
  const trendSourceLegend: TrendSourceLegendItem[] = [
    {
      key: 'youtube',
      label: 'YouTube',
      description: 'YouTube Data API trend signals.',
      badgeClass: 'bg-red-100 text-red-700',
    },
    {
      key: 'newsapi',
      label: 'NewsAPI',
      description: 'NewsAPI headlines and breaking topics.',
      badgeClass: 'bg-blue-100 text-blue-700',
    },
    {
      key: 'reddit',
      label: 'Reddit',
      description: 'Reddit community trend signals.',
      badgeClass: 'bg-orange-100 text-orange-700',
    },
    {
      key: 'serpapi',
      label: 'SerpAPI',
      description: 'SerpAPI Google Trends signals.',
      badgeClass: 'bg-green-100 text-green-700',
    },
    {
      key: 'omnivyra',
      label: 'OmniVyra',
      description: 'OmniVyra intelligence curated trends.',
      badgeClass: 'bg-purple-100 text-purple-700',
    },
  ];
  const omnivyraStatus = engineResult?.omnivyra_status;
  const omnivyraStatusColor =
    omnivyraStatus?.status === 'healthy'
      ? 'bg-green-100 text-green-700'
      : omnivyraStatus?.status === 'degraded'
      ? 'bg-yellow-100 text-yellow-700'
      : omnivyraStatus?.status === 'down'
      ? 'bg-red-100 text-red-700'
      : 'bg-gray-100 text-gray-700';

  return (
    <div className="min-h-screen bg-gray-50 p-6">
      <div className="max-w-5xl mx-auto space-y-6">
        <div className="bg-white rounded-lg shadow p-6">
          <div className="flex items-center justify-between">
            <div>
              <h1 className="text-2xl font-bold text-gray-900 mb-2">Recommendations</h1>
              <p className="text-sm text-gray-600">
                Trend-aligned campaign recommendations based on your profile and signals.
              </p>
              {lastRefresh && (
                <div className="text-xs text-gray-500 mt-1">
                  Last refreshed: {lastRefresh} • Source: {lastRefreshSource || 'manual'}
                </div>
              )}
            </div>
            <div className="flex items-center gap-2">
              <button
                onClick={generateRecommendations}
                disabled={isLoading || !selectedCompanyId || !selectedCampaignId}
                className="px-4 py-2 bg-indigo-600 text-white rounded-lg text-sm disabled:opacity-50"
              >
                {isLoading ? 'Generating...' : 'Generate'}
              </button>
              <button
                onClick={refreshRecommendations}
                disabled={isLoading || !selectedCompanyId}
                className="px-4 py-2 bg-gray-100 text-gray-900 rounded-lg text-sm disabled:opacity-50"
              >
                🔄 Refresh Recommendations
              </button>
              {isAdmin && (
                <button
                  onClick={() => {
                    const campaignId =
                      typeof router.query.campaignId === 'string' ? router.query.campaignId : '';
                    const target = campaignId
                      ? `/recommendations/policy?campaignId=${encodeURIComponent(campaignId)}`
                      : '/recommendations/policy';
                    window.location.href = target;
                  }}
                  className="px-4 py-2 bg-gray-900 text-white rounded-lg text-sm"
                >
                  Adjust Policy / Simulate
                </button>
              )}
              {isAdmin && (
                <button
                  onClick={() => {
                    const campaignId =
                      typeof router.query.campaignId === 'string' ? router.query.campaignId : '';
                    const target = campaignId
                      ? `/recommendations/analytics?campaignId=${encodeURIComponent(campaignId)}`
                      : '/recommendations/analytics';
                    window.location.href = target;
                  }}
                  className="px-4 py-2 bg-indigo-700 text-white rounded-lg text-sm"
                >
                  Analytics
                </button>
              )}
            </div>
          </div>
          {!selectedCompanyId || !selectedCampaignId ? (
            <div className="mt-4 text-xs text-amber-600">
              Please select a company and campaign.
            </div>
          ) : null}
          <div className="mt-4 grid grid-cols-1 md:grid-cols-2 gap-4 text-sm text-gray-700">
            <div>
              <label className="block text-xs text-gray-500">Company</label>
              <select
                value={selectedCompanyId}
                onChange={(e) => {
                  setSelectedCompanyId(e.target.value);
                  setSelectedCampaignId('');
                  setSelectedCampaignName('');
                }}
                disabled={!isAdmin || isCompanyLoading}
                className="mt-1 w-full border border-gray-300 rounded-lg px-3 py-2 text-sm disabled:bg-gray-100"
              >
                <option value="">Select company</option>
                {companies.map((company) => (
                  <option key={company.company_id} value={company.company_id}>
                    {company.name}
                  </option>
                ))}
              </select>
              {!isAdmin && selectedCompanyName && (
                <p className="text-xs text-gray-500 mt-1">Company locked for your role.</p>
              )}
            </div>
            <div>
              <label className="block text-xs text-gray-500">Campaign</label>
              <div className="flex gap-2">
                <select
                  value={selectedCampaignId}
                  onChange={(e) => setSelectedCampaignId(e.target.value)}
                  disabled={!selectedCompanyId || isCampaignLoading || campaignIdLocked}
                  className="mt-1 flex-1 border border-gray-300 rounded-lg px-3 py-2 text-sm disabled:bg-gray-100"
                >
                  <option value="">Select campaign</option>
                  {campaigns.map((campaign) => (
                    <option key={campaign.id} value={campaign.id}>
                      {campaign.name} ({campaign.status})
                    </option>
                  ))}
                </select>
                <button
                  onClick={async () => {
                    if (!selectedCompanyId) {
                      setErrorMessage('Please select or create a campaign first.');
                      return;
                    }
                    try {
                      const timestamp = new Date().toISOString().replace('T', ' ').slice(0, 16);
                      const response = await fetch('/api/campaigns', {
                        method: 'POST',
                        headers: { 'Content-Type': 'application/json' },
                        body: JSON.stringify({
                          companyId: selectedCompanyId,
                          name: `Campaign ${timestamp}`,
                          status: 'planning',
                          current_stage: 'planning',
                          timeframe: 'quarter',
                        }),
                      });
                      if (!response.ok) {
                        throw new Error('Failed to create campaign');
                      }
                      const data = await response.json();
                      const created = data.campaign;
                      if (created?.id) {
                        setCampaigns((prev) => [
                          { id: created.id, name: created.name, status: created.status || 'planning' },
                          ...prev,
                        ]);
                        setSelectedCampaignId(created.id);
                        setSelectedCampaignName(created.name);
                        console.log('CAMPAIGN_CREATED', {
                          companyId: selectedCompanyId,
                          campaignId: created.id,
                          campaignName: created.name,
                        });
                      }
                    } catch (error) {
                      setErrorMessage('Failed to create campaign.');
                    }
                  }}
                  className="mt-1 px-3 py-2 bg-gray-100 text-gray-900 rounded-lg text-xs"
                  disabled={!selectedCompanyId}
                >
                  + Create
                </button>
              </div>
              {campaignIdLocked && (
                <p className="text-xs text-gray-500 mt-1">Prefilled from campaign link.</p>
              )}
            </div>
          </div>
        </div>

        {errorMessage && (
          <div className="bg-red-50 border border-red-200 text-red-800 text-sm rounded-lg p-3">
            {errorMessage}
          </div>
        )}
        {noExternalSignals && (
          <div className="bg-yellow-50 border border-yellow-200 text-yellow-900 text-sm rounded-lg p-3">
            Not enough trend data available. Using fallback strategy.
          </div>
        )}
        {showNoveltyWarning && (
          <div className="bg-orange-50 border border-orange-200 text-orange-900 text-sm rounded-lg p-3">
            ⚠️ Some themes were regenerated to avoid repeating past campaigns.
            <div className="text-xs text-orange-800 mt-1">
              Campaign memory detected overlap. Confidence adjusted accordingly.
            </div>
          </div>
        )}

        <div className="space-y-4">
          {engineResult ? (
            <>
              <div className="bg-white rounded-lg shadow p-6 space-y-4">
                <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-4">
                  <div>
                    <h2 className="text-lg font-semibold text-gray-900">Recommendation Overview</h2>
                    <p className="text-sm text-gray-500">{engineResult.explanation}</p>
                  </div>
                  <div className="w-full md:w-64">
                    <div className="text-xs text-gray-500 mb-1">Confidence</div>
                    <div className="h-2 bg-gray-100 rounded-full overflow-hidden">
                      <div
                        className="h-full bg-indigo-500"
                        style={{ width: `${confidencePercent}%` }}
                      />
                    </div>
                    <div className={`text-xs mt-1 ${confidenceMeta.className}`}>
                      {confidenceMeta.label} • {confidencePercent}%
                    </div>
                  </div>
                </div>
                <div className="text-xs text-gray-600">
                  Sources: {engineResult.sources?.length ? engineResult.sources.join(', ') : '—'}
                </div>
              </div>

              <div className="bg-white rounded-lg shadow p-6">
                <h3 className="text-sm font-semibold text-gray-900 mb-3">Trend Sources</h3>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-3 text-xs text-gray-700">
                  {trendSourceLegend.map((item) => (
                    <div
                      key={item.key}
                      className="flex items-center justify-between border rounded-lg px-3 py-2"
                      title={item.description}
                    >
                      <span className="font-medium">{item.label}</span>
                      <span className={`px-2 py-0.5 rounded-full text-[11px] ${item.badgeClass}`}>
                        {(trendCounts as any)[item.key] || 0} trends
                      </span>
                    </div>
                  ))}
                  <div
                    className="flex items-center justify-between border rounded-lg px-3 py-2"
                    title="Trends ignored due to relevance or duplication."
                  >
                    <span className="font-medium">Ignored</span>
                    <span className="px-2 py-0.5 rounded-full text-[11px] bg-gray-100 text-gray-700">
                      {engineResult.trends_ignored.length} trends
                    </span>
                  </div>
                </div>
              </div>

              {engineResult.signal_quality && (
                <div className="bg-white rounded-lg shadow p-6">
                  <h3 className="text-sm font-semibold text-gray-900 mb-3">Signal Quality</h3>
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-xs text-gray-700">
                    <div className="border rounded-lg p-3">
                      <div className="font-semibold text-gray-900">API Health</div>
                      <div className="mt-2 space-y-1">
                        {(engineResult.signal_quality.external_api_health_snapshot || []).map((item) => {
                          const score = item.health_score ?? 0;
                          const status =
                            score >= 0.75 ? 'bg-green-100 text-green-700' : score >= 0.4 ? 'bg-yellow-100 text-yellow-700' : 'bg-red-100 text-red-700';
                          return (
                            <div key={item.api_source_id} className="flex items-center justify-between">
                              <span className="text-xs text-gray-600">{item.api_source_id}</span>
                              <span className={`px-2 py-0.5 rounded-full text-[11px] ${status}`}>
                                {(score * 100).toFixed(0)}%
                              </span>
                            </div>
                          );
                        })}
                        {(engineResult.signal_quality.external_api_health_snapshot || []).length === 0 && (
                          <div className="text-xs text-gray-500">No API health data.</div>
                        )}
                      </div>
                    </div>
                    <div className="border rounded-lg p-3">
                      <div className="font-semibold text-gray-900">Cache & Rate Limit</div>
                      <div className="mt-2 text-xs text-gray-600">
                        Cache hits: {engineResult.signal_quality.cache_hits?.hits ?? 0}
                      </div>
                      <div className="text-xs text-gray-600">
                        Cache misses: {engineResult.signal_quality.cache_hits?.misses ?? 0}
                      </div>
                      <div className="mt-2 text-xs text-gray-600">
                        Rate-limited sources:{' '}
                        {engineResult.signal_quality.rate_limited_sources?.length
                          ? engineResult.signal_quality.rate_limited_sources.join(', ')
                          : 'None'}
                      </div>
                      <div className="mt-2 text-xs text-gray-600">
                        Signal confidence avg:{' '}
                        {engineResult.signal_quality.signal_confidence_summary?.average ?? '—'}
                      </div>
                    </div>
                  </div>
                </div>
              )}

              {omnivyraStatus && (
                <div className="bg-white rounded-lg shadow p-6">
                  <h3 className="text-sm font-semibold text-gray-900 mb-3">OmniVyra Status</h3>
                  <div className="flex items-center gap-2 text-xs text-gray-700">
                    <span className={`px-2 py-0.5 rounded-full ${omnivyraStatusColor}`}>
                      {omnivyraStatus.status}
                    </span>
                    <span>Endpoint: {omnivyraStatus.endpoint || '—'}</span>
                  </div>
                  <div className="mt-2 grid grid-cols-1 md:grid-cols-2 gap-2 text-xs text-gray-600">
                    <div>Confidence: {omnivyraStatus.confidence ?? '—'}</div>
                    <div>Contract version: {omnivyraStatus.contract_version ?? '—'}</div>
                    <div>Latency: {omnivyraStatus.latency_ms ?? '—'} ms</div>
                    <div>Last error: {omnivyraStatus.last_error ?? '—'}</div>
                    <div>Fallback reason: {omnivyraStatus.fallback_reason ?? '—'}</div>
                  </div>
                </div>
              )}

              {engineResult.omnivyra_metadata && (
                <div className="bg-white rounded-lg shadow p-6">
                  <details className="text-sm text-gray-700">
                    <summary className="cursor-pointer text-sm font-semibold text-gray-900">
                      Why these recommendations?
                    </summary>
                    <div className="mt-2 text-sm text-gray-600">
                      {engineResult.omnivyra_metadata.explanation || 'OmniVyra explanation not available.'}
                    </div>
                    <div className="mt-2 text-xs text-gray-500">
                      Decision ID: {engineResult.omnivyra_metadata.decision_id || '—'}
                    </div>
                    <div className="mt-1 text-xs text-gray-500">
                      Confidence: {engineResult.omnivyra_metadata.confidence ?? '—'}
                    </div>
                    {engineResult.omnivyra_metadata.placeholders?.length ? (
                      <div className="mt-2 text-xs text-gray-500">
                        Placeholders: {engineResult.omnivyra_metadata.placeholders.join(', ')}
                      </div>
                    ) : null}
                  </details>
                </div>
              )}

              {engineResult.omnivyra_learning && (
                <div className="bg-white rounded-lg shadow p-6">
                  <h3 className="text-sm font-semibold text-gray-900 mb-2">
                    Learning sent to OmniVyra
                  </h3>
                  <div className="text-xs text-gray-700">
                    {engineResult.omnivyra_learning.status === 'sent' && '✅ Sent'}
                    {engineResult.omnivyra_learning.status === 'failed' && '⚠️ Failed'}
                    {engineResult.omnivyra_learning.status === 'skipped' && '⏭ Skipped (flag off)'}
                  </div>
                  {engineResult.omnivyra_learning.error && (
                    <div className="text-xs text-red-600 mt-1">
                      {engineResult.omnivyra_learning.error}
                    </div>
                  )}
                </div>
              )}

              <div className="bg-white rounded-lg shadow p-6">
                <h3 className="text-sm font-semibold text-gray-900 mb-3">Trends Used</h3>
                <div className="flex flex-wrap gap-2">
                  {engineResult.trends_used.map((trend, index) => (
                    <span
                      key={`${trend.topic}-${index}`}
                      className="text-xs bg-indigo-50 text-indigo-700 px-2 py-1 rounded-full"
                    >
                      {trend.topic}
                    </span>
                  ))}
                  {engineResult.trends_used.length === 0 && (
                    <span className="text-xs text-gray-500">No external trends used.</span>
                  )}
                </div>
              </div>

              <div className="bg-white rounded-lg shadow p-6">
                <h3 className="text-sm font-semibold text-gray-900 mb-3">Trends Ignored</h3>
                <div className="flex flex-wrap gap-2">
                  {engineResult.trends_ignored.map((trend, index) => (
                    <span
                      key={`${trend.topic}-${index}`}
                      className="text-xs bg-gray-100 text-gray-700 px-2 py-1 rounded-full"
                    >
                      {trend.topic}
                    </span>
                  ))}
                  {engineResult.trends_ignored.length === 0 && (
                    <span className="text-xs text-gray-500">No ignored trends.</span>
                  )}
                </div>
              </div>

              <div className="bg-white rounded-lg shadow p-6">
                <h3 className="text-sm font-semibold text-gray-900 mb-3">Weekly Plan</h3>
                <div className="space-y-3 text-sm text-gray-700">
                  {engineResult.weekly_plan.map((week) => (
                    <div key={`week-${week.week_number}`} className="border rounded-lg p-3">
                      <div className="font-semibold text-gray-900">
                        Week {week.week_number}: {week.theme}
                      </div>
                      <div className="text-xs text-gray-500 mt-1">
                        Trends: {(week.trend_influence || []).join(', ') || '—'}
                      </div>
                      <div className="text-xs text-gray-500">
                        Platforms: {(week.platforms || []).join(', ') || '—'}
                      </div>
                    </div>
                  ))}
                  {engineResult.weekly_plan.length === 0 && (
                    <div className="text-xs text-gray-500">Weekly plan not available.</div>
                  )}
                </div>
              </div>

              <div className="bg-white rounded-lg shadow p-6">
                <h3 className="text-sm font-semibold text-gray-900 mb-3">Daily Plan</h3>
                <div className="space-y-2 text-sm text-gray-700">
                  {engineResult.daily_plan.slice(0, 14).map((day, index) => (
                    <div key={`day-${index}`} className="flex items-center justify-between border-b pb-2">
                      <div>
                        <div className="font-medium text-gray-900">{day.date}</div>
                        <div className="text-xs text-gray-500">
                          {day.platform} • {day.content_type}
                        </div>
                      </div>
                      <div className="text-xs text-gray-600 text-right max-w-xs">
                        {day.topic}
                      </div>
                    </div>
                  ))}
                  {engineResult.daily_plan.length === 0 && (
                    <div className="text-xs text-gray-500">Daily plan not available.</div>
                  )}
                  {engineResult.daily_plan.length > 14 && (
                    <div className="text-xs text-gray-500">
                      Showing first 14 entries. Generate the campaign for full plan.
                    </div>
                  )}
                </div>
              </div>
            </>
          ) : (
            !isLoading && <div className="text-sm text-gray-500">No recommendations yet.</div>
          )}
        </div>
      </div>
    </div>
  );
}
