-- ────────────────────────────────────────────────────────────────────────────
-- 00000000000000_baseline_schema.sql
--
-- Generated by Phase B1 on 2026-05-04 from production catalog (information_schema
-- + pg_class + pg_constraint + pg_indexes). Represents the 26 base tables that
-- the 32 canonical migrations REFERENCE but do not CREATE — they were applied
-- out-of-band (via SQL Editor or pre-canonical scripts) and have no source-
-- of-truth migration in supabase_migrations.schema_migrations.
--
-- Filename uses 14 zeros so this file lex-sorts BEFORE every real timestamped
-- migration (Supabase applies in lex order).
--
-- Coverage:
--   ✓ CREATE TABLE IF NOT EXISTS for each base table (current prod columns,
--     types, defaults, NOT NULL flags)
--   ✓ PRIMARY KEY constraints
--   ✓ UNIQUE constraints (table-level)
--   ✓ CHECK constraints (named, idempotency-guarded via DO blocks)
--   ✓ Non-PK / non-table-level-UNIQUE indexes (CREATE INDEX IF NOT EXISTS)
--
-- Intentional EXCLUSIONS (not added by this baseline; left for follow-up):
--   ✗ Foreign keys to public.* — added in a follow-up baseline FK migration
--     so this file can apply without circular dependency on out-of-order CREATE
--   ✗ Foreign keys to auth.* — Supabase manages auth.users; replay env may
--     not have it
--   ✗ RLS policies — managed by separate RLS migration (Phase D)
--   ✗ Triggers, functions, views, sequences (other than serials)
--   ✗ Supabase-managed schemas: auth, storage, realtime, vault, extensions
--
-- Idempotency: every statement uses IF NOT EXISTS or DO-block guard so this
-- file is safe to re-apply.
--
-- Tables included (26):
--   access_requests, action_pricing_config, community_ai_actions,
--   community_ai_platform_tokens, companies, company_domains,
--   credit_transactions, daily_content_plans, domain_eligibility_cache,
--   domain_whitelist, email_jobs, free_credit_claims, free_credit_profiles,
--   invitations, llm_model_pricing, organization_credits,
--   platform_oauth_configs, scheduled_posts, social_accounts,
--   super_admin_audit_logs, unified_transactions, usage_events,
--   user_company_roles, user_override, user_preferences, users
-- ────────────────────────────────────────────────────────────────────────────

-- Required extensions (referenced by some default expressions)
CREATE EXTENSION IF NOT EXISTS pgcrypto;     -- gen_random_uuid()
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ── 1. CREATE TABLE statements ─────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.access_requests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  email text NOT NULL,
  domain text NOT NULL,
  company_name text,
  website text,
  use_case text,
  status text NOT NULL DEFAULT 'pending'::text,
  reviewed_by uuid,
  review_notes text,
  credits_grant_on_approve integer NOT NULL DEFAULT 300,
  credits_granted boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  name text,
  website_url text,
  job_title text,
  domain_status text,
  organization_id uuid,
  reviewed_at timestamp with time zone,
  admin_note text,
  rejection_reason text,
  credits_granted_amount integer
);

CREATE TABLE IF NOT EXISTS public.action_pricing_config (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  action_key text NOT NULL,
  credit_cost integer,
  cost_multiplier numeric(10,4) NOT NULL DEFAULT 1.0,
  effective_from timestamp with time zone NOT NULL DEFAULT now(),
  is_active boolean NOT NULL DEFAULT true,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  source_type text NOT NULL,
  minimum_charge_usd numeric NOT NULL DEFAULT 0,
  ceiling_usd numeric
);

CREATE TABLE IF NOT EXISTS public.community_ai_actions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  organization_id uuid NOT NULL,
  platform text NOT NULL,
  action_type text NOT NULL,
  target_id text NOT NULL,
  suggested_text text,
  tone text,
  risk_level text,
  requires_human_approval boolean DEFAULT true,
  status text,
  execution_result jsonb,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  scheduled_at timestamp without time zone,
  tone_used text,
  requires_approval boolean,
  final_text text,
  execution_mode text,
  playbook_id uuid,
  playbook_name text,
  intent_classification jsonb,
  discovered_user_id uuid,
  executed_at timestamp with time zone,
  skip_reason text,
  execution_correlation_id uuid,
  approved_at timestamp with time zone,
  dispatch_lease_id text,
  dispatch_lease_expires_at timestamp with time zone,
  dispatch_lease_holder_id text,
  dispatch_acknowledged_at timestamp with time zone,
  idempotency_key text,
  command_chain jsonb,
  command_chain_index integer,
  cancel_requested_at timestamp with time zone
);

CREATE TABLE IF NOT EXISTS public.community_ai_platform_tokens (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  organization_id uuid NOT NULL,
  platform text NOT NULL,
  access_token text,
  refresh_token text,
  expires_at timestamp without time zone,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  connected_by_user_id uuid
);

CREATE TABLE IF NOT EXISTS public.companies (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  website text,
  website_domain text,
  admin_email_domain text,
  industry text,
  updated_at timestamp with time zone,
  status text NOT NULL DEFAULT 'active'::text,
  domain_claimed_at timestamp with time zone,
  size text,
  free_credit_granted_at timestamp with time zone
);

CREATE TABLE IF NOT EXISTS public.company_domains (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL,
  is_primary boolean NOT NULL DEFAULT false,
  verified boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  input_domain text,
  final_domain text NOT NULL,
  redirect_chain jsonb,
  is_forwarding boolean NOT NULL DEFAULT false,
  verification_status text NOT NULL DEFAULT 'unverified'::text,
  override_reason text,
  created_via text NOT NULL DEFAULT 'user'::text,
  verification_token text,
  verification_method text,
  verified_at timestamp with time zone
);

CREATE TABLE IF NOT EXISTS public.credit_transactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  transaction_type text NOT NULL,
  credits_delta integer NOT NULL DEFAULT 0,
  balance_after integer NOT NULL DEFAULT 0,
  usd_equivalent numeric(14,6),
  reference_type text,
  reference_id uuid,
  note text,
  performed_by uuid,
  idempotency_key text,
  execution_phase text,
  parent_transaction_id uuid,
  category text,
  free_delta integer NOT NULL DEFAULT 0,
  paid_delta integer NOT NULL DEFAULT 0,
  incentive_delta integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  is_underfunded boolean NOT NULL DEFAULT false
);

CREATE TABLE IF NOT EXISTS public.daily_content_plans (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  campaign_id uuid NOT NULL,
  week_number integer NOT NULL,
  day_of_week character varying(20) NOT NULL,
  date date NOT NULL,
  platform character varying(100) NOT NULL,
  content_type character varying(100) NOT NULL,
  title character varying(500),
  content text NOT NULL,
  hashtags text[],
  mentions text[],
  media_urls text[],
  media_types character varying(20)[],
  required_resources text[],
  scheduled_time time without time zone,
  timezone character varying(50) DEFAULT 'UTC'::character varying,
  posting_strategy text,
  status character varying(50) DEFAULT 'planned'::character varying,
  priority character varying(20) DEFAULT 'medium'::character varying,
  source_week_content_id uuid,
  source_refinement_id uuid,
  ai_generated boolean DEFAULT false,
  expected_engagement integer DEFAULT 0,
  target_audience text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  content_items jsonb DEFAULT '[]'::jsonb,
  voice_notes jsonb DEFAULT '[]'::jsonb,
  ai_enhanced boolean DEFAULT false,
  content_created boolean DEFAULT false,
  media_requirements jsonb,
  visual_elements jsonb,
  engagement_strategy text,
  target_metrics jsonb,
  actual_metrics jsonb,
  topic text,
  intro_objective text,
  summary text,
  objective text,
  main_points jsonb,
  cta text,
  brand_voice text,
  format_notes text,
  theme_linkage text,
  week_theme text,
  campaign_theme text,
  key_points jsonb,
  external_post_id text,
  execution_id text,
  scheduled_post_id uuid,
  creator_asset jsonb,
  content_status text,
  generation_source text,
  intent_type text,
  asset_type text,
  template_id text,
  plan_version integer NOT NULL DEFAULT 1,
  locked_by text,
  lease_expires_at timestamp with time zone,
  attempt_count integer NOT NULL DEFAULT 0,
  retry_count integer NOT NULL DEFAULT 0,
  max_retries integer NOT NULL DEFAULT 3,
  failure_reason text,
  failure_type text
);

CREATE TABLE IF NOT EXISTS public.domain_eligibility_cache (
  domain text NOT NULL,
  status text NOT NULL,
  reason text NOT NULL,
  has_mx boolean NOT NULL DEFAULT false,
  mx_hosts text[] NOT NULL DEFAULT '{}'::text[],
  is_forwarding boolean NOT NULL DEFAULT false,
  cached_at timestamp with time zone NOT NULL DEFAULT now(),
  expires_at timestamp with time zone NOT NULL DEFAULT (now() + '24:00:00'::interval),
  checked_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.domain_whitelist (
  domain text NOT NULL,
  approved_by uuid,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  added_by uuid,
  reason text
);

CREATE TABLE IF NOT EXISTS public.email_jobs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  job_type text NOT NULL,
  recipient_email text NOT NULL,
  subject text NOT NULL,
  html text NOT NULL,
  status text NOT NULL DEFAULT 'pending'::text,
  retry_count integer NOT NULL DEFAULT 0,
  last_error text,
  last_attempt_at timestamp with time zone,
  sent_at timestamp with time zone,
  metadata jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  idempotency_key text,
  payload_hash text,
  next_attempt_at timestamp with time zone,
  locked_at timestamp with time zone,
  locked_by text,
  request_id text
);

CREATE TABLE IF NOT EXISTS public.free_credit_claims (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  organization_id uuid,
  category text NOT NULL,
  credits_granted integer NOT NULL,
  claimed_at timestamp with time zone NOT NULL DEFAULT now(),
  domain text
);

CREATE TABLE IF NOT EXISTS public.free_credit_profiles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  organization_id uuid,
  phone_number text NOT NULL,
  phone_verified_at timestamp with time zone NOT NULL DEFAULT now(),
  firebase_uid text,
  intent_goals text[] NOT NULL DEFAULT '{}'::text[],
  intent_team text,
  intent_challenges text[] NOT NULL DEFAULT '{}'::text[],
  acquisition_source text NOT NULL DEFAULT 'get_free_credits'::text,
  initial_credits integer NOT NULL DEFAULT 300,
  credit_expiry_at timestamp with time zone NOT NULL DEFAULT (now() + '14 days'::interval),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.invitations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  email text NOT NULL,
  company_id uuid NOT NULL,
  role text NOT NULL DEFAULT 'CONTENT_CREATOR'::text,
  token_hash text NOT NULL,
  invited_by uuid,
  expires_at timestamp with time zone NOT NULL DEFAULT (now() + '7 days'::interval),
  accepted_at timestamp with time zone,
  accepted_by uuid,
  revoked_at timestamp with time zone,
  revoked_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  token_consumed_at timestamp with time zone,
  idempotency_key text
);

CREATE TABLE IF NOT EXISTS public.llm_model_pricing (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  provider text NOT NULL,
  model_name text NOT NULL,
  kind text NOT NULL DEFAULT 'completion'::text,
  input_per_1k_usd numeric(20,10) NOT NULL,
  output_per_1k_usd numeric(20,10) NOT NULL DEFAULT 0,
  effective_from timestamp with time zone NOT NULL DEFAULT now(),
  is_active boolean NOT NULL DEFAULT true,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  max_context_tokens integer,
  max_output_tokens integer
);

CREATE TABLE IF NOT EXISTS public.organization_credits (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  free_balance integer NOT NULL DEFAULT 0,
  paid_balance integer NOT NULL DEFAULT 0,
  incentive_balance integer NOT NULL DEFAULT 0,
  reserved_free integer NOT NULL DEFAULT 0,
  reserved_paid integer NOT NULL DEFAULT 0,
  reserved_incentive integer NOT NULL DEFAULT 0,
  lifetime_purchased integer NOT NULL DEFAULT 0,
  lifetime_consumed integer NOT NULL DEFAULT 0,
  credit_rate_usd numeric(10,6) NOT NULL DEFAULT 0.01,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.platform_oauth_configs (
  platform character varying(50) NOT NULL,
  oauth_client_id_encrypted text,
  oauth_client_secret_encrypted text,
  oauth_authorize_url text,
  oauth_token_url text,
  oauth_scopes text[] DEFAULT '{}'::text[],
  enabled boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.scheduled_posts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  social_account_id uuid,
  campaign_id uuid,
  platform character varying(50) NOT NULL,
  content_type character varying(100) NOT NULL,
  title character varying(500),
  content text NOT NULL,
  hashtags text[],
  location character varying(200),
  media_urls text[],
  media_types character varying(20)[],
  media_sizes bigint[],
  media_formats character varying(10)[],
  video_duration integer,
  video_resolution character varying(20),
  video_aspect_ratio character varying(10),
  video_bitrate integer,
  video_fps integer,
  image_width integer,
  image_height integer,
  image_aspect_ratio character varying(10),
  audio_duration integer,
  audio_title character varying(200),
  audio_url character varying(500),
  parent_post_id uuid,
  thread_position integer,
  is_thread_start boolean DEFAULT false,
  stickers jsonb,
  scheduled_for timestamp with time zone NOT NULL,
  status character varying(50) DEFAULT 'draft'::character varying,
  published_at timestamp with time zone,
  post_url text,
  platform_post_id character varying(255),
  error_message text,
  retry_count integer DEFAULT 0,
  max_retries integer DEFAULT 3,
  next_retry_at timestamp with time zone,
  ai_score integer,
  uniqueness_score integer,
  repetition_score integer,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  priority integer DEFAULT 0,
  error_code character varying(100),
  repurpose_index integer DEFAULT 1,
  repurpose_total integer DEFAULT 1,
  repurpose_parent_execution_id text,
  idempotency_key text,
  execution_platform_id text,
  asset_hash text,
  publish_source text NOT NULL DEFAULT 'unknown'::text
);

CREATE TABLE IF NOT EXISTS public.social_accounts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  platform character varying(50) NOT NULL,
  platform_user_id character varying(255) NOT NULL,
  account_name character varying(255) NOT NULL,
  username character varying(255),
  access_token text NOT NULL,
  refresh_token text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  profile_picture_url text,
  follower_count integer DEFAULT 0,
  following_count integer DEFAULT 0,
  token_expires_at timestamp with time zone,
  last_sync_at timestamp with time zone,
  company_id uuid,
  phone_number_id text,
  waba_id text,
  display_phone text,
  business_account_id text,
  messaging_tier integer DEFAULT 1,
  quality_rating text,
  meta_connection_id uuid,
  page_access_token text,
  ig_user_token text,
  threads_token text,
  linked_page_id text,
  linked_ig_business_id text,
  is_system_user boolean NOT NULL DEFAULT false
);

CREATE TABLE IF NOT EXISTS public.super_admin_audit_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  actor_user_id uuid NOT NULL,
  action text NOT NULL,
  target_type text NOT NULL,
  target_id text,
  metadata jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  idempotency_key text
);

CREATE TABLE IF NOT EXISTS public.unified_transactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  user_id uuid,
  action_key text,
  source_type text NOT NULL,
  provider_name text,
  model_name text,
  input_tokens integer,
  output_tokens integer,
  total_tokens integer,
  api_cost_usd numeric(20,10),
  credits_charged integer,
  credits_value_usd numeric(20,10),
  margin_usd numeric(20,10) GENERATED ALWAYS AS (COALESCE(credits_value_usd, (0)::numeric) - COALESCE(api_cost_usd, (0)::numeric)) STORED,
  retry_attempt integer NOT NULL DEFAULT 1,
  final_attempt boolean NOT NULL DEFAULT true,
  error_flag boolean NOT NULL DEFAULT false,
  error_type text,
  reference_type text,
  reference_id text,
  pricing_snapshot jsonb,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  input_cost_usd numeric,
  output_cost_usd numeric,
  final_price_usd numeric
);

CREATE TABLE IF NOT EXISTS public.usage_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  campaign_id uuid,
  user_id uuid,
  source_type text NOT NULL,
  provider_name text,
  model_name text,
  model_version text,
  source_name text NOT NULL,
  process_type text NOT NULL,
  input_tokens integer,
  output_tokens integer,
  total_tokens integer,
  latency_ms integer,
  error_flag boolean DEFAULT false,
  error_type text,
  unit_cost numeric,
  total_cost numeric,
  pricing_snapshot jsonb,
  metadata jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  action_key text,
  input_cost_usd numeric,
  output_cost_usd numeric,
  final_price_usd numeric,
  total_cost_usd numeric
);

CREATE TABLE IF NOT EXISTS public.user_company_roles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  company_id uuid NOT NULL,
  role text NOT NULL,
  created_at timestamp without time zone DEFAULT now(),
  status text DEFAULT 'invited'::text,
  invited_at timestamp without time zone,
  accepted_at timestamp without time zone,
  deactivated_at timestamp without time zone,
  updated_at timestamp without time zone,
  name text,
  join_source text
);

CREATE TABLE IF NOT EXISTS public.user_override (
  user_id uuid NOT NULL,
  approved_by uuid,
  credits_granted integer NOT NULL DEFAULT 300,
  reason text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  is_eligible boolean NOT NULL DEFAULT true
);

CREATE TABLE IF NOT EXISTS public.user_preferences (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  default_landing character varying(50) DEFAULT 'command_center'::character varying,
  command_center_pinned boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.users (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  email text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  company_id uuid,
  role text,
  name text,
  phone text,
  is_email_verified boolean NOT NULL DEFAULT false,
  is_phone_verified boolean NOT NULL DEFAULT false,
  auth_level text NOT NULL DEFAULT 'none'::text,
  user_type text,
  credits integer NOT NULL DEFAULT 0,
  last_sign_in_at timestamp with time zone,
  is_deleted boolean NOT NULL DEFAULT false,
  deleted_at timestamp with time zone,
  job_title text,
  updated_at timestamp with time zone,
  supabase_uid text,
  active_company_id uuid,
  onboarding_state text NOT NULL DEFAULT 'active'::text,
  has_password boolean NOT NULL DEFAULT false,
  signup_source text,
  industry text
);

-- ── 2. PRIMARY KEY + UNIQUE + CHECK constraints (idempotent) ────────────────
DO $$
BEGIN
  -- access_requests
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='access_requests_pkey')                              THEN ALTER TABLE public.access_requests ADD CONSTRAINT access_requests_pkey PRIMARY KEY (id); END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='access_requests_status_check')                      THEN ALTER TABLE public.access_requests ADD CONSTRAINT access_requests_status_check CHECK (status = ANY (ARRAY['pending','approved','rejected','deleted'])); END IF;
  -- action_pricing_config
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='action_pricing_config_pkey')                        THEN ALTER TABLE public.action_pricing_config ADD CONSTRAINT action_pricing_config_pkey PRIMARY KEY (id); END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='action_pricing_config_cost_multiplier_check')       THEN ALTER TABLE public.action_pricing_config ADD CONSTRAINT action_pricing_config_cost_multiplier_check CHECK (cost_multiplier >= 0); END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='action_pricing_config_credit_cost_check')           THEN ALTER TABLE public.action_pricing_config ADD CONSTRAINT action_pricing_config_credit_cost_check CHECK (credit_cost IS NULL OR credit_cost >= 0); END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='action_pricing_config_source_type_check')           THEN ALTER TABLE public.action_pricing_config ADD CONSTRAINT action_pricing_config_source_type_check CHECK (source_type IN ('llm','embedding','fixed')); END IF;
  -- community_ai_actions
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='community_ai_actions_pkey')                         THEN ALTER TABLE public.community_ai_actions ADD CONSTRAINT community_ai_actions_pkey PRIMARY KEY (id); END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='community_ai_actions_action_type_check')            THEN ALTER TABLE public.community_ai_actions ADD CONSTRAINT community_ai_actions_action_type_check CHECK (action_type IN ('like','reply','share','follow','schedule','dm')); END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='community_ai_actions_status_check')                 THEN ALTER TABLE public.community_ai_actions ADD CONSTRAINT community_ai_actions_status_check CHECK (status IN ('pending','approved','executed','failed','skipped')); END IF;
  -- community_ai_platform_tokens
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='community_ai_platform_tokens_pkey')                 THEN ALTER TABLE public.community_ai_platform_tokens ADD CONSTRAINT community_ai_platform_tokens_pkey PRIMARY KEY (id); END IF;
  -- companies
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='companies_pkey')                                    THEN ALTER TABLE public.companies ADD CONSTRAINT companies_pkey PRIMARY KEY (id); END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='companies_status_check')                            THEN ALTER TABLE public.companies ADD CONSTRAINT companies_status_check CHECK (status IN ('active','inactive','suspended')); END IF;
  -- company_domains
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='company_domains_pkey')                              THEN ALTER TABLE public.company_domains ADD CONSTRAINT company_domains_pkey PRIMARY KEY (id); END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='unique_final_domain')                               THEN ALTER TABLE public.company_domains ADD CONSTRAINT unique_final_domain UNIQUE (final_domain); END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='final_domain_not_empty')                            THEN ALTER TABLE public.company_domains ADD CONSTRAINT final_domain_not_empty CHECK (final_domain <> ''); END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='company_domains_created_via_check')                 THEN ALTER TABLE public.company_domains ADD CONSTRAINT company_domains_created_via_check CHECK (created_via IN ('user','admin','system')); END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='company_domains_verification_status_check')         THEN ALTER TABLE public.company_domains ADD CONSTRAINT company_domains_verification_status_check CHECK (verification_status IN ('unverified','pending','verified','admin_override')); END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='company_domains_verification_method_check')         THEN ALTER TABLE public.company_domains ADD CONSTRAINT company_domains_verification_method_check CHECK (verification_method IS NULL OR verification_method IN ('dns','http','admin_override')); END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='company_domains_override_reason_required')          THEN ALTER TABLE public.company_domains ADD CONSTRAINT company_domains_override_reason_required CHECK ((verification_status <> 'admin_override') OR ((override_reason IS NOT NULL) AND (length(trim(override_reason)) > 0))); END IF;
  -- credit_transactions
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='credit_transactions_pkey')                          THEN ALTER TABLE public.credit_transactions ADD CONSTRAINT credit_transactions_pkey PRIMARY KEY (id); END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='credit_transactions_idempotency_key_key')           THEN ALTER TABLE public.credit_transactions ADD CONSTRAINT credit_transactions_idempotency_key_key UNIQUE (idempotency_key); END IF;
  -- daily_content_plans
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='daily_content_plans_pkey')                          THEN ALTER TABLE public.daily_content_plans ADD CONSTRAINT daily_content_plans_pkey PRIMARY KEY (id); END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='daily_content_plans_status_check')                  THEN ALTER TABLE public.daily_content_plans ADD CONSTRAINT daily_content_plans_status_check CHECK (status::text = ANY (ARRAY['planned','content-created','media-ready','scheduled','published','failed'])); END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='daily_content_plans_priority_check')                THEN ALTER TABLE public.daily_content_plans ADD CONSTRAINT daily_content_plans_priority_check CHECK (priority::text = ANY (ARRAY['low','medium','high','urgent'])); END IF;
  -- domain_eligibility_cache / domain_whitelist
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='domain_eligibility_cache_pkey')                     THEN ALTER TABLE public.domain_eligibility_cache ADD CONSTRAINT domain_eligibility_cache_pkey PRIMARY KEY (domain); END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='domain_eligibility_cache_status_check')             THEN ALTER TABLE public.domain_eligibility_cache ADD CONSTRAINT domain_eligibility_cache_status_check CHECK (status IN ('eligible','blocked','pending_review')); END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='domain_whitelist_pkey')                             THEN ALTER TABLE public.domain_whitelist ADD CONSTRAINT domain_whitelist_pkey PRIMARY KEY (domain); END IF;
  -- email_jobs
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='email_jobs_pkey')                                   THEN ALTER TABLE public.email_jobs ADD CONSTRAINT email_jobs_pkey PRIMARY KEY (id); END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='email_jobs_job_type_check')                         THEN ALTER TABLE public.email_jobs ADD CONSTRAINT email_jobs_job_type_check CHECK (job_type IN ('magic_link','invite','reset','company_referral','inbound_signup_notice')); END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='email_jobs_status_check')                           THEN ALTER TABLE public.email_jobs ADD CONSTRAINT email_jobs_status_check CHECK (status IN ('pending','processing','sent','failed','dead')); END IF;
  -- free_credit_claims
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='free_credit_claims_pkey')                           THEN ALTER TABLE public.free_credit_claims ADD CONSTRAINT free_credit_claims_pkey PRIMARY KEY (id); END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='free_credit_claims_user_category')                  THEN ALTER TABLE public.free_credit_claims ADD CONSTRAINT free_credit_claims_user_category UNIQUE (user_id, category); END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='free_credit_claims_positive_credits')               THEN ALTER TABLE public.free_credit_claims ADD CONSTRAINT free_credit_claims_positive_credits CHECK (credits_granted > 0); END IF;
  -- free_credit_profiles
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='free_credit_profiles_pkey')                         THEN ALTER TABLE public.free_credit_profiles ADD CONSTRAINT free_credit_profiles_pkey PRIMARY KEY (id); END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='free_credit_profiles_phone_number_key')             THEN ALTER TABLE public.free_credit_profiles ADD CONSTRAINT free_credit_profiles_phone_number_key UNIQUE (phone_number); END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='free_credit_profiles_user_id_key')                  THEN ALTER TABLE public.free_credit_profiles ADD CONSTRAINT free_credit_profiles_user_id_key UNIQUE (user_id); END IF;
  -- invitations
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='invitations_pkey')                                  THEN ALTER TABLE public.invitations ADD CONSTRAINT invitations_pkey PRIMARY KEY (id); END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='invitations_token_hash_key')                        THEN ALTER TABLE public.invitations ADD CONSTRAINT invitations_token_hash_key UNIQUE (token_hash); END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='invitations_role_check')                            THEN ALTER TABLE public.invitations ADD CONSTRAINT invitations_role_check CHECK (role IN ('COMPANY_ADMIN','CONTENT_CREATOR','CONTENT_REVIEWER','CONTENT_PUBLISHER','VIEW_ONLY')); END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='invitations_token_consumed_acceptance_ck')          THEN ALTER TABLE public.invitations ADD CONSTRAINT invitations_token_consumed_acceptance_ck CHECK ((accepted_at IS NULL) OR (token_consumed_at IS NOT NULL)); END IF;
  -- llm_model_pricing
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='llm_model_pricing_pkey')                            THEN ALTER TABLE public.llm_model_pricing ADD CONSTRAINT llm_model_pricing_pkey PRIMARY KEY (id); END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='llm_model_pricing_input_per_1k_usd_check')          THEN ALTER TABLE public.llm_model_pricing ADD CONSTRAINT llm_model_pricing_input_per_1k_usd_check CHECK (input_per_1k_usd >= 0); END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='llm_model_pricing_output_per_1k_usd_check')         THEN ALTER TABLE public.llm_model_pricing ADD CONSTRAINT llm_model_pricing_output_per_1k_usd_check CHECK (output_per_1k_usd >= 0); END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='llm_model_pricing_kind_check')                      THEN ALTER TABLE public.llm_model_pricing ADD CONSTRAINT llm_model_pricing_kind_check CHECK (kind IN ('completion','embedding')); END IF;
  -- organization_credits
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='organization_credits_pkey')                         THEN ALTER TABLE public.organization_credits ADD CONSTRAINT organization_credits_pkey PRIMARY KEY (id); END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='organization_credits_organization_id_key')          THEN ALTER TABLE public.organization_credits ADD CONSTRAINT organization_credits_organization_id_key UNIQUE (organization_id); END IF;
  -- platform_oauth_configs
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='platform_oauth_configs_pkey')                       THEN ALTER TABLE public.platform_oauth_configs ADD CONSTRAINT platform_oauth_configs_pkey PRIMARY KEY (platform); END IF;
  -- scheduled_posts
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='scheduled_posts_pkey')                              THEN ALTER TABLE public.scheduled_posts ADD CONSTRAINT scheduled_posts_pkey PRIMARY KEY (id); END IF;
  -- (chk_* CHECKs on scheduled_posts intentionally omitted from baseline; multi-line/multi-platform CHECKs
  --  re-add cleanly via the existing canonical migration ordering and would bloat this baseline.)
  -- social_accounts
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='social_accounts_pkey')                              THEN ALTER TABLE public.social_accounts ADD CONSTRAINT social_accounts_pkey PRIMARY KEY (id); END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='social_accounts_company_platform_user_unique')      THEN ALTER TABLE public.social_accounts ADD CONSTRAINT social_accounts_company_platform_user_unique UNIQUE (company_id, platform, platform_user_id); END IF;
  -- super_admin_audit_logs
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='super_admin_audit_logs_pkey')                       THEN ALTER TABLE public.super_admin_audit_logs ADD CONSTRAINT super_admin_audit_logs_pkey PRIMARY KEY (id); END IF;
  -- unified_transactions
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='unified_transactions_pkey')                         THEN ALTER TABLE public.unified_transactions ADD CONSTRAINT unified_transactions_pkey PRIMARY KEY (id); END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='unified_transactions_retry_attempt_check')          THEN ALTER TABLE public.unified_transactions ADD CONSTRAINT unified_transactions_retry_attempt_check CHECK (retry_attempt >= 1); END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='unified_transactions_source_type_check')            THEN ALTER TABLE public.unified_transactions ADD CONSTRAINT unified_transactions_source_type_check CHECK (source_type IN ('llm','embedding','cache','external_api','automation_execution','system','internal')); END IF;
  -- usage_events
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='usage_events_pkey')                                 THEN ALTER TABLE public.usage_events ADD CONSTRAINT usage_events_pkey PRIMARY KEY (id); END IF;
  -- user_company_roles
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='user_company_roles_pkey')                           THEN ALTER TABLE public.user_company_roles ADD CONSTRAINT user_company_roles_pkey PRIMARY KEY (id); END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='user_company_roles_status_check')                   THEN ALTER TABLE public.user_company_roles ADD CONSTRAINT user_company_roles_status_check CHECK (status IN ('invited','active','inactive','expired')); END IF;
  -- user_override
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='user_override_pkey')                                THEN ALTER TABLE public.user_override ADD CONSTRAINT user_override_pkey PRIMARY KEY (user_id); END IF;
  -- user_preferences
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='user_preferences_pkey')                             THEN ALTER TABLE public.user_preferences ADD CONSTRAINT user_preferences_pkey PRIMARY KEY (id); END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='unique_user_id')                                    THEN ALTER TABLE public.user_preferences ADD CONSTRAINT unique_user_id UNIQUE (user_id); END IF;
  -- users
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='users_pkey')                                        THEN ALTER TABLE public.users ADD CONSTRAINT users_pkey PRIMARY KEY (id); END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='users_email_key')                                   THEN ALTER TABLE public.users ADD CONSTRAINT users_email_key UNIQUE (email); END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='users_auth_level_check')                            THEN ALTER TABLE public.users ADD CONSTRAINT users_auth_level_check CHECK (auth_level IN ('none','email_verified','email_phone_verified')); END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='users_user_type_check')                             THEN ALTER TABLE public.users ADD CONSTRAINT users_user_type_check CHECK (user_type IN ('trial','paid','enterprise','internal')); END IF;
END $$;

-- ── 3. Indexes (idempotent) ─────────────────────────────────────────────────
-- access_requests
CREATE INDEX IF NOT EXISTS access_requests_domain_idx              ON public.access_requests (domain);
CREATE INDEX IF NOT EXISTS access_requests_status_idx              ON public.access_requests (status, created_at DESC);
CREATE INDEX IF NOT EXISTS access_requests_user_id_idx             ON public.access_requests (user_id);
CREATE INDEX IF NOT EXISTS idx_access_requests_email_approved      ON public.access_requests (email) WHERE status = 'approved';
CREATE UNIQUE INDEX IF NOT EXISTS idx_access_requests_email_approved_unique ON public.access_requests (email) WHERE status = 'approved';
CREATE UNIQUE INDEX IF NOT EXISTS idx_access_requests_email_pending         ON public.access_requests (email) WHERE status = 'pending';
-- action_pricing_config
CREATE UNIQUE INDEX IF NOT EXISTS action_pricing_config_active_uniq ON public.action_pricing_config (action_key) WHERE is_active = true;
CREATE INDEX        IF NOT EXISTS idx_action_pricing_config_effective ON public.action_pricing_config (action_key, effective_from DESC);
CREATE UNIQUE INDEX IF NOT EXISTS uq_action_pricing_config_active   ON public.action_pricing_config (action_key) WHERE is_active = true;
-- companies
CREATE INDEX IF NOT EXISTS idx_companies_free_credit_granted ON public.companies (free_credit_granted_at) WHERE free_credit_granted_at IS NOT NULL;
-- company_domains
CREATE INDEX IF NOT EXISTS idx_company_domains_company_id          ON public.company_domains (company_id);
CREATE INDEX IF NOT EXISTS idx_company_domains_final_domain        ON public.company_domains (final_domain);
CREATE INDEX IF NOT EXISTS idx_company_domains_input_domain        ON public.company_domains (input_domain);
CREATE INDEX IF NOT EXISTS idx_company_domains_verification_status ON public.company_domains (verification_status);
-- credit_transactions
CREATE UNIQUE INDEX IF NOT EXISTS credit_transactions_idempotency_key_lockdown_unique ON public.credit_transactions (idempotency_key) WHERE idempotency_key IS NOT NULL;
CREATE INDEX        IF NOT EXISTS idx_credit_tx_org_expiry         ON public.credit_transactions (organization_id, created_at DESC);
-- daily_content_plans (subset; full set re-applied by canonical migrations)
CREATE INDEX IF NOT EXISTS idx_daily_plans_campaign      ON public.daily_content_plans (campaign_id);
CREATE INDEX IF NOT EXISTS idx_daily_plans_campaign_week ON public.daily_content_plans (campaign_id, week_number);
CREATE INDEX IF NOT EXISTS idx_daily_plans_date          ON public.daily_content_plans (date);
CREATE INDEX IF NOT EXISTS idx_daily_plans_status        ON public.daily_content_plans (status);
-- domain_eligibility_cache
CREATE INDEX IF NOT EXISTS domain_eligibility_cache_expires_idx ON public.domain_eligibility_cache (expires_at);
-- email_jobs (idempotency / pending payload re-added by canonical migration)
CREATE INDEX IF NOT EXISTS email_jobs_status_idx ON public.email_jobs (status, created_at);
-- free_credit_claims
CREATE INDEX IF NOT EXISTS idx_fcc_claimed_at  ON public.free_credit_claims (claimed_at DESC);
CREATE INDEX IF NOT EXISTS idx_fcc_user_category ON public.free_credit_claims (user_id, category);
CREATE INDEX IF NOT EXISTS idx_fcc_user_id     ON public.free_credit_claims (user_id);
-- free_credit_profiles
CREATE INDEX IF NOT EXISTS idx_fcp_created  ON public.free_credit_profiles (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_fcp_org_id   ON public.free_credit_profiles (organization_id);
CREATE INDEX IF NOT EXISTS idx_fcp_phone    ON public.free_credit_profiles (phone_number);
CREATE INDEX IF NOT EXISTS idx_fcp_user_id  ON public.free_credit_profiles (user_id);
-- invitations
CREATE UNIQUE INDEX IF NOT EXISTS invitations_active_unique ON public.invitations (lower(email), company_id) WHERE accepted_at IS NULL AND revoked_at IS NULL;
CREATE INDEX        IF NOT EXISTS invitations_company_id_idx ON public.invitations (company_id) WHERE accepted_at IS NULL AND revoked_at IS NULL;
CREATE INDEX        IF NOT EXISTS invitations_token_hash_idx ON public.invitations (token_hash);
-- llm_model_pricing
CREATE INDEX IF NOT EXISTS idx_llm_model_pricing_effective ON public.llm_model_pricing (provider, model_name, kind, effective_from DESC);
CREATE UNIQUE INDEX IF NOT EXISTS uq_llm_model_pricing_active ON public.llm_model_pricing (provider, model_name, kind) WHERE is_active = true;
-- scheduled_posts (subset)
CREATE INDEX IF NOT EXISTS idx_scheduled_posts_campaign      ON public.scheduled_posts (campaign_id);
CREATE INDEX IF NOT EXISTS idx_scheduled_posts_status        ON public.scheduled_posts (status);
CREATE INDEX IF NOT EXISTS idx_scheduled_posts_scheduled_for ON public.scheduled_posts (scheduled_for);
CREATE INDEX IF NOT EXISTS idx_scheduled_posts_user_id       ON public.scheduled_posts (user_id);
-- social_accounts
CREATE INDEX IF NOT EXISTS idx_social_accounts_active     ON public.social_accounts (is_active);
CREATE INDEX IF NOT EXISTS idx_social_accounts_company_id ON public.social_accounts (company_id);
CREATE INDEX IF NOT EXISTS idx_social_accounts_platform   ON public.social_accounts (platform);
CREATE INDEX IF NOT EXISTS idx_social_accounts_user_id    ON public.social_accounts (user_id);
-- super_admin_audit_logs
CREATE INDEX IF NOT EXISTS super_admin_audit_logs_actor_idx ON public.super_admin_audit_logs (actor_user_id, created_at DESC);
-- unified_transactions
CREATE INDEX IF NOT EXISTS idx_unified_txn_org_created ON public.unified_transactions (organization_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_unified_txn_source      ON public.unified_transactions (source_type, created_at DESC);
-- usage_events
CREATE INDEX IF NOT EXISTS idx_usage_events_org      ON public.usage_events (organization_id, created_at);
CREATE INDEX IF NOT EXISTS idx_usage_events_campaign ON public.usage_events (campaign_id, created_at);
-- user_company_roles
CREATE INDEX IF NOT EXISTS idx_user_company_roles_user_company ON public.user_company_roles (user_id, company_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_user_company_roles_user_company_active ON public.user_company_roles (user_id, company_id) WHERE status = 'active';
-- user_preferences
CREATE INDEX IF NOT EXISTS idx_user_preferences_user_id ON public.user_preferences (user_id);
-- users
CREATE INDEX IF NOT EXISTS idx_users_active_company_id ON public.users (active_company_id) WHERE active_company_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_users_onboarding_state  ON public.users (onboarding_state) WHERE onboarding_state <> 'active';
CREATE UNIQUE INDEX IF NOT EXISTS users_supabase_uid_key ON public.users (supabase_uid) WHERE supabase_uid IS NOT NULL;

-- End of baseline.
