/**
 * DERIVED template asset slots — which user-supplied reference images each
 * canonical design accepts.
 *
 * WHY DERIVATION AND NOT A REGISTRY
 * ---------------------------------
 * A slot is a statement about a design's structure: a layout with one hero
 * figure can host a subject; every layout has a backdrop and an aesthetic; only
 * a multi-panel layout has somewhere to put a second image. All of that is
 * already recorded on the canonical template — family, category, rendering
 * contract, branding intensity, frame/panel geometry. Restating it as a second
 * hand-maintained 251-entry table would create a source of truth that can
 * disagree with the design it describes, and the first template added without a
 * matching entry would silently accept nothing.
 *
 * So: ONE source (the template), read here.
 *
 * WHAT DERIVATION DELIBERATELY DOES NOT DO
 * ----------------------------------------
 * - It never states a `mode`. Mode belongs to the purpose policy
 *   (`PURPOSE_MODE_POLICY`), which is the single authority; a slot that pinned
 *   one would be a second, weaker policy.
 * - It never states a `max`. The omitted value already means 1, which is the
 *   contract the single-asset panel implements. Inventing a number would
 *   promise capacity no surface offers.
 * - It never invents `placement`. Compose geometry has no canonical per-template
 *   source, and coordinates nobody chose would put a user's asset somewhere
 *   arbitrary while reporting success. A compose slot without placement is
 *   refused at routing and never offered by the panel — visible, not guessed.
 *
 * An EXPLICIT `assetSlots` declaration on a template always wins: it is an
 * author's decision about a specific design, and derivation is the default for
 * everything that has not made one.
 */
import type { CreatorTemplate } from './types';
import type { TemplateAssetSlot } from '../content/compositionAssetRouting';

/* ── The rules ──────────────────────────────────────────────────────────────*/

/**
 * `subject` — the person or thing the design is about.
 *
 * Image and carousel layouts have a principal figure. Infographics do not: they
 * are diagrammatic, and their content is the data, so a photographic subject
 * has nowhere to live. Templates with a dedicated `imageComposition` are also
 * excluded — that field exists precisely because those designs dispatch to a
 * fixed structural composition (a split before/after, a centred statistic)
 * whose figure is generated by the composition rather than supplied.
 */
function acceptsSubject(t: CreatorTemplate): boolean {
  if (t.assetFamily === 'infographic') return false;
  return !hasDedicatedComposition(t);
}

function hasDedicatedComposition(t: CreatorTemplate): boolean {
  const c = t.renderingContract?.imageComposition;
  return typeof c === 'string' && c.trim().length > 0;
}

/**
 * `product` — a product photo to feature.
 *
 * Three existing signals name a product design, and any one of them is enough:
 * the rendering contract's purpose key, the gallery category, and the blueprint
 * the design derives from (curated variants carry the blueprint but not the
 * blueprint template's purpose key, so both have to be consulted).
 */
function acceptsProduct(t: CreatorTemplate): boolean {
  if (t.renderingContract?.purposeKey === 'product-showcase-image') return true;
  if (String(t.category || '').trim().toLowerCase() === 'product') return true;
  return blueprintIdOf(t).includes('product');
}

/**
 * `supporting` — a second image beside the subject.
 *
 * Only a multi-panel design has a second place to put one. A carousel with more
 * than one frame is multi-panel by construction; an infographic is multi-panel
 * when its composition declares more than one column; an image is multi-panel
 * only when its composition splits the canvas.
 */
/**
 * The image compositions that divide the canvas.
 *
 * Taken from the vocabulary the renderer actually dispatches on — `list`,
 * `quote`, `split`, `stat` — and `split` is the only member that gives a
 * second image somewhere to be. Naming compositions that do not exist would be
 * a rule about an imaginary design.
 */
const SPLIT_IMAGE_COMPOSITIONS = new Set(['split']);

function acceptsSupporting(t: CreatorTemplate): boolean {
  if (t.assetFamily === 'carousel') return (t.renderingContract?.frameCount ?? 0) > 1;
  if (t.assetFamily === 'infographic') return (t.composition?.columns ?? 0) > 1;
  const c = String(t.renderingContract?.imageComposition || '').trim().toLowerCase();
  return SPLIT_IMAGE_COMPOSITIONS.has(c);
}

/**
 * `logo` — a brand mark placed on the design.
 *
 * Branding intensity already records how much room a design gives the brand.
 * `subtle` is excluded deliberately: those designs minimise brand presence, and
 * accepting a mark only to shrink it out of sight would answer "can I put my
 * logo here?" with a yes the design does not honour.
 */
function acceptsLogo(t: CreatorTemplate): boolean {
  const intensity = t.visualLanguage?.brandingIntensity;
  return intensity === 'balanced' || intensity === 'strong';
}

/** The blueprint a design derives from, for the rules that read it. */
function blueprintIdOf(t: CreatorTemplate): string {
  const meta = (t.metadata ?? {}) as Record<string, unknown>;
  const raw = meta.blueprint_id ?? meta.blueprintId ?? '';
  const fromMeta = typeof raw === 'string' ? raw : '';
  // Curated ids encode the blueprint: sys-curated-<blueprint>-<family>.
  const m = /^sys-curated-(.+)-(?:image|carousel|infographic)$/.exec(String(t.id || ''));
  return `${fromMeta} ${m?.[1] ?? ''}`.trim().toLowerCase();
}

/* ── Derivation ─────────────────────────────────────────────────────────────*/

/**
 * The slots a template accepts, derived from its own canonical metadata.
 *
 * `background` and `style_reference` are universal and need no rule: every
 * design has a backdrop, and every design has a look that a reference can
 * inform. `style_reference` in particular occupies no layout space at all, so
 * there is no structure that could refuse it.
 *
 * Order is the vocabulary's own, so the panel presents the same choices in the
 * same order for every template.
 */
export function deriveTemplateAssetSlots(template: CreatorTemplate): TemplateAssetSlot[] {
  if (!template) return [];
  const slots: TemplateAssetSlot[] = [];
  if (acceptsSubject(template)) slots.push({ purpose: 'subject' });
  if (acceptsProduct(template)) slots.push({ purpose: 'product' });
  slots.push({ purpose: 'background' });
  if (acceptsLogo(template)) slots.push({ purpose: 'logo' });
  if (acceptsSupporting(template)) slots.push({ purpose: 'supporting' });
  slots.push({ purpose: 'style_reference' });
  return slots;
}

/**
 * The template, carrying slots.
 *
 * Cached on the SOURCE OBJECT, so enriching the same template twice returns the
 * same instance. That matters: `getTemplateById(t.id) === t` is a contract the
 * registry tests pin, and a fresh copy per call would break it for every
 * template resolved more than once.
 *
 * A template that already declares `assetSlots` is returned untouched — an
 * author's explicit decision about one design outranks the general rule.
 */
const derived = new WeakMap<CreatorTemplate, CreatorTemplate>();

export function withDerivedAssetSlots<T extends CreatorTemplate>(template: T): T {
  if (!template || typeof template !== 'object') return template;
  if (Array.isArray(template.assetSlots)) return template;
  const cached = derived.get(template);
  if (cached) return cached as T;
  const enriched = { ...template, assetSlots: deriveTemplateAssetSlots(template) };
  derived.set(template, enriched);
  return enriched as T;
}
