export function useCampaignAIViewProps(args: any) {
  const {
    props,
    state,
    external,
    controller,
  } = args;

  const {
    isOpen,
    standalone,
    onMinimize,
    onClose,
    campaignId,
    campaignData,
    governanceLocked,
    context,
    prefilledPlanning,
    initialPlan,
    collectedPlanningContext,
    onBackToRecommendation,
  } = props;

  const {
    campaignLearnings,
    selectedProvider,
    uiErrorMessage,
    uiSuccessMessage,
    activeTab,
    retrievePlanData,
    isRetrievePlanLoading,
    isParsingSavedPlan,
    showLearning,
    setShowLearning,
    showSettings,
    setShowSettings,
    isFullscreen,
    setIsFullscreen,
    messages,
    isTyping,
    modeLoading,
    planAbortRef,
    isSchedulingPlan,
    isLoading,
    messagesEndRef,
    structuredPlan,
    structuredPlanMessageId,
    isBusy,
    selectedQuickOptions,
    setSelectedQuickOptions,
    quickCustomizeMode,
    setQuickCustomizeMode,
    quickCustomizeText,
    setQuickCustomizeText,
    quickCustomContentType,
    setQuickCustomContentType,
    quickCustomContentCount,
    setQuickCustomContentCount,
    quickCustomPlatform,
    setQuickCustomPlatform,
    quickDateYear,
    setQuickDateYear,
    quickDateMonth,
    setQuickDateMonth,
    quickDateDay,
    setQuickDateDay,
    quickCapacityCounts,
    setQuickCapacityCounts,
    quickCapacityCreationMode,
    setQuickCapacityCreationMode,
    showAllTypeCounters,
    setShowAllTypeCounters,
    planningSelectedPlatforms,
    setQuickPlatformContentTypes,
    planningPlatformContentRequests,
    setPlanningPlatformContentRequests,
    planningCrossPlatformSharingEnabled,
    setPlanningCrossPlatformSharingEnabled,
    planningCrossPlatformScheduleMode,
    setPlanningCrossPlatformScheduleMode,
    planningExclusiveCampaigns,
    setPlanningExclusiveCampaigns,
    planningAvailableCountsOverride,
    planningCapacityCountsOverride,
    planningPlatformContentTypePrefs,
    showAllPlatformRequestTypes,
    setShowAllPlatformRequestTypes,
    quickPickPrimaryStyles,
    setQuickPickPrimaryStyles,
    quickPickSecondaryModifiers,
    setQuickPickSecondaryModifiers,
    lastCollectedPlanningContextFromApi,
    hasProvidedPlatformContentRequests,
    showScheduleConfirm,
    setShowScheduleConfirm,
    showPlanOverview,
    setShowPlanOverview,
    reviewWeekNumber,
    setReviewWeekNumber,
    replaceMode,
    setReplaceMode,
    replaceSelection,
    setReplaceSelection,
    newMessage,
    setNewMessage,
    inputClearKey,
    isSavingDraftForView,
    inputRef,
    showPlanPreview,
    setShowPlanPreview,
    selectedPlan,
    hasViewedPlanMessageId,
    hasGeneratedPlanInSession,
    quickPickBackIndex,
  } = state;

  const {
    resolvedCompanyId,
    handleProviderChange,
    platformLabels,
    platformContentTypeOptions,
    platformContentTypeRawOptions,
    hasEffectiveCatalog,
    aiHistory,
    isHistoryLoading,
    auditReport,
    isAuditLoading,
    healthReport,
    isHealthLoading,
    optimizeWeekNumber,
    setOptimizeWeekNumber,
    optimizeReason,
    setOptimizeReason,
    isOptimizingWeek,
    optimizeResult,
    executionPlan,
    isExecutionLoading,
    executionWeekNumber,
    setExecutionWeekNumber,
    schedulerPayload,
    contentAssets,
    isContentLoading,
    contentWeekNumber,
    setContentWeekNumber,
    regenerateInstruction,
    setRegenerateInstruction,
    handleOptimizeWeek,
    loadExecutionPlan,
    handleApproveScheduling,
    handleTrackingLinkClick,
    handleGenerateContent,
    handleRegenerateContent,
    handleApproveContent,
    handleRejectContent,
    analyticsReport,
    learningInsights,
    isPerformanceLoading,
    performanceWeekNumber,
    setPerformanceWeekNumber,
    campaignMemory,
    memoryOverlap,
    forecastReport,
    roiReport,
    businessReport,
    isBusinessLoading,
    platformIntelAssetId,
    setPlatformIntelAssetId,
    platformIntelPlatform,
    setPlatformIntelPlatform,
    platformIntelContentType,
    setPlatformIntelContentType,
    platformIntelData,
    isPlatformIntelLoading,
    handlePlatformIntel,
    handleApplyInsightsToWeek,
  } = external;

  const {
    isRecsChat,
    displayTopic,
    visibleMessages,
    quickPickAttachToMessageId,
    quickPickConfig,
    eligiblePlanningTypes,
    aiMessageIndices,
    canGoBack,
    submitQuickPickAnswer,
    handleQuickPickBack,
    handleQuickPickBackDeeper,
    sendMessage,
    applyPlanOverviewReplacement,
    saveDraftAndViewOnCampaign,
    saveAIContentForPlan,
    serializeStructuredPlanToText,
    commitPlan,
    viewPlan,
    loadSavedPlanAndEdit,
    loadCommittedPlanAndEdit,
    scheduleStructuredPlan,
    isWeeklyPlanMessage,
    handleKeyPress,
    hasPreviousQuestion,
    quickPlatformContentTypes,
  } = controller;

  return {
    isOpen,
    standalone,
    isFullscreen,
    isRecsChat,
    displayTopic,
    showLearning,
    setShowLearning,
    showSettings,
    setShowSettings,
    setIsFullscreen,
    onMinimize,
    onClose,
    campaignLearnings,
    selectedProvider,
    handleProviderChange,
    uiErrorMessage,
    uiSuccessMessage,
    activeTab,
    retrievePlanData,
    isRetrievePlanLoading,
    isParsingSavedPlan,
    resolvedCompanyId,
    campaignId,
    loadSavedPlanAndEdit,
    loadCommittedPlanAndEdit,
    nonChatContentProps: {
      activeTab: activeTab as 'history' | 'audit' | 'execution' | 'content' | 'performance' | 'memory' | 'business' | 'platform',
      aiHistory,
      isHistoryLoading,
      isAuditLoading,
      auditReport,
      isHealthLoading,
      healthReport,
      optimizeWeekNumber,
      setOptimizeWeekNumber,
      optimizeReason,
      setOptimizeReason,
      handleOptimizeWeek,
      isOptimizingWeek,
      optimizeResult,
      executionWeekNumber,
      setExecutionWeekNumber,
      loadExecutionPlan,
      isExecutionLoading,
      handleApproveScheduling,
      executionPlan,
      schedulerPayload,
      campaignId,
      contentWeekNumber,
      setContentWeekNumber,
      regenerateInstruction,
      setRegenerateInstruction,
      isContentLoading,
      contentAssets,
      handleTrackingLinkClick,
      handleRegenerateContent,
      handleApproveContent,
      handleRejectContent,
      handleGenerateContent,
      performanceWeekNumber,
      setPerformanceWeekNumber,
      handleApplyInsightsToWeek,
      isPerformanceLoading,
      analyticsReport,
      learningInsights,
      campaignMemory,
      memoryOverlap,
      isBusinessLoading,
      forecastReport,
      roiReport,
      businessReport,
      platformIntelAssetId,
      setPlatformIntelAssetId,
      platformIntelPlatform,
      setPlatformIntelPlatform,
      platformIntelContentType,
      setPlatformIntelContentType,
      handlePlatformIntel,
      isPlatformIntelLoading,
      platformIntelData,
    },
    messageListProps: {
      visibleMessages,
      structuredPlan,
      structuredPlanMessageId,
      isBusy,
      campaignId,
      governanceLocked,
      isRecsChat,
      quickPickAttachToMessageId,
      quickPickConfig,
      hideQuickPickPanel: state.hideQuickPickPanel,
      canGoBack,
      quickPickBackIndex,
      aiMessageIndices,
      onBackToRecommendation,
      handleQuickPickBack,
      handleQuickPickBackDeeper,
      submitQuickPickAnswer,
      sendMessage,
      selectedQuickOptions,
      setSelectedQuickOptions,
      quickCustomizeMode,
      setQuickCustomizeMode,
      quickCustomizeText,
      setQuickCustomizeText,
      quickCustomContentType,
      setQuickCustomContentType,
      quickCustomContentCount,
      setQuickCustomContentCount,
      quickCustomPlatform,
      setQuickCustomPlatform,
      quickDateYear,
      setQuickDateYear,
      quickDateMonth,
      setQuickDateMonth,
      quickDateDay,
      setQuickDateDay,
      quickCapacityCounts,
      setQuickCapacityCounts,
      quickCapacityCreationMode,
      setQuickCapacityCreationMode,
      showAllTypeCounters,
      setShowAllTypeCounters,
      planningSelectedPlatforms,
      platformLabels,
      platformContentTypeOptions,
      platformContentTypeRawOptions,
      eligiblePlanningTypes,
      quickPlatformContentTypes,
      setQuickPlatformContentTypes,
      setHideQuickPickPanel: state.setHideQuickPickPanel,
      hasEffectiveCatalog,
      planningPlatformContentRequests,
      setPlanningPlatformContentRequests,
      planningCrossPlatformSharingEnabled,
      setPlanningCrossPlatformSharingEnabled,
      planningCrossPlatformScheduleMode,
      setPlanningCrossPlatformScheduleMode,
      planningExclusiveCampaigns,
      setPlanningExclusiveCampaigns,
      planningAvailableCountsOverride,
      planningCapacityCountsOverride,
      prefilledPlanning,
      collectedPlanningContext,
      planningPlatformContentTypePrefs,
      showAllPlatformRequestTypes,
      setShowAllPlatformRequestTypes,
      quickPickPrimaryStyles,
      setQuickPickPrimaryStyles,
      quickPickSecondaryModifiers,
      setQuickPickSecondaryModifiers,
      lastCollectedPlanningContextFromApi,
      hasProvidedPlatformContentRequests,
      planningPlatformContentRequestsForPreview: planningPlatformContentRequests,
      planningCrossPlatformSharingEnabledForPreview: planningCrossPlatformSharingEnabled,
      planningCrossPlatformScheduleModeForPreview: planningCrossPlatformScheduleMode,
      onSchedulePlan: () => setShowScheduleConfirm(true),
    },
    typingStateProps: {
      isTyping,
      activeTab,
      messages,
      modeLoading,
      campaignData,
      initialPlan,
      planAbortRef,
      isSchedulingPlan,
      isLoading,
      isRecsChat,
      selectedProvider,
    },
    messagesEndRef,
    planOverviewProps: {
      isOpen: showPlanOverview,
      structuredPlan,
      reviewWeekNumber,
      replaceMode,
      replaceSelection,
      newMessage,
      inputClearKey,
      isBusy,
      isLoading,
      isTyping,
      isRecsChat,
      uiErrorMessage,
      messages,
      structuredPlanMessageId,
      context,
      campaignId,
      isSavingDraftForView,
      onClose: () => setShowPlanOverview(false),
      onSetReviewWeekNumber: setReviewWeekNumber,
      onSetNewMessage: setNewMessage,
      onSetReplaceMode: setReplaceMode,
      onSetReplaceSelection: setReplaceSelection,
      onSetUiErrorMessage: state.setUiErrorMessage,
      onSetInputRef: (el: any) => { inputRef.current = el; },
      onPromptDailyWeek: (week: number) => {
        setNewMessage(`Generate the daily plan for Week ${week}.`);
        setTimeout(() => inputRef.current?.focus(), 100);
      },
      onSubmitInput: () => {
        if (replaceMode) {
          applyPlanOverviewReplacement();
          return;
        }
        void sendMessage();
      },
      onSaveDraftAndView: () => saveDraftAndViewOnCampaign(),
      onSaveForLater: () => {
        if (!structuredPlan) return;
        setShowPlanOverview(false);
        saveAIContentForPlan(serializeStructuredPlanToText(structuredPlan), structuredPlan);
      },
      onSubmitPlan: () => commitPlan(),
      planningContext: {
        lastCollectedPlanningContextFromApi,
        prefilledPlanning: (prefilledPlanning as Record<string, unknown> | null) ?? null,
        collectedPlanningContext: (collectedPlanningContext as Record<string, unknown> | null) ?? null,
        hasProvidedPlatformContentRequests,
        planningPlatformContentRequests,
        planningCrossPlatformSharingEnabled,
        planningCrossPlatformScheduleMode,
      },
      inputRef,
      messagesEndRef,
    },
    planPreviewProps: {
      isOpen: showPlanPreview && !showPlanOverview,
      selectedPlan,
      onClose: () => state.setShowPlanPreview(false),
      onSubmit: (plan: any) => {
        state.setShowPlanPreview(false);
        commitPlan(plan);
      },
      onSaveForLater: (plan: any) => {
        state.setShowPlanPreview(false);
        saveAIContentForPlan(plan);
      },
    },
    scheduleConfirmProps: {
      isOpen: showScheduleConfirm,
      isSchedulingPlan,
      governanceLocked,
      onCancel: () => setShowScheduleConfirm(false),
      onConfirm: scheduleStructuredPlan,
    },
    inputFooterProps: {
      messages,
      isWeeklyPlanMessage,
      hasViewedPlanMessageId,
      structuredPlan,
      hasGeneratedPlanInSession,
      isBusy,
      governanceLocked,
      structuredPlanMessageId,
      viewPlan,
      commitPlan,
      saveAIContentForPlan,
      activeTab,
      context,
      hasPreviousQuestion,
      quickPickBackIndex,
      aiMessageIndices,
      onBackToRecommendation,
      handleQuickPickBack,
      handleQuickPickBackDeeper,
      newMessage,
      inputClearKey,
      setInputRef: (el: any) => { inputRef.current = el; },
      setNewMessage,
      handleKeyPress,
      displayTopic,
      isRecsChat,
      onVoiceTranscription: (text: string) => setNewMessage(text),
      onSend: () => { void sendMessage(); },
      isLoading,
    },
  };
}
