import { saveCampaignMessage } from './campaignChatStorage';

export function useCampaignAIControllerArgs(args: any) {
  const {
    props,
    state,
    planningCatalog,
    external,
  } = args;

  const {
    isOpen,
    onClose,
    onMinimize,
    context,
    companyId,
    campaignId,
    campaignData,
    recommendationContext,
    onProgramGenerated,
    governanceLocked,
    optimizationContext,
    prefilledPlanning,
    initialPlan,
    standalone,
    vetScope,
    collectedPlanningContext,
    forceFreshPlanningThread,
    onBackToRecommendation,
  } = props;

  return {
    props: {
      isOpen,
      onClose,
      onMinimize,
      context,
      companyId,
      campaignId,
      campaignData,
      recommendationContext,
      onProgramGenerated,
      governanceLocked,
      optimizationContext,
      prefilledPlanning,
      initialPlan,
      standalone,
      vetScope,
      collectedPlanningContext,
      forceFreshPlanningThread,
      onBackToRecommendation,
    },
    state: {
      messages: state.messages,
      setMessages: state.setMessages,
      newMessage: state.newMessage,
      setNewMessage: state.setNewMessage,
      inputClearKey: state.inputClearKey,
      setInputClearKey: state.setInputClearKey,
      setIsTyping: state.setIsTyping,
      isLoading: state.isLoading,
      setIsLoading: state.setIsLoading,
      setUiErrorMessage: state.setUiErrorMessage,
      selectedProvider: state.selectedProvider,
      modeLoading: state.modeLoading,
      setModeLoading: state.setModeLoading,
      structuredPlan: state.structuredPlan,
      setStructuredPlan: state.setStructuredPlan,
      structuredPlanMessageId: state.structuredPlanMessageId,
      setStructuredPlanMessageId: state.setStructuredPlanMessageId,
      setHasGeneratedPlanInSession: state.setHasGeneratedPlanInSession,
      reviewWeekNumber: state.reviewWeekNumber,
      setReviewWeekNumber: state.setReviewWeekNumber,
      replaceMode: state.replaceMode,
      setReplaceMode: state.setReplaceMode,
      replaceSelection: state.replaceSelection,
      setReplaceSelection: state.setReplaceSelection,
      setShowScheduleConfirm: state.setShowScheduleConfirm,
      setIsSchedulingPlan: state.setIsSchedulingPlan,
      setUiSuccessMessage: state.setUiSuccessMessage,
      hasViewedPlanMessageId: state.hasViewedPlanMessageId,
      setHasViewedPlanMessageId: state.setHasViewedPlanMessageId,
      showPlanOverview: state.showPlanOverview,
      setShowPlanOverview: state.setShowPlanOverview,
      isSavingDraftForView: state.isSavingDraftForView,
      setIsSavingDraftForView: state.setIsSavingDraftForView,
      retrievePlanData: state.retrievePlanData,
      setRetrievePlanData: state.setRetrievePlanData,
      planSource: state.planSource,
      setPlanSource: state.setPlanSource,
      setShowDateSelection: state.setShowDateSelection,
      selectedPlan: state.selectedPlan,
      setSelectedPlan: state.setSelectedPlan,
      commitStartDate: state.commitStartDate,
      setCommitStartDate: state.setCommitStartDate,
      commitDurationWeeks: state.commitDurationWeeks,
      setCommitDurationWeeks: state.setCommitDurationWeeks,
      selectedQuickOptions: state.selectedQuickOptions,
      setSelectedQuickOptions: state.setSelectedQuickOptions,
      quickPickPrimaryStyles: state.quickPickPrimaryStyles,
      setQuickPickPrimaryStyles: state.setQuickPickPrimaryStyles,
      quickPickSecondaryModifiers: state.quickPickSecondaryModifiers,
      setQuickPickSecondaryModifiers: state.setQuickPickSecondaryModifiers,
      quickCustomizeMode: state.quickCustomizeMode,
      setQuickCustomizeMode: state.setQuickCustomizeMode,
      quickCustomizeText: state.quickCustomizeText,
      setQuickCustomizeText: state.setQuickCustomizeText,
      quickCustomContentType: state.quickCustomContentType,
      setQuickCustomContentType: state.setQuickCustomContentType,
      quickCustomContentCount: state.quickCustomContentCount,
      setQuickCustomContentCount: state.setQuickCustomContentCount,
      quickCustomPlatform: state.quickCustomPlatform,
      setQuickCustomPlatform: state.setQuickCustomPlatform,
      hideQuickPickPanel: state.hideQuickPickPanel,
      setHideQuickPickPanel: state.setHideQuickPickPanel,
      quickPickBackIndex: state.quickPickBackIndex,
      setQuickPickBackIndex: state.setQuickPickBackIndex,
      quickPickReplaceTruncateToRef: state.quickPickReplaceTruncateToRef,
      isNavigatingBackRef: state.isNavigatingBackRef,
      quickDateYear: state.quickDateYear,
      setQuickDateYear: state.setQuickDateYear,
      quickDateMonth: state.quickDateMonth,
      setQuickDateMonth: state.setQuickDateMonth,
      quickDateDay: state.quickDateDay,
      setQuickDateDay: state.setQuickDateDay,
      quickCapacityCounts: state.quickCapacityCounts,
      setQuickCapacityCounts: state.setQuickCapacityCounts,
      planningAvailableCountsOverride: state.planningAvailableCountsOverride,
      setPlanningAvailableCountsOverride: state.setPlanningAvailableCountsOverride,
      planningCapacityCountsOverride: state.planningCapacityCountsOverride,
      setPlanningCapacityCountsOverride: state.setPlanningCapacityCountsOverride,
      quickCapacityCreationMode: state.quickCapacityCreationMode,
      setQuickCapacityCreationMode: state.setQuickCapacityCreationMode,
      showAllTypeCounters: state.showAllTypeCounters,
      setShowAllTypeCounters: state.setShowAllTypeCounters,
      planningSelectedPlatforms: state.planningSelectedPlatforms,
      setPlanningSelectedPlatforms: state.setPlanningSelectedPlatforms,
      quickPlatformContentTypes: state.quickPlatformContentTypes,
      setQuickPlatformContentTypes: state.setQuickPlatformContentTypes,
      planningPlatformContentTypePrefs: state.planningPlatformContentTypePrefs,
      setPlanningPlatformContentTypePrefs: state.setPlanningPlatformContentTypePrefs,
      planningPlatformContentRequests: state.planningPlatformContentRequests,
      setPlanningPlatformContentRequests: state.setPlanningPlatformContentRequests,
      hasProvidedPlatformContentRequests: state.hasProvidedPlatformContentRequests,
      setHasProvidedPlatformContentRequests: state.setHasProvidedPlatformContentRequests,
      planningCrossPlatformSharingEnabled: state.planningCrossPlatformSharingEnabled,
      setPlanningCrossPlatformSharingEnabled: state.setPlanningCrossPlatformSharingEnabled,
      planningCrossPlatformScheduleMode: state.planningCrossPlatformScheduleMode,
      setPlanningCrossPlatformScheduleMode: state.setPlanningCrossPlatformScheduleMode,
      showAllPlatformRequestTypes: state.showAllPlatformRequestTypes,
      setShowAllPlatformRequestTypes: state.setShowAllPlatformRequestTypes,
      planningAvailableTypeHints: state.planningAvailableTypeHints,
      setPlanningAvailableTypeHints: state.setPlanningAvailableTypeHints,
      planningCapacityTypeHints: state.planningCapacityTypeHints,
      setPlanningCapacityTypeHints: state.setPlanningCapacityTypeHints,
      planningExclusiveCampaigns: state.planningExclusiveCampaigns,
      setPlanningExclusiveCampaigns: state.setPlanningExclusiveCampaigns,
      hasProvidedExclusiveCampaigns: state.hasProvidedExclusiveCampaigns,
      setHasProvidedExclusiveCampaigns: state.setHasProvidedExclusiveCampaigns,
      lastCollectedPlanningContextFromApi: state.lastCollectedPlanningContextFromApi,
      setLastCollectedPlanningContextFromApi: state.setLastCollectedPlanningContextFromApi,
      inputRef: state.inputRef,
      messagesEndRef: state.messagesEndRef,
      planAbortRef: state.planAbortRef,
      autoTriggerPlanRef: state.autoTriggerPlanRef,
      sendMessageRef: state.sendMessageRef,
      isBusy: state.isBusy,
      pendingAmendment: state.pendingAmendment,
      setPendingAmendment: state.setPendingAmendment,
      showPlanPreview: state.showPlanPreview,
      setShowPlanPreview: state.setShowPlanPreview,
      setIsParsingSavedPlan: state.setIsParsingSavedPlan,
      campaignLearnings: state.campaignLearnings,
    },
    planningCatalog: {
      planDurationLimit: planningCatalog.planDurationLimit,
      platformLabels: planningCatalog.platformLabels,
      platformQuickPickOptions: planningCatalog.platformQuickPickOptions,
      configuredPlatformKeys: planningCatalog.configuredPlatformKeys,
      platformContentTypeOptions: planningCatalog.platformContentTypeOptions,
      allCatalogContentTypeQuickPickOptions: planningCatalog.allCatalogContentTypeQuickPickOptions,
      creatorDependentQuickPickOptions: planningCatalog.creatorDependentQuickPickOptions,
      platformExtractCandidates: planningCatalog.platformExtractCandidates,
    },
    external: {
      resolvedCompanyId: external.resolvedCompanyId,
      hasAnsweredPlanningKeyValue: external.hasAnsweredPlanningKeyValue,
    },
    saveCampaignMessage,
  };
}
