/**
 * Activity-consumption correlation envelope (Phase 1 — correlation foundation).
 *
 * This is a CORRELATION construct ONLY. It is never a billing / credit / action
 * key. It lets the platform aggregate ALL resource consumption (LLM tokens,
 * media, external API) generated by a single user activity under one identifier.
 *
 *   - referenceType: the SEMANTIC activity type. Examples:
 *       'bolt_run' | 'creator_asset' | 'campaign_plan' | 'blog_generation'
 *       | 'blog_repurpose' | 'lead_job' | 'active_leads' | 'opportunity_discovery'
 *       | 'recommendation_generation'
 *     It MUST NOT contain an action_key / billing key / credit key.
 *   - referenceId: the activity identifier (run_id / campaign_id / blog_id /
 *       job_id / execution_id …).
 *   - parentActivityId: optional run-grain parent for nested activities (e.g.
 *       a creator_asset whose parent is the bolt_run).
 *
 * Written through to unified_transactions.reference_type / reference_id
 * (+ metadata.parent_activity_id) by usageLedgerService.logUsageEvent.
 */
export type CorrelationRef = {
  referenceType?: string | null;
  referenceId?: string | null;
  parentActivityId?: string | null;
};

/** Canonical semantic activity types (referenceType values). */
export const ACTIVITY_TYPE = {
  BOLT_RUN: 'bolt_run',
  CREATOR_ASSET: 'creator_asset',
  CAMPAIGN_PLAN: 'campaign_plan',
  BLOG_GENERATION: 'blog_generation',
  BLOG_REPURPOSE: 'blog_repurpose',
  LEAD_JOB: 'lead_job',
  ACTIVE_LEADS: 'active_leads',
  OPPORTUNITY_DISCOVERY: 'opportunity_discovery',
  RECOMMENDATION_GENERATION: 'recommendation_generation',
} as const;

export type ActivityType = (typeof ACTIVITY_TYPE)[keyof typeof ACTIVITY_TYPE];

/** Normalize a possibly-partial correlation source into the gateway field shape. */
export function toCorrelationRef(src: CorrelationRef | null | undefined): CorrelationRef {
  if (!src) return { referenceType: null, referenceId: null, parentActivityId: null };
  return {
    referenceType: src.referenceType ?? null,
    referenceId: src.referenceId ?? null,
    parentActivityId: src.parentActivityId ?? null,
  };
}
